using System;

public class EquipParamWeapon : ParamBase<EquipParamWeapon>
{
    public int ID { get { return this.GenericParam.GetValue<int>("ID"); } set { this.GenericParam.SetValue("ID", value); } }
    public string Name { get { return this.GenericParam.GetValue<string>("Name"); } set { this.GenericParam.SetValue("Name", value); } }
    public byte disableParam_NT { get { return this.GenericParam.GetValue<byte>("disableParam_NT"); } set { this.GenericParam.SetValue("disableParam_NT", value); } }
    public byte disableParamReserve1 { get { return this.GenericParam.GetValue<byte>("disableParamReserve1"); } set { this.GenericParam.SetValue("disableParamReserve1", value); } }
    public byte[] disableParamReserve2 { get { return this.GenericParam.GetValue<byte[]>("disableParamReserve2"); } set { this.GenericParam.SetValue("disableParamReserve2", value); } }
    public int behaviorVariationId { get { return this.GenericParam.GetValue<int>("behaviorVariationId"); } set { this.GenericParam.SetValue("behaviorVariationId", value); } }
    public int sortId { get { return this.GenericParam.GetValue<int>("sortId"); } set { this.GenericParam.SetValue("sortId", value); } }
    public uint wanderingEquipId { get { return this.GenericParam.GetValue<uint>("wanderingEquipId"); } set { this.GenericParam.SetValue("wanderingEquipId", value); } }
    public float weight { get { return this.GenericParam.GetValue<float>("weight"); } set { this.GenericParam.SetValue("weight", value); } }
    public float weaponWeightRate { get { return this.GenericParam.GetValue<float>("weaponWeightRate"); } set { this.GenericParam.SetValue("weaponWeightRate", value); } }
    public int fixPrice { get { return this.GenericParam.GetValue<int>("fixPrice"); } set { this.GenericParam.SetValue("fixPrice", value); } }
    public int reinforcePrice { get { return this.GenericParam.GetValue<int>("reinforcePrice"); } set { this.GenericParam.SetValue("reinforcePrice", value); } }
    public int sellValue { get { return this.GenericParam.GetValue<int>("sellValue"); } set { this.GenericParam.SetValue("sellValue", value); } }
    public float correctStrength { get { return this.GenericParam.GetValue<float>("correctStrength"); } set { this.GenericParam.SetValue("correctStrength", value); } }
    public float correctAgility { get { return this.GenericParam.GetValue<float>("correctAgility"); } set { this.GenericParam.SetValue("correctAgility", value); } }
    public float correctMagic { get { return this.GenericParam.GetValue<float>("correctMagic"); } set { this.GenericParam.SetValue("correctMagic", value); } }
    public float correctFaith { get { return this.GenericParam.GetValue<float>("correctFaith"); } set { this.GenericParam.SetValue("correctFaith", value); } }
    public float physGuardCutRate { get { return this.GenericParam.GetValue<float>("physGuardCutRate"); } set { this.GenericParam.SetValue("physGuardCutRate", value); } }
    public float magGuardCutRate { get { return this.GenericParam.GetValue<float>("magGuardCutRate"); } set { this.GenericParam.SetValue("magGuardCutRate", value); } }
    public float fireGuardCutRate { get { return this.GenericParam.GetValue<float>("fireGuardCutRate"); } set { this.GenericParam.SetValue("fireGuardCutRate", value); } }
    public float thunGuardCutRate { get { return this.GenericParam.GetValue<float>("thunGuardCutRate"); } set { this.GenericParam.SetValue("thunGuardCutRate", value); } }
    public int spEffectBehaviorId0 { get { return this.GenericParam.GetValue<int>("spEffectBehaviorId0"); } set { this.GenericParam.SetValue("spEffectBehaviorId0", value); } }
    public int spEffectBehaviorId1 { get { return this.GenericParam.GetValue<int>("spEffectBehaviorId1"); } set { this.GenericParam.SetValue("spEffectBehaviorId1", value); } }
    public int spEffectBehaviorId2 { get { return this.GenericParam.GetValue<int>("spEffectBehaviorId2"); } set { this.GenericParam.SetValue("spEffectBehaviorId2", value); } }
    public int residentSpEffectId { get { return this.GenericParam.GetValue<int>("residentSpEffectId"); } set { this.GenericParam.SetValue("residentSpEffectId", value); } }
    public int residentSpEffectId1 { get { return this.GenericParam.GetValue<int>("residentSpEffectId1"); } set { this.GenericParam.SetValue("residentSpEffectId1", value); } }
    public int residentSpEffectId2 { get { return this.GenericParam.GetValue<int>("residentSpEffectId2"); } set { this.GenericParam.SetValue("residentSpEffectId2", value); } }
    public int materialSetId { get { return this.GenericParam.GetValue<int>("materialSetId"); } set { this.GenericParam.SetValue("materialSetId", value); } }
    public int originEquipWep { get { return this.GenericParam.GetValue<int>("originEquipWep"); } set { this.GenericParam.SetValue("originEquipWep", value); } }
    public int originEquipWep1 { get { return this.GenericParam.GetValue<int>("originEquipWep1"); } set { this.GenericParam.SetValue("originEquipWep1", value); } }
    public int originEquipWep2 { get { return this.GenericParam.GetValue<int>("originEquipWep2"); } set { this.GenericParam.SetValue("originEquipWep2", value); } }
    public int originEquipWep3 { get { return this.GenericParam.GetValue<int>("originEquipWep3"); } set { this.GenericParam.SetValue("originEquipWep3", value); } }
    public int originEquipWep4 { get { return this.GenericParam.GetValue<int>("originEquipWep4"); } set { this.GenericParam.SetValue("originEquipWep4", value); } }
    public int originEquipWep5 { get { return this.GenericParam.GetValue<int>("originEquipWep5"); } set { this.GenericParam.SetValue("originEquipWep5", value); } }
    public int originEquipWep6 { get { return this.GenericParam.GetValue<int>("originEquipWep6"); } set { this.GenericParam.SetValue("originEquipWep6", value); } }
    public int originEquipWep7 { get { return this.GenericParam.GetValue<int>("originEquipWep7"); } set { this.GenericParam.SetValue("originEquipWep7", value); } }
    public int originEquipWep8 { get { return this.GenericParam.GetValue<int>("originEquipWep8"); } set { this.GenericParam.SetValue("originEquipWep8", value); } }
    public int originEquipWep9 { get { return this.GenericParam.GetValue<int>("originEquipWep9"); } set { this.GenericParam.SetValue("originEquipWep9", value); } }
    public int originEquipWep10 { get { return this.GenericParam.GetValue<int>("originEquipWep10"); } set { this.GenericParam.SetValue("originEquipWep10", value); } }
    public int originEquipWep11 { get { return this.GenericParam.GetValue<int>("originEquipWep11"); } set { this.GenericParam.SetValue("originEquipWep11", value); } }
    public int originEquipWep12 { get { return this.GenericParam.GetValue<int>("originEquipWep12"); } set { this.GenericParam.SetValue("originEquipWep12", value); } }
    public int originEquipWep13 { get { return this.GenericParam.GetValue<int>("originEquipWep13"); } set { this.GenericParam.SetValue("originEquipWep13", value); } }
    public int originEquipWep14 { get { return this.GenericParam.GetValue<int>("originEquipWep14"); } set { this.GenericParam.SetValue("originEquipWep14", value); } }
    public int originEquipWep15 { get { return this.GenericParam.GetValue<int>("originEquipWep15"); } set { this.GenericParam.SetValue("originEquipWep15", value); } }
    public float weakA_DamageRate { get { return this.GenericParam.GetValue<float>("weakA_DamageRate"); } set { this.GenericParam.SetValue("weakA_DamageRate", value); } }
    public float weakB_DamageRate { get { return this.GenericParam.GetValue<float>("weakB_DamageRate"); } set { this.GenericParam.SetValue("weakB_DamageRate", value); } }
    public float weakC_DamageRate { get { return this.GenericParam.GetValue<float>("weakC_DamageRate"); } set { this.GenericParam.SetValue("weakC_DamageRate", value); } }
    public float weakD_DamageRate { get { return this.GenericParam.GetValue<float>("weakD_DamageRate"); } set { this.GenericParam.SetValue("weakD_DamageRate", value); } }
    public float sleepGuardResist_MaxCorrect { get { return this.GenericParam.GetValue<float>("sleepGuardResist_MaxCorrect"); } set { this.GenericParam.SetValue("sleepGuardResist_MaxCorrect", value); } }
    public float madnessGuardResist_MaxCorrect { get { return this.GenericParam.GetValue<float>("madnessGuardResist_MaxCorrect"); } set { this.GenericParam.SetValue("madnessGuardResist_MaxCorrect", value); } }
    public float saWeaponDamage { get { return this.GenericParam.GetValue<float>("saWeaponDamage"); } set { this.GenericParam.SetValue("saWeaponDamage", value); } }
    public ushort equipModelId { get { return this.GenericParam.GetValue<ushort>("equipModelId"); } set { this.GenericParam.SetValue("equipModelId", value); } }
    public ushort iconId { get { return this.GenericParam.GetValue<ushort>("iconId"); } set { this.GenericParam.SetValue("iconId", value); } }
    public ushort durability { get { return this.GenericParam.GetValue<ushort>("durability"); } set { this.GenericParam.SetValue("durability", value); } }
    public ushort durabilityMax { get { return this.GenericParam.GetValue<ushort>("durabilityMax"); } set { this.GenericParam.SetValue("durabilityMax", value); } }
    public ushort attackThrowEscape { get { return this.GenericParam.GetValue<ushort>("attackThrowEscape"); } set { this.GenericParam.SetValue("attackThrowEscape", value); } }
    public short parryDamageLife { get { return this.GenericParam.GetValue<short>("parryDamageLife"); } set { this.GenericParam.SetValue("parryDamageLife", value); } }
    public ushort attackBasePhysics { get { return this.GenericParam.GetValue<ushort>("attackBasePhysics"); } set { this.GenericParam.SetValue("attackBasePhysics", value); } }
    public ushort attackBaseMagic { get { return this.GenericParam.GetValue<ushort>("attackBaseMagic"); } set { this.GenericParam.SetValue("attackBaseMagic", value); } }
    public ushort attackBaseFire { get { return this.GenericParam.GetValue<ushort>("attackBaseFire"); } set { this.GenericParam.SetValue("attackBaseFire", value); } }
    public ushort attackBaseThunder { get { return this.GenericParam.GetValue<ushort>("attackBaseThunder"); } set { this.GenericParam.SetValue("attackBaseThunder", value); } }
    public ushort attackBaseStamina { get { return this.GenericParam.GetValue<ushort>("attackBaseStamina"); } set { this.GenericParam.SetValue("attackBaseStamina", value); } }
    public short guardAngle { get { return this.GenericParam.GetValue<short>("guardAngle"); } set { this.GenericParam.SetValue("guardAngle", value); } }
    public float saDurability { get { return this.GenericParam.GetValue<float>("saDurability"); } set { this.GenericParam.SetValue("saDurability", value); } }
    public short staminaGuardDef { get { return this.GenericParam.GetValue<short>("staminaGuardDef"); } set { this.GenericParam.SetValue("staminaGuardDef", value); } }
    public short reinforceTypeId { get { return this.GenericParam.GetValue<short>("reinforceTypeId"); } set { this.GenericParam.SetValue("reinforceTypeId", value); } }
    public short trophySGradeId { get { return this.GenericParam.GetValue<short>("trophySGradeId"); } set { this.GenericParam.SetValue("trophySGradeId", value); } }
    public short trophySeqId { get { return this.GenericParam.GetValue<short>("trophySeqId"); } set { this.GenericParam.SetValue("trophySeqId", value); } }
    public short throwAtkRate { get { return this.GenericParam.GetValue<short>("throwAtkRate"); } set { this.GenericParam.SetValue("throwAtkRate", value); } }
    public short bowDistRate { get { return this.GenericParam.GetValue<short>("bowDistRate"); } set { this.GenericParam.SetValue("bowDistRate", value); } }
    public byte equipModelCategory { get { return this.GenericParam.GetValue<byte>("equipModelCategory"); } set { this.GenericParam.SetValue("equipModelCategory", value); } }
    public byte equipModelGender { get { return this.GenericParam.GetValue<byte>("equipModelGender"); } set { this.GenericParam.SetValue("equipModelGender", value); } }
    public byte weaponCategory { get { return this.GenericParam.GetValue<byte>("weaponCategory"); } set { this.GenericParam.SetValue("weaponCategory", value); } }
    public byte wepmotionCategory { get { return this.GenericParam.GetValue<byte>("wepmotionCategory"); } set { this.GenericParam.SetValue("wepmotionCategory", value); } }
    public byte guardmotionCategory { get { return this.GenericParam.GetValue<byte>("guardmotionCategory"); } set { this.GenericParam.SetValue("guardmotionCategory", value); } }
    public byte atkMaterial { get { return this.GenericParam.GetValue<byte>("atkMaterial"); } set { this.GenericParam.SetValue("atkMaterial", value); } }
    public ushort defSeMaterial1 { get { return this.GenericParam.GetValue<ushort>("defSeMaterial1"); } set { this.GenericParam.SetValue("defSeMaterial1", value); } }
    public byte correctType_Physics { get { return this.GenericParam.GetValue<byte>("correctType_Physics"); } set { this.GenericParam.SetValue("correctType_Physics", value); } }
    public byte spAttribute { get { return this.GenericParam.GetValue<byte>("spAttribute"); } set { this.GenericParam.SetValue("spAttribute", value); } }
    public ushort spAtkcategory { get { return this.GenericParam.GetValue<ushort>("spAtkcategory"); } set { this.GenericParam.SetValue("spAtkcategory", value); } }
    public byte wepmotionOneHandId { get { return this.GenericParam.GetValue<byte>("wepmotionOneHandId"); } set { this.GenericParam.SetValue("wepmotionOneHandId", value); } }
    public byte wepmotionBothHandId { get { return this.GenericParam.GetValue<byte>("wepmotionBothHandId"); } set { this.GenericParam.SetValue("wepmotionBothHandId", value); } }
    public byte properStrength { get { return this.GenericParam.GetValue<byte>("properStrength"); } set { this.GenericParam.SetValue("properStrength", value); } }
    public byte properAgility { get { return this.GenericParam.GetValue<byte>("properAgility"); } set { this.GenericParam.SetValue("properAgility", value); } }
    public byte properMagic { get { return this.GenericParam.GetValue<byte>("properMagic"); } set { this.GenericParam.SetValue("properMagic", value); } }
    public byte properFaith { get { return this.GenericParam.GetValue<byte>("properFaith"); } set { this.GenericParam.SetValue("properFaith", value); } }
    public byte overStrength { get { return this.GenericParam.GetValue<byte>("overStrength"); } set { this.GenericParam.SetValue("overStrength", value); } }
    public byte attackBaseParry { get { return this.GenericParam.GetValue<byte>("attackBaseParry"); } set { this.GenericParam.SetValue("attackBaseParry", value); } }
    public byte defenseBaseParry { get { return this.GenericParam.GetValue<byte>("defenseBaseParry"); } set { this.GenericParam.SetValue("defenseBaseParry", value); } }
    public byte guardBaseRepel { get { return this.GenericParam.GetValue<byte>("guardBaseRepel"); } set { this.GenericParam.SetValue("guardBaseRepel", value); } }
    public byte attackBaseRepel { get { return this.GenericParam.GetValue<byte>("attackBaseRepel"); } set { this.GenericParam.SetValue("attackBaseRepel", value); } }
    public sbyte guardCutCancelRate { get { return this.GenericParam.GetValue<sbyte>("guardCutCancelRate"); } set { this.GenericParam.SetValue("guardCutCancelRate", value); } }
    public sbyte guardLevel { get { return this.GenericParam.GetValue<sbyte>("guardLevel"); } set { this.GenericParam.SetValue("guardLevel", value); } }
    public sbyte slashGuardCutRate { get { return this.GenericParam.GetValue<sbyte>("slashGuardCutRate"); } set { this.GenericParam.SetValue("slashGuardCutRate", value); } }
    public sbyte blowGuardCutRate { get { return this.GenericParam.GetValue<sbyte>("blowGuardCutRate"); } set { this.GenericParam.SetValue("blowGuardCutRate", value); } }
    public sbyte thrustGuardCutRate { get { return this.GenericParam.GetValue<sbyte>("thrustGuardCutRate"); } set { this.GenericParam.SetValue("thrustGuardCutRate", value); } }
    public sbyte poisonGuardResist { get { return this.GenericParam.GetValue<sbyte>("poisonGuardResist"); } set { this.GenericParam.SetValue("poisonGuardResist", value); } }
    public sbyte diseaseGuardResist { get { return this.GenericParam.GetValue<sbyte>("diseaseGuardResist"); } set { this.GenericParam.SetValue("diseaseGuardResist", value); } }
    public sbyte bloodGuardResist { get { return this.GenericParam.GetValue<sbyte>("bloodGuardResist"); } set { this.GenericParam.SetValue("bloodGuardResist", value); } }
    public sbyte curseGuardResist { get { return this.GenericParam.GetValue<sbyte>("curseGuardResist"); } set { this.GenericParam.SetValue("curseGuardResist", value); } }
    public byte atkAttribute { get { return this.GenericParam.GetValue<byte>("atkAttribute"); } set { this.GenericParam.SetValue("atkAttribute", value); } }
    public byte rightHandEquipable { get { return this.GenericParam.GetValue<byte>("rightHandEquipable"); } set { this.GenericParam.SetValue("rightHandEquipable", value); } }
    public byte leftHandEquipable { get { return this.GenericParam.GetValue<byte>("leftHandEquipable"); } set { this.GenericParam.SetValue("leftHandEquipable", value); } }
    public byte bothHandEquipable { get { return this.GenericParam.GetValue<byte>("bothHandEquipable"); } set { this.GenericParam.SetValue("bothHandEquipable", value); } }
    public byte arrowSlotEquipable { get { return this.GenericParam.GetValue<byte>("arrowSlotEquipable"); } set { this.GenericParam.SetValue("arrowSlotEquipable", value); } }
    public byte boltSlotEquipable { get { return this.GenericParam.GetValue<byte>("boltSlotEquipable"); } set { this.GenericParam.SetValue("boltSlotEquipable", value); } }
    public byte enableGuard { get { return this.GenericParam.GetValue<byte>("enableGuard"); } set { this.GenericParam.SetValue("enableGuard", value); } }
    public byte enableParry { get { return this.GenericParam.GetValue<byte>("enableParry"); } set { this.GenericParam.SetValue("enableParry", value); } }
    public byte enableMagic { get { return this.GenericParam.GetValue<byte>("enableMagic"); } set { this.GenericParam.SetValue("enableMagic", value); } }
    public byte enableSorcery { get { return this.GenericParam.GetValue<byte>("enableSorcery"); } set { this.GenericParam.SetValue("enableSorcery", value); } }
    public byte enableMiracle { get { return this.GenericParam.GetValue<byte>("enableMiracle"); } set { this.GenericParam.SetValue("enableMiracle", value); } }
    public byte enableVowMagic { get { return this.GenericParam.GetValue<byte>("enableVowMagic"); } set { this.GenericParam.SetValue("enableVowMagic", value); } }
    public byte isNormalAttackType { get { return this.GenericParam.GetValue<byte>("isNormalAttackType"); } set { this.GenericParam.SetValue("isNormalAttackType", value); } }
    public byte isBlowAttackType { get { return this.GenericParam.GetValue<byte>("isBlowAttackType"); } set { this.GenericParam.SetValue("isBlowAttackType", value); } }
    public byte isSlashAttackType { get { return this.GenericParam.GetValue<byte>("isSlashAttackType"); } set { this.GenericParam.SetValue("isSlashAttackType", value); } }
    public byte isThrustAttackType { get { return this.GenericParam.GetValue<byte>("isThrustAttackType"); } set { this.GenericParam.SetValue("isThrustAttackType", value); } }
    public byte isEnhance { get { return this.GenericParam.GetValue<byte>("isEnhance"); } set { this.GenericParam.SetValue("isEnhance", value); } }
    public byte isHeroPointCorrect { get { return this.GenericParam.GetValue<byte>("isHeroPointCorrect"); } set { this.GenericParam.SetValue("isHeroPointCorrect", value); } }
    public byte isCustom { get { return this.GenericParam.GetValue<byte>("isCustom"); } set { this.GenericParam.SetValue("isCustom", value); } }
    public byte disableBaseChangeReset { get { return this.GenericParam.GetValue<byte>("disableBaseChangeReset"); } set { this.GenericParam.SetValue("disableBaseChangeReset", value); } }
    public byte disableRepair { get { return this.GenericParam.GetValue<byte>("disableRepair"); } set { this.GenericParam.SetValue("disableRepair", value); } }
    public byte isDarkHand { get { return this.GenericParam.GetValue<byte>("isDarkHand"); } set { this.GenericParam.SetValue("isDarkHand", value); } }
    public byte simpleModelForDlc { get { return this.GenericParam.GetValue<byte>("simpleModelForDlc"); } set { this.GenericParam.SetValue("simpleModelForDlc", value); } }
    public byte lanternWep { get { return this.GenericParam.GetValue<byte>("lanternWep"); } set { this.GenericParam.SetValue("lanternWep", value); } }
    public byte isVersusGhostWep { get { return this.GenericParam.GetValue<byte>("isVersusGhostWep"); } set { this.GenericParam.SetValue("isVersusGhostWep", value); } }
    public byte baseChangeCategory { get { return this.GenericParam.GetValue<byte>("baseChangeCategory"); } set { this.GenericParam.SetValue("baseChangeCategory", value); } }
    public byte isDragonSlayer { get { return this.GenericParam.GetValue<byte>("isDragonSlayer"); } set { this.GenericParam.SetValue("isDragonSlayer", value); } }
    public byte isDeposit { get { return this.GenericParam.GetValue<byte>("isDeposit"); } set { this.GenericParam.SetValue("isDeposit", value); } }
    public byte disableMultiDropShare { get { return this.GenericParam.GetValue<byte>("disableMultiDropShare"); } set { this.GenericParam.SetValue("disableMultiDropShare", value); } }
    public byte isDiscard { get { return this.GenericParam.GetValue<byte>("isDiscard"); } set { this.GenericParam.SetValue("isDiscard", value); } }
    public byte isDrop { get { return this.GenericParam.GetValue<byte>("isDrop"); } set { this.GenericParam.SetValue("isDrop", value); } }
    public byte showLogCondType { get { return this.GenericParam.GetValue<byte>("showLogCondType"); } set { this.GenericParam.SetValue("showLogCondType", value); } }
    public byte enableThrow { get { return this.GenericParam.GetValue<byte>("enableThrow"); } set { this.GenericParam.SetValue("enableThrow", value); } }
    public byte showDialogCondType { get { return this.GenericParam.GetValue<byte>("showDialogCondType"); } set { this.GenericParam.SetValue("showDialogCondType", value); } }
    public byte disableGemAttr { get { return this.GenericParam.GetValue<byte>("disableGemAttr"); } set { this.GenericParam.SetValue("disableGemAttr", value); } }
    public ushort defSfxMaterial1 { get { return this.GenericParam.GetValue<ushort>("defSfxMaterial1"); } set { this.GenericParam.SetValue("defSfxMaterial1", value); } }
    public byte wepCollidableType0 { get { return this.GenericParam.GetValue<byte>("wepCollidableType0"); } set { this.GenericParam.SetValue("wepCollidableType0", value); } }
    public byte wepCollidableType1 { get { return this.GenericParam.GetValue<byte>("wepCollidableType1"); } set { this.GenericParam.SetValue("wepCollidableType1", value); } }
    public byte postureControlId_Right { get { return this.GenericParam.GetValue<byte>("postureControlId_Right"); } set { this.GenericParam.SetValue("postureControlId_Right", value); } }
    public byte postureControlId_Left { get { return this.GenericParam.GetValue<byte>("postureControlId_Left"); } set { this.GenericParam.SetValue("postureControlId_Left", value); } }
    public int traceSfxId0 { get { return this.GenericParam.GetValue<int>("traceSfxId0"); } set { this.GenericParam.SetValue("traceSfxId0", value); } }
    public int traceDmyIdHead0 { get { return this.GenericParam.GetValue<int>("traceDmyIdHead0"); } set { this.GenericParam.SetValue("traceDmyIdHead0", value); } }
    public int traceDmyIdTail0 { get { return this.GenericParam.GetValue<int>("traceDmyIdTail0"); } set { this.GenericParam.SetValue("traceDmyIdTail0", value); } }
    public int traceSfxId1 { get { return this.GenericParam.GetValue<int>("traceSfxId1"); } set { this.GenericParam.SetValue("traceSfxId1", value); } }
    public int traceDmyIdHead1 { get { return this.GenericParam.GetValue<int>("traceDmyIdHead1"); } set { this.GenericParam.SetValue("traceDmyIdHead1", value); } }
    public int traceDmyIdTail1 { get { return this.GenericParam.GetValue<int>("traceDmyIdTail1"); } set { this.GenericParam.SetValue("traceDmyIdTail1", value); } }
    public int traceSfxId2 { get { return this.GenericParam.GetValue<int>("traceSfxId2"); } set { this.GenericParam.SetValue("traceSfxId2", value); } }
    public int traceDmyIdHead2 { get { return this.GenericParam.GetValue<int>("traceDmyIdHead2"); } set { this.GenericParam.SetValue("traceDmyIdHead2", value); } }
    public int traceDmyIdTail2 { get { return this.GenericParam.GetValue<int>("traceDmyIdTail2"); } set { this.GenericParam.SetValue("traceDmyIdTail2", value); } }
    public int traceSfxId3 { get { return this.GenericParam.GetValue<int>("traceSfxId3"); } set { this.GenericParam.SetValue("traceSfxId3", value); } }
    public int traceDmyIdHead3 { get { return this.GenericParam.GetValue<int>("traceDmyIdHead3"); } set { this.GenericParam.SetValue("traceDmyIdHead3", value); } }
    public int traceDmyIdTail3 { get { return this.GenericParam.GetValue<int>("traceDmyIdTail3"); } set { this.GenericParam.SetValue("traceDmyIdTail3", value); } }
    public int traceSfxId4 { get { return this.GenericParam.GetValue<int>("traceSfxId4"); } set { this.GenericParam.SetValue("traceSfxId4", value); } }
    public int traceDmyIdHead4 { get { return this.GenericParam.GetValue<int>("traceDmyIdHead4"); } set { this.GenericParam.SetValue("traceDmyIdHead4", value); } }
    public int traceDmyIdTail4 { get { return this.GenericParam.GetValue<int>("traceDmyIdTail4"); } set { this.GenericParam.SetValue("traceDmyIdTail4", value); } }
    public int traceSfxId5 { get { return this.GenericParam.GetValue<int>("traceSfxId5"); } set { this.GenericParam.SetValue("traceSfxId5", value); } }
    public int traceDmyIdHead5 { get { return this.GenericParam.GetValue<int>("traceDmyIdHead5"); } set { this.GenericParam.SetValue("traceDmyIdHead5", value); } }
    public int traceDmyIdTail5 { get { return this.GenericParam.GetValue<int>("traceDmyIdTail5"); } set { this.GenericParam.SetValue("traceDmyIdTail5", value); } }
    public int traceSfxId6 { get { return this.GenericParam.GetValue<int>("traceSfxId6"); } set { this.GenericParam.SetValue("traceSfxId6", value); } }
    public int traceDmyIdHead6 { get { return this.GenericParam.GetValue<int>("traceDmyIdHead6"); } set { this.GenericParam.SetValue("traceDmyIdHead6", value); } }
    public int traceDmyIdTail6 { get { return this.GenericParam.GetValue<int>("traceDmyIdTail6"); } set { this.GenericParam.SetValue("traceDmyIdTail6", value); } }
    public int traceSfxId7 { get { return this.GenericParam.GetValue<int>("traceSfxId7"); } set { this.GenericParam.SetValue("traceSfxId7", value); } }
    public int traceDmyIdHead7 { get { return this.GenericParam.GetValue<int>("traceDmyIdHead7"); } set { this.GenericParam.SetValue("traceDmyIdHead7", value); } }
    public int traceDmyIdTail7 { get { return this.GenericParam.GetValue<int>("traceDmyIdTail7"); } set { this.GenericParam.SetValue("traceDmyIdTail7", value); } }
    public ushort defSfxMaterial2 { get { return this.GenericParam.GetValue<ushort>("defSfxMaterial2"); } set { this.GenericParam.SetValue("defSfxMaterial2", value); } }
    public ushort defSeMaterial2 { get { return this.GenericParam.GetValue<ushort>("defSeMaterial2"); } set { this.GenericParam.SetValue("defSeMaterial2", value); } }
    public int absorpParamId { get { return this.GenericParam.GetValue<int>("absorpParamId"); } set { this.GenericParam.SetValue("absorpParamId", value); } }
    public float toughnessCorrectRate { get { return this.GenericParam.GetValue<float>("toughnessCorrectRate"); } set { this.GenericParam.SetValue("toughnessCorrectRate", value); } }
    public byte isValidTough_ProtSADmg { get { return this.GenericParam.GetValue<byte>("isValidTough_ProtSADmg"); } set { this.GenericParam.SetValue("isValidTough_ProtSADmg", value); } }
    public byte isDualBlade { get { return this.GenericParam.GetValue<byte>("isDualBlade"); } set { this.GenericParam.SetValue("isDualBlade", value); } }
    public byte isAutoEquip { get { return this.GenericParam.GetValue<byte>("isAutoEquip"); } set { this.GenericParam.SetValue("isAutoEquip", value); } }
    public byte isEnableEmergencyStep { get { return this.GenericParam.GetValue<byte>("isEnableEmergencyStep"); } set { this.GenericParam.SetValue("isEnableEmergencyStep", value); } }
    public byte invisibleOnRemo { get { return this.GenericParam.GetValue<byte>("invisibleOnRemo"); } set { this.GenericParam.SetValue("invisibleOnRemo", value); } }
    public byte unknown_0x17c_5 { get { return this.GenericParam.GetValue<byte>("unknown_0x17c_5"); } set { this.GenericParam.SetValue("unknown_0x17c_5", value); } }
    public byte isArrow { get { return this.GenericParam.GetValue<byte>("isArrow"); } set { this.GenericParam.SetValue("isArrow", value); } }
    public byte isWeaponCatalyst { get { return this.GenericParam.GetValue<byte>("isWeaponCatalyst"); } set { this.GenericParam.SetValue("isWeaponCatalyst", value); } }
    public byte correctType_Magic { get { return this.GenericParam.GetValue<byte>("correctType_Magic"); } set { this.GenericParam.SetValue("correctType_Magic", value); } }
    public byte correctType_Fire { get { return this.GenericParam.GetValue<byte>("correctType_Fire"); } set { this.GenericParam.SetValue("correctType_Fire", value); } }
    public byte correctType_Thunder { get { return this.GenericParam.GetValue<byte>("correctType_Thunder"); } set { this.GenericParam.SetValue("correctType_Thunder", value); } }
    public float weakE_DamageRate { get { return this.GenericParam.GetValue<float>("weakE_DamageRate"); } set { this.GenericParam.SetValue("weakE_DamageRate", value); } }
    public float weakF_DamageRate { get { return this.GenericParam.GetValue<float>("weakF_DamageRate"); } set { this.GenericParam.SetValue("weakF_DamageRate", value); } }
    public float darkGuardCutRate { get { return this.GenericParam.GetValue<float>("darkGuardCutRate"); } set { this.GenericParam.SetValue("darkGuardCutRate", value); } }
    public ushort attackBaseDark { get { return this.GenericParam.GetValue<ushort>("attackBaseDark"); } set { this.GenericParam.SetValue("attackBaseDark", value); } }
    public byte correctType_Dark { get { return this.GenericParam.GetValue<byte>("correctType_Dark"); } set { this.GenericParam.SetValue("correctType_Dark", value); } }
    public byte correctType_Poison { get { return this.GenericParam.GetValue<byte>("correctType_Poison"); } set { this.GenericParam.SetValue("correctType_Poison", value); } }
    public byte sortGroupId { get { return this.GenericParam.GetValue<byte>("sortGroupId"); } set { this.GenericParam.SetValue("sortGroupId", value); } }
    public byte atkAttribute2 { get { return this.GenericParam.GetValue<byte>("atkAttribute2"); } set { this.GenericParam.SetValue("atkAttribute2", value); } }
    public sbyte sleepGuardResist { get { return this.GenericParam.GetValue<sbyte>("sleepGuardResist"); } set { this.GenericParam.SetValue("sleepGuardResist", value); } }
    public sbyte madnessGuardResist { get { return this.GenericParam.GetValue<sbyte>("madnessGuardResist"); } set { this.GenericParam.SetValue("madnessGuardResist", value); } }
    public byte correctType_Blood { get { return this.GenericParam.GetValue<byte>("correctType_Blood"); } set { this.GenericParam.SetValue("correctType_Blood", value); } }
    public byte properLuck { get { return this.GenericParam.GetValue<byte>("properLuck"); } set { this.GenericParam.SetValue("properLuck", value); } }
    public sbyte freezeGuardResist { get { return this.GenericParam.GetValue<sbyte>("freezeGuardResist"); } set { this.GenericParam.SetValue("freezeGuardResist", value); } }
    public byte autoReplenishType { get { return this.GenericParam.GetValue<byte>("autoReplenishType"); } set { this.GenericParam.SetValue("autoReplenishType", value); } }
    public int swordArtsParamId { get { return this.GenericParam.GetValue<int>("swordArtsParamId"); } set { this.GenericParam.SetValue("swordArtsParamId", value); } }
    public float correctLuck { get { return this.GenericParam.GetValue<float>("correctLuck"); } set { this.GenericParam.SetValue("correctLuck", value); } }
    public uint arrowBoltEquipId { get { return this.GenericParam.GetValue<uint>("arrowBoltEquipId"); } set { this.GenericParam.SetValue("arrowBoltEquipId", value); } }
    public byte DerivationLevelType { get { return this.GenericParam.GetValue<byte>("DerivationLevelType"); } set { this.GenericParam.SetValue("DerivationLevelType", value); } }
    public byte enchantSfxSize { get { return this.GenericParam.GetValue<byte>("enchantSfxSize"); } set { this.GenericParam.SetValue("enchantSfxSize", value); } }
    public ushort wepType { get { return this.GenericParam.GetValue<ushort>("wepType"); } set { this.GenericParam.SetValue("wepType", value); } }
    public float physGuardCutRate_MaxCorrect { get { return this.GenericParam.GetValue<float>("physGuardCutRate_MaxCorrect"); } set { this.GenericParam.SetValue("physGuardCutRate_MaxCorrect", value); } }
    public float magGuardCutRate_MaxCorrect { get { return this.GenericParam.GetValue<float>("magGuardCutRate_MaxCorrect"); } set { this.GenericParam.SetValue("magGuardCutRate_MaxCorrect", value); } }
    public float fireGuardCutRate_MaxCorrect { get { return this.GenericParam.GetValue<float>("fireGuardCutRate_MaxCorrect"); } set { this.GenericParam.SetValue("fireGuardCutRate_MaxCorrect", value); } }
    public float thunGuardCutRate_MaxCorrect { get { return this.GenericParam.GetValue<float>("thunGuardCutRate_MaxCorrect"); } set { this.GenericParam.SetValue("thunGuardCutRate_MaxCorrect", value); } }
    public float darkGuardCutRate_MaxCorrect { get { return this.GenericParam.GetValue<float>("darkGuardCutRate_MaxCorrect"); } set { this.GenericParam.SetValue("darkGuardCutRate_MaxCorrect", value); } }
    public float poisonGuardResist_MaxCorrect { get { return this.GenericParam.GetValue<float>("poisonGuardResist_MaxCorrect"); } set { this.GenericParam.SetValue("poisonGuardResist_MaxCorrect", value); } }
    public float diseaseGuardResist_MaxCorrect { get { return this.GenericParam.GetValue<float>("diseaseGuardResist_MaxCorrect"); } set { this.GenericParam.SetValue("diseaseGuardResist_MaxCorrect", value); } }
    public float bloodGuardResist_MaxCorrect { get { return this.GenericParam.GetValue<float>("bloodGuardResist_MaxCorrect"); } set { this.GenericParam.SetValue("bloodGuardResist_MaxCorrect", value); } }
    public float curseGuardResist_MaxCorrect { get { return this.GenericParam.GetValue<float>("curseGuardResist_MaxCorrect"); } set { this.GenericParam.SetValue("curseGuardResist_MaxCorrect", value); } }
    public float freezeGuardResist_MaxCorrect { get { return this.GenericParam.GetValue<float>("freezeGuardResist_MaxCorrect"); } set { this.GenericParam.SetValue("freezeGuardResist_MaxCorrect", value); } }
    public float staminaGuardDef_MaxCorrect { get { return this.GenericParam.GetValue<float>("staminaGuardDef_MaxCorrect"); } set { this.GenericParam.SetValue("staminaGuardDef_MaxCorrect", value); } }
    public int residentSfxId_1 { get { return this.GenericParam.GetValue<int>("residentSfxId_1"); } set { this.GenericParam.SetValue("residentSfxId_1", value); } }
    public int residentSfxId_2 { get { return this.GenericParam.GetValue<int>("residentSfxId_2"); } set { this.GenericParam.SetValue("residentSfxId_2", value); } }
    public int residentSfxId_3 { get { return this.GenericParam.GetValue<int>("residentSfxId_3"); } set { this.GenericParam.SetValue("residentSfxId_3", value); } }
    public int residentSfxId_4 { get { return this.GenericParam.GetValue<int>("residentSfxId_4"); } set { this.GenericParam.SetValue("residentSfxId_4", value); } }
    public int residentSfx_DmyId_1 { get { return this.GenericParam.GetValue<int>("residentSfx_DmyId_1"); } set { this.GenericParam.SetValue("residentSfx_DmyId_1", value); } }
    public int residentSfx_DmyId_2 { get { return this.GenericParam.GetValue<int>("residentSfx_DmyId_2"); } set { this.GenericParam.SetValue("residentSfx_DmyId_2", value); } }
    public int residentSfx_DmyId_3 { get { return this.GenericParam.GetValue<int>("residentSfx_DmyId_3"); } set { this.GenericParam.SetValue("residentSfx_DmyId_3", value); } }
    public int residentSfx_DmyId_4 { get { return this.GenericParam.GetValue<int>("residentSfx_DmyId_4"); } set { this.GenericParam.SetValue("residentSfx_DmyId_4", value); } }
    public float staminaConsumptionRate { get { return this.GenericParam.GetValue<float>("staminaConsumptionRate"); } set { this.GenericParam.SetValue("staminaConsumptionRate", value); } }
    public float vsPlayerDmgCorrectRate_Physics { get { return this.GenericParam.GetValue<float>("vsPlayerDmgCorrectRate_Physics"); } set { this.GenericParam.SetValue("vsPlayerDmgCorrectRate_Physics", value); } }
    public float vsPlayerDmgCorrectRate_Magic { get { return this.GenericParam.GetValue<float>("vsPlayerDmgCorrectRate_Magic"); } set { this.GenericParam.SetValue("vsPlayerDmgCorrectRate_Magic", value); } }
    public float vsPlayerDmgCorrectRate_Fire { get { return this.GenericParam.GetValue<float>("vsPlayerDmgCorrectRate_Fire"); } set { this.GenericParam.SetValue("vsPlayerDmgCorrectRate_Fire", value); } }
    public float vsPlayerDmgCorrectRate_Thunder { get { return this.GenericParam.GetValue<float>("vsPlayerDmgCorrectRate_Thunder"); } set { this.GenericParam.SetValue("vsPlayerDmgCorrectRate_Thunder", value); } }
    public float vsPlayerDmgCorrectRate_Dark { get { return this.GenericParam.GetValue<float>("vsPlayerDmgCorrectRate_Dark"); } set { this.GenericParam.SetValue("vsPlayerDmgCorrectRate_Dark", value); } }
    public float vsPlayerDmgCorrectRate_Poison { get { return this.GenericParam.GetValue<float>("vsPlayerDmgCorrectRate_Poison"); } set { this.GenericParam.SetValue("vsPlayerDmgCorrectRate_Poison", value); } }
    public float vsPlayerDmgCorrectRate_Blood { get { return this.GenericParam.GetValue<float>("vsPlayerDmgCorrectRate_Blood"); } set { this.GenericParam.SetValue("vsPlayerDmgCorrectRate_Blood", value); } }
    public float vsPlayerDmgCorrectRate_Freeze { get { return this.GenericParam.GetValue<float>("vsPlayerDmgCorrectRate_Freeze"); } set { this.GenericParam.SetValue("vsPlayerDmgCorrectRate_Freeze", value); } }
    public int attainmentWepStatusStr { get { return this.GenericParam.GetValue<int>("attainmentWepStatusStr"); } set { this.GenericParam.SetValue("attainmentWepStatusStr", value); } }
    public int attainmentWepStatusDex { get { return this.GenericParam.GetValue<int>("attainmentWepStatusDex"); } set { this.GenericParam.SetValue("attainmentWepStatusDex", value); } }
    public int attainmentWepStatusMag { get { return this.GenericParam.GetValue<int>("attainmentWepStatusMag"); } set { this.GenericParam.SetValue("attainmentWepStatusMag", value); } }
    public int attainmentWepStatusFai { get { return this.GenericParam.GetValue<int>("attainmentWepStatusFai"); } set { this.GenericParam.SetValue("attainmentWepStatusFai", value); } }
    public int attainmentWepStatusLuc { get { return this.GenericParam.GetValue<int>("attainmentWepStatusLuc"); } set { this.GenericParam.SetValue("attainmentWepStatusLuc", value); } }
    public int attackElementCorrectId { get { return this.GenericParam.GetValue<int>("attackElementCorrectId"); } set { this.GenericParam.SetValue("attackElementCorrectId", value); } }
    public int saleValue { get { return this.GenericParam.GetValue<int>("saleValue"); } set { this.GenericParam.SetValue("saleValue", value); } }
    public byte reinforceShopCategory { get { return this.GenericParam.GetValue<byte>("reinforceShopCategory"); } set { this.GenericParam.SetValue("reinforceShopCategory", value); } }
    public byte maxArrowQuantity { get { return this.GenericParam.GetValue<byte>("maxArrowQuantity"); } set { this.GenericParam.SetValue("maxArrowQuantity", value); } }
    public byte residentSfx_1_IsVisibleForHang { get { return this.GenericParam.GetValue<byte>("residentSfx_1_IsVisibleForHang"); } set { this.GenericParam.SetValue("residentSfx_1_IsVisibleForHang", value); } }
    public byte residentSfx_2_IsVisibleForHang { get { return this.GenericParam.GetValue<byte>("residentSfx_2_IsVisibleForHang"); } set { this.GenericParam.SetValue("residentSfx_2_IsVisibleForHang", value); } }
    public byte residentSfx_3_IsVisibleForHang { get { return this.GenericParam.GetValue<byte>("residentSfx_3_IsVisibleForHang"); } set { this.GenericParam.SetValue("residentSfx_3_IsVisibleForHang", value); } }
    public byte residentSfx_4_IsVisibleForHang { get { return this.GenericParam.GetValue<byte>("residentSfx_4_IsVisibleForHang"); } set { this.GenericParam.SetValue("residentSfx_4_IsVisibleForHang", value); } }
    public byte isSoulParamIdChange_model0 { get { return this.GenericParam.GetValue<byte>("isSoulParamIdChange_model0"); } set { this.GenericParam.SetValue("isSoulParamIdChange_model0", value); } }
    public byte isSoulParamIdChange_model1 { get { return this.GenericParam.GetValue<byte>("isSoulParamIdChange_model1"); } set { this.GenericParam.SetValue("isSoulParamIdChange_model1", value); } }
    public byte isSoulParamIdChange_model2 { get { return this.GenericParam.GetValue<byte>("isSoulParamIdChange_model2"); } set { this.GenericParam.SetValue("isSoulParamIdChange_model2", value); } }
    public byte isSoulParamIdChange_model3 { get { return this.GenericParam.GetValue<byte>("isSoulParamIdChange_model3"); } set { this.GenericParam.SetValue("isSoulParamIdChange_model3", value); } }
    public sbyte wepSeIdOffset { get { return this.GenericParam.GetValue<sbyte>("wepSeIdOffset"); } set { this.GenericParam.SetValue("wepSeIdOffset", value); } }
    public int baseChangePrice { get { return this.GenericParam.GetValue<int>("baseChangePrice"); } set { this.GenericParam.SetValue("baseChangePrice", value); } }
    public short levelSyncCorrectId { get { return this.GenericParam.GetValue<short>("levelSyncCorrectId"); } set { this.GenericParam.SetValue("levelSyncCorrectId", value); } }
    public byte correctType_Sleep { get { return this.GenericParam.GetValue<byte>("correctType_Sleep"); } set { this.GenericParam.SetValue("correctType_Sleep", value); } }
    public byte correctType_Madness { get { return this.GenericParam.GetValue<byte>("correctType_Madness"); } set { this.GenericParam.SetValue("correctType_Madness", value); } }
    public byte rarity { get { return this.GenericParam.GetValue<byte>("rarity"); } set { this.GenericParam.SetValue("rarity", value); } }
    public byte gemMountType { get { return this.GenericParam.GetValue<byte>("gemMountType"); } set { this.GenericParam.SetValue("gemMountType", value); } }
    public ushort wepRegainHp { get { return this.GenericParam.GetValue<ushort>("wepRegainHp"); } set { this.GenericParam.SetValue("wepRegainHp", value); } }
    public int spEffectMsgId0 { get { return this.GenericParam.GetValue<int>("spEffectMsgId0"); } set { this.GenericParam.SetValue("spEffectMsgId0", value); } }
    public int spEffectMsgId1 { get { return this.GenericParam.GetValue<int>("spEffectMsgId1"); } set { this.GenericParam.SetValue("spEffectMsgId1", value); } }
    public int spEffectMsgId2 { get { return this.GenericParam.GetValue<int>("spEffectMsgId2"); } set { this.GenericParam.SetValue("spEffectMsgId2", value); } }
    public int originEquipWep16 { get { return this.GenericParam.GetValue<int>("originEquipWep16"); } set { this.GenericParam.SetValue("originEquipWep16", value); } }
    public int originEquipWep17 { get { return this.GenericParam.GetValue<int>("originEquipWep17"); } set { this.GenericParam.SetValue("originEquipWep17", value); } }
    public int originEquipWep18 { get { return this.GenericParam.GetValue<int>("originEquipWep18"); } set { this.GenericParam.SetValue("originEquipWep18", value); } }
    public int originEquipWep19 { get { return this.GenericParam.GetValue<int>("originEquipWep19"); } set { this.GenericParam.SetValue("originEquipWep19", value); } }
    public int originEquipWep20 { get { return this.GenericParam.GetValue<int>("originEquipWep20"); } set { this.GenericParam.SetValue("originEquipWep20", value); } }
    public int originEquipWep21 { get { return this.GenericParam.GetValue<int>("originEquipWep21"); } set { this.GenericParam.SetValue("originEquipWep21", value); } }
    public int originEquipWep22 { get { return this.GenericParam.GetValue<int>("originEquipWep22"); } set { this.GenericParam.SetValue("originEquipWep22", value); } }
    public int originEquipWep23 { get { return this.GenericParam.GetValue<int>("originEquipWep23"); } set { this.GenericParam.SetValue("originEquipWep23", value); } }
    public int originEquipWep24 { get { return this.GenericParam.GetValue<int>("originEquipWep24"); } set { this.GenericParam.SetValue("originEquipWep24", value); } }
    public int originEquipWep25 { get { return this.GenericParam.GetValue<int>("originEquipWep25"); } set { this.GenericParam.SetValue("originEquipWep25", value); } }
    public float vsPlayerDmgCorrectRate_Sleep { get { return this.GenericParam.GetValue<float>("vsPlayerDmgCorrectRate_Sleep"); } set { this.GenericParam.SetValue("vsPlayerDmgCorrectRate_Sleep", value); } }
    public float vsPlayerDmgCorrectRate_Madness { get { return this.GenericParam.GetValue<float>("vsPlayerDmgCorrectRate_Madness"); } set { this.GenericParam.SetValue("vsPlayerDmgCorrectRate_Madness", value); } }
    public float saGuardCutRate { get { return this.GenericParam.GetValue<float>("saGuardCutRate"); } set { this.GenericParam.SetValue("saGuardCutRate", value); } }
    public byte defMaterialVariationValue { get { return this.GenericParam.GetValue<byte>("defMaterialVariationValue"); } set { this.GenericParam.SetValue("defMaterialVariationValue", value); } }
    public byte spAttributeVariationValue { get { return this.GenericParam.GetValue<byte>("spAttributeVariationValue"); } set { this.GenericParam.SetValue("spAttributeVariationValue", value); } }
    public short stealthAtkRate { get { return this.GenericParam.GetValue<short>("stealthAtkRate"); } set { this.GenericParam.SetValue("stealthAtkRate", value); } }
    public float vsPlayerDmgCorrectRate_Disease { get { return this.GenericParam.GetValue<float>("vsPlayerDmgCorrectRate_Disease"); } set { this.GenericParam.SetValue("vsPlayerDmgCorrectRate_Disease", value); } }
    public float vsPlayerDmgCorrectRate_Curse { get { return this.GenericParam.GetValue<float>("vsPlayerDmgCorrectRate_Curse"); } set { this.GenericParam.SetValue("vsPlayerDmgCorrectRate_Curse", value); } }
    public byte restrictSpecialSwordArt { get { return this.GenericParam.GetValue<byte>("restrictSpecialSwordArt"); } set { this.GenericParam.SetValue("restrictSpecialSwordArt", value); } }
    public byte[] pad { get { return this.GenericParam.GetValue<byte[]>("pad"); } set { this.GenericParam.SetValue("pad", value); } }
}
