using System;

public class EquipParamProtector : ParamBase<EquipParamProtector>
{
    public int ID { get { return this.GenericParam.GetValue<int>("ID"); } set { this.GenericParam.SetValue("ID", value); } }
    public string Name { get { return this.GenericParam.GetValue<string>("Name"); } set { this.GenericParam.SetValue("Name", value); } }
    public byte disableParam_NT { get { return this.GenericParam.GetValue<byte>("disableParam_NT"); } set { this.GenericParam.SetValue("disableParam_NT", value); } }
    public byte disableParamReserve1 { get { return this.GenericParam.GetValue<byte>("disableParamReserve1"); } set { this.GenericParam.SetValue("disableParamReserve1", value); } }
    public byte[] disableParamReserve2 { get { return this.GenericParam.GetValue<byte[]>("disableParamReserve2"); } set { this.GenericParam.SetValue("disableParamReserve2", value); } }
    public int sortId { get { return this.GenericParam.GetValue<int>("sortId"); } set { this.GenericParam.SetValue("sortId", value); } }
    public uint wanderingEquipId { get { return this.GenericParam.GetValue<uint>("wanderingEquipId"); } set { this.GenericParam.SetValue("wanderingEquipId", value); } }
    public ushort resistSleep { get { return this.GenericParam.GetValue<ushort>("resistSleep"); } set { this.GenericParam.SetValue("resistSleep", value); } }
    public ushort resistMadness { get { return this.GenericParam.GetValue<ushort>("resistMadness"); } set { this.GenericParam.SetValue("resistMadness", value); } }
    public float saDurability { get { return this.GenericParam.GetValue<float>("saDurability"); } set { this.GenericParam.SetValue("saDurability", value); } }
    public float toughnessCorrectRate { get { return this.GenericParam.GetValue<float>("toughnessCorrectRate"); } set { this.GenericParam.SetValue("toughnessCorrectRate", value); } }
    public int fixPrice { get { return this.GenericParam.GetValue<int>("fixPrice"); } set { this.GenericParam.SetValue("fixPrice", value); } }
    public int basicPrice { get { return this.GenericParam.GetValue<int>("basicPrice"); } set { this.GenericParam.SetValue("basicPrice", value); } }
    public int sellValue { get { return this.GenericParam.GetValue<int>("sellValue"); } set { this.GenericParam.SetValue("sellValue", value); } }
    public float weight { get { return this.GenericParam.GetValue<float>("weight"); } set { this.GenericParam.SetValue("weight", value); } }
    public int residentSpEffectId { get { return this.GenericParam.GetValue<int>("residentSpEffectId"); } set { this.GenericParam.SetValue("residentSpEffectId", value); } }
    public int residentSpEffectId2 { get { return this.GenericParam.GetValue<int>("residentSpEffectId2"); } set { this.GenericParam.SetValue("residentSpEffectId2", value); } }
    public int residentSpEffectId3 { get { return this.GenericParam.GetValue<int>("residentSpEffectId3"); } set { this.GenericParam.SetValue("residentSpEffectId3", value); } }
    public int materialSetId { get { return this.GenericParam.GetValue<int>("materialSetId"); } set { this.GenericParam.SetValue("materialSetId", value); } }
    public float partsDamageRate { get { return this.GenericParam.GetValue<float>("partsDamageRate"); } set { this.GenericParam.SetValue("partsDamageRate", value); } }
    public float corectSARecover { get { return this.GenericParam.GetValue<float>("corectSARecover"); } set { this.GenericParam.SetValue("corectSARecover", value); } }
    public int originEquipPro { get { return this.GenericParam.GetValue<int>("originEquipPro"); } set { this.GenericParam.SetValue("originEquipPro", value); } }
    public int originEquipPro1 { get { return this.GenericParam.GetValue<int>("originEquipPro1"); } set { this.GenericParam.SetValue("originEquipPro1", value); } }
    public int originEquipPro2 { get { return this.GenericParam.GetValue<int>("originEquipPro2"); } set { this.GenericParam.SetValue("originEquipPro2", value); } }
    public int originEquipPro3 { get { return this.GenericParam.GetValue<int>("originEquipPro3"); } set { this.GenericParam.SetValue("originEquipPro3", value); } }
    public int originEquipPro4 { get { return this.GenericParam.GetValue<int>("originEquipPro4"); } set { this.GenericParam.SetValue("originEquipPro4", value); } }
    public int originEquipPro5 { get { return this.GenericParam.GetValue<int>("originEquipPro5"); } set { this.GenericParam.SetValue("originEquipPro5", value); } }
    public int originEquipPro6 { get { return this.GenericParam.GetValue<int>("originEquipPro6"); } set { this.GenericParam.SetValue("originEquipPro6", value); } }
    public int originEquipPro7 { get { return this.GenericParam.GetValue<int>("originEquipPro7"); } set { this.GenericParam.SetValue("originEquipPro7", value); } }
    public int originEquipPro8 { get { return this.GenericParam.GetValue<int>("originEquipPro8"); } set { this.GenericParam.SetValue("originEquipPro8", value); } }
    public int originEquipPro9 { get { return this.GenericParam.GetValue<int>("originEquipPro9"); } set { this.GenericParam.SetValue("originEquipPro9", value); } }
    public int originEquipPro10 { get { return this.GenericParam.GetValue<int>("originEquipPro10"); } set { this.GenericParam.SetValue("originEquipPro10", value); } }
    public int originEquipPro11 { get { return this.GenericParam.GetValue<int>("originEquipPro11"); } set { this.GenericParam.SetValue("originEquipPro11", value); } }
    public int originEquipPro12 { get { return this.GenericParam.GetValue<int>("originEquipPro12"); } set { this.GenericParam.SetValue("originEquipPro12", value); } }
    public int originEquipPro13 { get { return this.GenericParam.GetValue<int>("originEquipPro13"); } set { this.GenericParam.SetValue("originEquipPro13", value); } }
    public int originEquipPro14 { get { return this.GenericParam.GetValue<int>("originEquipPro14"); } set { this.GenericParam.SetValue("originEquipPro14", value); } }
    public int originEquipPro15 { get { return this.GenericParam.GetValue<int>("originEquipPro15"); } set { this.GenericParam.SetValue("originEquipPro15", value); } }
    public float faceScaleM_ScaleX { get { return this.GenericParam.GetValue<float>("faceScaleM_ScaleX"); } set { this.GenericParam.SetValue("faceScaleM_ScaleX", value); } }
    public float faceScaleM_ScaleZ { get { return this.GenericParam.GetValue<float>("faceScaleM_ScaleZ"); } set { this.GenericParam.SetValue("faceScaleM_ScaleZ", value); } }
    public float faceScaleM_MaxX { get { return this.GenericParam.GetValue<float>("faceScaleM_MaxX"); } set { this.GenericParam.SetValue("faceScaleM_MaxX", value); } }
    public float faceScaleM_MaxZ { get { return this.GenericParam.GetValue<float>("faceScaleM_MaxZ"); } set { this.GenericParam.SetValue("faceScaleM_MaxZ", value); } }
    public float faceScaleF_ScaleX { get { return this.GenericParam.GetValue<float>("faceScaleF_ScaleX"); } set { this.GenericParam.SetValue("faceScaleF_ScaleX", value); } }
    public float faceScaleF_ScaleZ { get { return this.GenericParam.GetValue<float>("faceScaleF_ScaleZ"); } set { this.GenericParam.SetValue("faceScaleF_ScaleZ", value); } }
    public float faceScaleF_MaxX { get { return this.GenericParam.GetValue<float>("faceScaleF_MaxX"); } set { this.GenericParam.SetValue("faceScaleF_MaxX", value); } }
    public float faceScaleF_MaxZ { get { return this.GenericParam.GetValue<float>("faceScaleF_MaxZ"); } set { this.GenericParam.SetValue("faceScaleF_MaxZ", value); } }
    public int qwcId { get { return this.GenericParam.GetValue<int>("qwcId"); } set { this.GenericParam.SetValue("qwcId", value); } }
    public ushort equipModelId { get { return this.GenericParam.GetValue<ushort>("equipModelId"); } set { this.GenericParam.SetValue("equipModelId", value); } }
    public ushort iconIdM { get { return this.GenericParam.GetValue<ushort>("iconIdM"); } set { this.GenericParam.SetValue("iconIdM", value); } }
    public ushort iconIdF { get { return this.GenericParam.GetValue<ushort>("iconIdF"); } set { this.GenericParam.SetValue("iconIdF", value); } }
    public ushort knockBack { get { return this.GenericParam.GetValue<ushort>("knockBack"); } set { this.GenericParam.SetValue("knockBack", value); } }
    public ushort knockbackBounceRate { get { return this.GenericParam.GetValue<ushort>("knockbackBounceRate"); } set { this.GenericParam.SetValue("knockbackBounceRate", value); } }
    public ushort durability { get { return this.GenericParam.GetValue<ushort>("durability"); } set { this.GenericParam.SetValue("durability", value); } }
    public ushort durabilityMax { get { return this.GenericParam.GetValue<ushort>("durabilityMax"); } set { this.GenericParam.SetValue("durabilityMax", value); } }
    public byte[] pad03 { get { return this.GenericParam.GetValue<byte[]>("pad03"); } set { this.GenericParam.SetValue("pad03", value); } }
    public ushort defFlickPower { get { return this.GenericParam.GetValue<ushort>("defFlickPower"); } set { this.GenericParam.SetValue("defFlickPower", value); } }
    public ushort defensePhysics { get { return this.GenericParam.GetValue<ushort>("defensePhysics"); } set { this.GenericParam.SetValue("defensePhysics", value); } }
    public ushort defenseMagic { get { return this.GenericParam.GetValue<ushort>("defenseMagic"); } set { this.GenericParam.SetValue("defenseMagic", value); } }
    public ushort defenseFire { get { return this.GenericParam.GetValue<ushort>("defenseFire"); } set { this.GenericParam.SetValue("defenseFire", value); } }
    public ushort defenseThunder { get { return this.GenericParam.GetValue<ushort>("defenseThunder"); } set { this.GenericParam.SetValue("defenseThunder", value); } }
    public short defenseSlash { get { return this.GenericParam.GetValue<short>("defenseSlash"); } set { this.GenericParam.SetValue("defenseSlash", value); } }
    public short defenseBlow { get { return this.GenericParam.GetValue<short>("defenseBlow"); } set { this.GenericParam.SetValue("defenseBlow", value); } }
    public short defenseThrust { get { return this.GenericParam.GetValue<short>("defenseThrust"); } set { this.GenericParam.SetValue("defenseThrust", value); } }
    public ushort resistPoison { get { return this.GenericParam.GetValue<ushort>("resistPoison"); } set { this.GenericParam.SetValue("resistPoison", value); } }
    public ushort resistDisease { get { return this.GenericParam.GetValue<ushort>("resistDisease"); } set { this.GenericParam.SetValue("resistDisease", value); } }
    public ushort resistBlood { get { return this.GenericParam.GetValue<ushort>("resistBlood"); } set { this.GenericParam.SetValue("resistBlood", value); } }
    public ushort resistCurse { get { return this.GenericParam.GetValue<ushort>("resistCurse"); } set { this.GenericParam.SetValue("resistCurse", value); } }
    public short reinforceTypeId { get { return this.GenericParam.GetValue<short>("reinforceTypeId"); } set { this.GenericParam.SetValue("reinforceTypeId", value); } }
    public short trophySGradeId { get { return this.GenericParam.GetValue<short>("trophySGradeId"); } set { this.GenericParam.SetValue("trophySGradeId", value); } }
    public short shopLv { get { return this.GenericParam.GetValue<short>("shopLv"); } set { this.GenericParam.SetValue("shopLv", value); } }
    public byte knockbackParamId { get { return this.GenericParam.GetValue<byte>("knockbackParamId"); } set { this.GenericParam.SetValue("knockbackParamId", value); } }
    public byte flickDamageCutRate { get { return this.GenericParam.GetValue<byte>("flickDamageCutRate"); } set { this.GenericParam.SetValue("flickDamageCutRate", value); } }
    public byte equipModelCategory { get { return this.GenericParam.GetValue<byte>("equipModelCategory"); } set { this.GenericParam.SetValue("equipModelCategory", value); } }
    public byte equipModelGender { get { return this.GenericParam.GetValue<byte>("equipModelGender"); } set { this.GenericParam.SetValue("equipModelGender", value); } }
    public byte protectorCategory { get { return this.GenericParam.GetValue<byte>("protectorCategory"); } set { this.GenericParam.SetValue("protectorCategory", value); } }
    public byte rarity { get { return this.GenericParam.GetValue<byte>("rarity"); } set { this.GenericParam.SetValue("rarity", value); } }
    public byte sortGroupId { get { return this.GenericParam.GetValue<byte>("sortGroupId"); } set { this.GenericParam.SetValue("sortGroupId", value); } }
    public byte partsDmgType { get { return this.GenericParam.GetValue<byte>("partsDmgType"); } set { this.GenericParam.SetValue("partsDmgType", value); } }
    public byte[] pad04 { get { return this.GenericParam.GetValue<byte[]>("pad04"); } set { this.GenericParam.SetValue("pad04", value); } }
    public byte isDeposit { get { return this.GenericParam.GetValue<byte>("isDeposit"); } set { this.GenericParam.SetValue("isDeposit", value); } }
    public byte headEquip { get { return this.GenericParam.GetValue<byte>("headEquip"); } set { this.GenericParam.SetValue("headEquip", value); } }
    public byte bodyEquip { get { return this.GenericParam.GetValue<byte>("bodyEquip"); } set { this.GenericParam.SetValue("bodyEquip", value); } }
    public byte armEquip { get { return this.GenericParam.GetValue<byte>("armEquip"); } set { this.GenericParam.SetValue("armEquip", value); } }
    public byte legEquip { get { return this.GenericParam.GetValue<byte>("legEquip"); } set { this.GenericParam.SetValue("legEquip", value); } }
    public byte useFaceScale { get { return this.GenericParam.GetValue<byte>("useFaceScale"); } set { this.GenericParam.SetValue("useFaceScale", value); } }
    public byte isSkipWeakDamageAnim { get { return this.GenericParam.GetValue<byte>("isSkipWeakDamageAnim"); } set { this.GenericParam.SetValue("isSkipWeakDamageAnim", value); } }
    public byte pad06 { get { return this.GenericParam.GetValue<byte>("pad06"); } set { this.GenericParam.SetValue("pad06", value); } }
    public byte defenseMaterialVariationValue_Weak { get { return this.GenericParam.GetValue<byte>("defenseMaterialVariationValue_Weak"); } set { this.GenericParam.SetValue("defenseMaterialVariationValue_Weak", value); } }
    public short autoFootEffectDecalBaseId2 { get { return this.GenericParam.GetValue<short>("autoFootEffectDecalBaseId2"); } set { this.GenericParam.SetValue("autoFootEffectDecalBaseId2", value); } }
    public short autoFootEffectDecalBaseId3 { get { return this.GenericParam.GetValue<short>("autoFootEffectDecalBaseId3"); } set { this.GenericParam.SetValue("autoFootEffectDecalBaseId3", value); } }
    public byte defenseMaterialVariationValue { get { return this.GenericParam.GetValue<byte>("defenseMaterialVariationValue"); } set { this.GenericParam.SetValue("defenseMaterialVariationValue", value); } }
    public byte isDiscard { get { return this.GenericParam.GetValue<byte>("isDiscard"); } set { this.GenericParam.SetValue("isDiscard", value); } }
    public byte isDrop { get { return this.GenericParam.GetValue<byte>("isDrop"); } set { this.GenericParam.SetValue("isDrop", value); } }
    public byte disableMultiDropShare { get { return this.GenericParam.GetValue<byte>("disableMultiDropShare"); } set { this.GenericParam.SetValue("disableMultiDropShare", value); } }
    public byte simpleModelForDlc { get { return this.GenericParam.GetValue<byte>("simpleModelForDlc"); } set { this.GenericParam.SetValue("simpleModelForDlc", value); } }
    public byte showLogCondType { get { return this.GenericParam.GetValue<byte>("showLogCondType"); } set { this.GenericParam.SetValue("showLogCondType", value); } }
    public byte showDialogCondType { get { return this.GenericParam.GetValue<byte>("showDialogCondType"); } set { this.GenericParam.SetValue("showDialogCondType", value); } }
    public byte pad { get { return this.GenericParam.GetValue<byte>("pad"); } set { this.GenericParam.SetValue("pad", value); } }
    public float neutralDamageCutRate { get { return this.GenericParam.GetValue<float>("neutralDamageCutRate"); } set { this.GenericParam.SetValue("neutralDamageCutRate", value); } }
    public float slashDamageCutRate { get { return this.GenericParam.GetValue<float>("slashDamageCutRate"); } set { this.GenericParam.SetValue("slashDamageCutRate", value); } }
    public float blowDamageCutRate { get { return this.GenericParam.GetValue<float>("blowDamageCutRate"); } set { this.GenericParam.SetValue("blowDamageCutRate", value); } }
    public float thrustDamageCutRate { get { return this.GenericParam.GetValue<float>("thrustDamageCutRate"); } set { this.GenericParam.SetValue("thrustDamageCutRate", value); } }
    public float magicDamageCutRate { get { return this.GenericParam.GetValue<float>("magicDamageCutRate"); } set { this.GenericParam.SetValue("magicDamageCutRate", value); } }
    public float fireDamageCutRate { get { return this.GenericParam.GetValue<float>("fireDamageCutRate"); } set { this.GenericParam.SetValue("fireDamageCutRate", value); } }
    public float thunderDamageCutRate { get { return this.GenericParam.GetValue<float>("thunderDamageCutRate"); } set { this.GenericParam.SetValue("thunderDamageCutRate", value); } }
    public ushort defenseMaterialSfx1 { get { return this.GenericParam.GetValue<ushort>("defenseMaterialSfx1"); } set { this.GenericParam.SetValue("defenseMaterialSfx1", value); } }
    public ushort defenseMaterialSfx_Weak1 { get { return this.GenericParam.GetValue<ushort>("defenseMaterialSfx_Weak1"); } set { this.GenericParam.SetValue("defenseMaterialSfx_Weak1", value); } }
    public ushort defenseMaterial1 { get { return this.GenericParam.GetValue<ushort>("defenseMaterial1"); } set { this.GenericParam.SetValue("defenseMaterial1", value); } }
    public ushort defenseMaterial_Weak1 { get { return this.GenericParam.GetValue<ushort>("defenseMaterial_Weak1"); } set { this.GenericParam.SetValue("defenseMaterial_Weak1", value); } }
    public ushort defenseMaterialSfx2 { get { return this.GenericParam.GetValue<ushort>("defenseMaterialSfx2"); } set { this.GenericParam.SetValue("defenseMaterialSfx2", value); } }
    public ushort defenseMaterialSfx_Weak2 { get { return this.GenericParam.GetValue<ushort>("defenseMaterialSfx_Weak2"); } set { this.GenericParam.SetValue("defenseMaterialSfx_Weak2", value); } }
    public ushort footMaterialSe { get { return this.GenericParam.GetValue<ushort>("footMaterialSe"); } set { this.GenericParam.SetValue("footMaterialSe", value); } }
    public ushort defenseMaterial_Weak2 { get { return this.GenericParam.GetValue<ushort>("defenseMaterial_Weak2"); } set { this.GenericParam.SetValue("defenseMaterial_Weak2", value); } }
    public int autoFootEffectDecalBaseId1 { get { return this.GenericParam.GetValue<int>("autoFootEffectDecalBaseId1"); } set { this.GenericParam.SetValue("autoFootEffectDecalBaseId1", value); } }
    public float toughnessDamageCutRate { get { return this.GenericParam.GetValue<float>("toughnessDamageCutRate"); } set { this.GenericParam.SetValue("toughnessDamageCutRate", value); } }
    public float toughnessRecoverCorrection { get { return this.GenericParam.GetValue<float>("toughnessRecoverCorrection"); } set { this.GenericParam.SetValue("toughnessRecoverCorrection", value); } }
    public float darkDamageCutRate { get { return this.GenericParam.GetValue<float>("darkDamageCutRate"); } set { this.GenericParam.SetValue("darkDamageCutRate", value); } }
    public ushort defenseDark { get { return this.GenericParam.GetValue<ushort>("defenseDark"); } set { this.GenericParam.SetValue("defenseDark", value); } }
    public byte invisibleFlag48 { get { return this.GenericParam.GetValue<byte>("invisibleFlag48"); } set { this.GenericParam.SetValue("invisibleFlag48", value); } }
    public byte invisibleFlag49 { get { return this.GenericParam.GetValue<byte>("invisibleFlag49"); } set { this.GenericParam.SetValue("invisibleFlag49", value); } }
    public byte invisibleFlag50 { get { return this.GenericParam.GetValue<byte>("invisibleFlag50"); } set { this.GenericParam.SetValue("invisibleFlag50", value); } }
    public byte invisibleFlag51 { get { return this.GenericParam.GetValue<byte>("invisibleFlag51"); } set { this.GenericParam.SetValue("invisibleFlag51", value); } }
    public byte invisibleFlag52 { get { return this.GenericParam.GetValue<byte>("invisibleFlag52"); } set { this.GenericParam.SetValue("invisibleFlag52", value); } }
    public byte invisibleFlag53 { get { return this.GenericParam.GetValue<byte>("invisibleFlag53"); } set { this.GenericParam.SetValue("invisibleFlag53", value); } }
    public byte invisibleFlag54 { get { return this.GenericParam.GetValue<byte>("invisibleFlag54"); } set { this.GenericParam.SetValue("invisibleFlag54", value); } }
    public byte invisibleFlag55 { get { return this.GenericParam.GetValue<byte>("invisibleFlag55"); } set { this.GenericParam.SetValue("invisibleFlag55", value); } }
    public byte invisibleFlag56 { get { return this.GenericParam.GetValue<byte>("invisibleFlag56"); } set { this.GenericParam.SetValue("invisibleFlag56", value); } }
    public byte invisibleFlag57 { get { return this.GenericParam.GetValue<byte>("invisibleFlag57"); } set { this.GenericParam.SetValue("invisibleFlag57", value); } }
    public byte invisibleFlag58 { get { return this.GenericParam.GetValue<byte>("invisibleFlag58"); } set { this.GenericParam.SetValue("invisibleFlag58", value); } }
    public byte invisibleFlag59 { get { return this.GenericParam.GetValue<byte>("invisibleFlag59"); } set { this.GenericParam.SetValue("invisibleFlag59", value); } }
    public byte invisibleFlag60 { get { return this.GenericParam.GetValue<byte>("invisibleFlag60"); } set { this.GenericParam.SetValue("invisibleFlag60", value); } }
    public byte invisibleFlag61 { get { return this.GenericParam.GetValue<byte>("invisibleFlag61"); } set { this.GenericParam.SetValue("invisibleFlag61", value); } }
    public byte invisibleFlag62 { get { return this.GenericParam.GetValue<byte>("invisibleFlag62"); } set { this.GenericParam.SetValue("invisibleFlag62", value); } }
    public byte invisibleFlag63 { get { return this.GenericParam.GetValue<byte>("invisibleFlag63"); } set { this.GenericParam.SetValue("invisibleFlag63", value); } }
    public byte invisibleFlag64 { get { return this.GenericParam.GetValue<byte>("invisibleFlag64"); } set { this.GenericParam.SetValue("invisibleFlag64", value); } }
    public byte invisibleFlag65 { get { return this.GenericParam.GetValue<byte>("invisibleFlag65"); } set { this.GenericParam.SetValue("invisibleFlag65", value); } }
    public byte invisibleFlag66 { get { return this.GenericParam.GetValue<byte>("invisibleFlag66"); } set { this.GenericParam.SetValue("invisibleFlag66", value); } }
    public byte invisibleFlag67 { get { return this.GenericParam.GetValue<byte>("invisibleFlag67"); } set { this.GenericParam.SetValue("invisibleFlag67", value); } }
    public byte invisibleFlag68 { get { return this.GenericParam.GetValue<byte>("invisibleFlag68"); } set { this.GenericParam.SetValue("invisibleFlag68", value); } }
    public byte invisibleFlag69 { get { return this.GenericParam.GetValue<byte>("invisibleFlag69"); } set { this.GenericParam.SetValue("invisibleFlag69", value); } }
    public byte invisibleFlag70 { get { return this.GenericParam.GetValue<byte>("invisibleFlag70"); } set { this.GenericParam.SetValue("invisibleFlag70", value); } }
    public byte invisibleFlag71 { get { return this.GenericParam.GetValue<byte>("invisibleFlag71"); } set { this.GenericParam.SetValue("invisibleFlag71", value); } }
    public byte invisibleFlag72 { get { return this.GenericParam.GetValue<byte>("invisibleFlag72"); } set { this.GenericParam.SetValue("invisibleFlag72", value); } }
    public byte invisibleFlag73 { get { return this.GenericParam.GetValue<byte>("invisibleFlag73"); } set { this.GenericParam.SetValue("invisibleFlag73", value); } }
    public byte invisibleFlag74 { get { return this.GenericParam.GetValue<byte>("invisibleFlag74"); } set { this.GenericParam.SetValue("invisibleFlag74", value); } }
    public byte invisibleFlag75 { get { return this.GenericParam.GetValue<byte>("invisibleFlag75"); } set { this.GenericParam.SetValue("invisibleFlag75", value); } }
    public byte invisibleFlag76 { get { return this.GenericParam.GetValue<byte>("invisibleFlag76"); } set { this.GenericParam.SetValue("invisibleFlag76", value); } }
    public byte invisibleFlag77 { get { return this.GenericParam.GetValue<byte>("invisibleFlag77"); } set { this.GenericParam.SetValue("invisibleFlag77", value); } }
    public byte invisibleFlag78 { get { return this.GenericParam.GetValue<byte>("invisibleFlag78"); } set { this.GenericParam.SetValue("invisibleFlag78", value); } }
    public byte invisibleFlag79 { get { return this.GenericParam.GetValue<byte>("invisibleFlag79"); } set { this.GenericParam.SetValue("invisibleFlag79", value); } }
    public byte invisibleFlag80 { get { return this.GenericParam.GetValue<byte>("invisibleFlag80"); } set { this.GenericParam.SetValue("invisibleFlag80", value); } }
    public byte padbit { get { return this.GenericParam.GetValue<byte>("padbit"); } set { this.GenericParam.SetValue("padbit", value); } }
    public byte postureControlId { get { return this.GenericParam.GetValue<byte>("postureControlId"); } set { this.GenericParam.SetValue("postureControlId", value); } }
    public byte[] pad2 { get { return this.GenericParam.GetValue<byte[]>("pad2"); } set { this.GenericParam.SetValue("pad2", value); } }
    public int saleValue { get { return this.GenericParam.GetValue<int>("saleValue"); } set { this.GenericParam.SetValue("saleValue", value); } }
    public ushort resistFreeze { get { return this.GenericParam.GetValue<ushort>("resistFreeze"); } set { this.GenericParam.SetValue("resistFreeze", value); } }
    public byte invisibleFlag_SexVer00 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer00"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer00", value); } }
    public byte invisibleFlag_SexVer01 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer01"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer01", value); } }
    public byte invisibleFlag_SexVer02 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer02"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer02", value); } }
    public byte invisibleFlag_SexVer03 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer03"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer03", value); } }
    public byte invisibleFlag_SexVer04 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer04"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer04", value); } }
    public byte invisibleFlag_SexVer05 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer05"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer05", value); } }
    public byte invisibleFlag_SexVer06 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer06"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer06", value); } }
    public byte invisibleFlag_SexVer07 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer07"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer07", value); } }
    public byte invisibleFlag_SexVer08 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer08"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer08", value); } }
    public byte invisibleFlag_SexVer09 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer09"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer09", value); } }
    public byte invisibleFlag_SexVer10 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer10"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer10", value); } }
    public byte invisibleFlag_SexVer11 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer11"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer11", value); } }
    public byte invisibleFlag_SexVer12 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer12"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer12", value); } }
    public byte invisibleFlag_SexVer13 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer13"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer13", value); } }
    public byte invisibleFlag_SexVer14 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer14"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer14", value); } }
    public byte invisibleFlag_SexVer15 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer15"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer15", value); } }
    public byte invisibleFlag_SexVer16 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer16"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer16", value); } }
    public byte invisibleFlag_SexVer17 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer17"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer17", value); } }
    public byte invisibleFlag_SexVer18 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer18"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer18", value); } }
    public byte invisibleFlag_SexVer19 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer19"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer19", value); } }
    public byte invisibleFlag_SexVer20 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer20"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer20", value); } }
    public byte invisibleFlag_SexVer21 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer21"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer21", value); } }
    public byte invisibleFlag_SexVer22 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer22"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer22", value); } }
    public byte invisibleFlag_SexVer23 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer23"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer23", value); } }
    public byte invisibleFlag_SexVer24 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer24"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer24", value); } }
    public byte invisibleFlag_SexVer25 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer25"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer25", value); } }
    public byte invisibleFlag_SexVer26 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer26"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer26", value); } }
    public byte invisibleFlag_SexVer27 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer27"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer27", value); } }
    public byte invisibleFlag_SexVer28 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer28"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer28", value); } }
    public byte invisibleFlag_SexVer29 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer29"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer29", value); } }
    public byte invisibleFlag_SexVer30 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer30"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer30", value); } }
    public byte invisibleFlag_SexVer31 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer31"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer31", value); } }
    public byte invisibleFlag_SexVer32 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer32"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer32", value); } }
    public byte invisibleFlag_SexVer33 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer33"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer33", value); } }
    public byte invisibleFlag_SexVer34 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer34"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer34", value); } }
    public byte invisibleFlag_SexVer35 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer35"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer35", value); } }
    public byte invisibleFlag_SexVer36 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer36"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer36", value); } }
    public byte invisibleFlag_SexVer37 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer37"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer37", value); } }
    public byte invisibleFlag_SexVer38 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer38"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer38", value); } }
    public byte invisibleFlag_SexVer39 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer39"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer39", value); } }
    public byte invisibleFlag_SexVer40 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer40"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer40", value); } }
    public byte invisibleFlag_SexVer41 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer41"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer41", value); } }
    public byte invisibleFlag_SexVer42 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer42"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer42", value); } }
    public byte invisibleFlag_SexVer43 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer43"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer43", value); } }
    public byte invisibleFlag_SexVer44 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer44"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer44", value); } }
    public byte invisibleFlag_SexVer45 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer45"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer45", value); } }
    public byte invisibleFlag_SexVer46 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer46"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer46", value); } }
    public byte invisibleFlag_SexVer47 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer47"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer47", value); } }
    public byte invisibleFlag_SexVer48 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer48"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer48", value); } }
    public byte invisibleFlag_SexVer49 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer49"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer49", value); } }
    public byte invisibleFlag_SexVer50 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer50"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer50", value); } }
    public byte invisibleFlag_SexVer51 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer51"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer51", value); } }
    public byte invisibleFlag_SexVer52 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer52"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer52", value); } }
    public byte invisibleFlag_SexVer53 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer53"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer53", value); } }
    public byte invisibleFlag_SexVer54 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer54"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer54", value); } }
    public byte invisibleFlag_SexVer55 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer55"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer55", value); } }
    public byte invisibleFlag_SexVer56 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer56"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer56", value); } }
    public byte invisibleFlag_SexVer57 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer57"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer57", value); } }
    public byte invisibleFlag_SexVer58 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer58"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer58", value); } }
    public byte invisibleFlag_SexVer59 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer59"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer59", value); } }
    public byte invisibleFlag_SexVer60 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer60"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer60", value); } }
    public byte invisibleFlag_SexVer61 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer61"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer61", value); } }
    public byte invisibleFlag_SexVer62 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer62"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer62", value); } }
    public byte invisibleFlag_SexVer63 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer63"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer63", value); } }
    public byte invisibleFlag_SexVer64 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer64"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer64", value); } }
    public byte invisibleFlag_SexVer65 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer65"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer65", value); } }
    public byte invisibleFlag_SexVer66 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer66"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer66", value); } }
    public byte invisibleFlag_SexVer67 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer67"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer67", value); } }
    public byte invisibleFlag_SexVer68 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer68"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer68", value); } }
    public byte invisibleFlag_SexVer69 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer69"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer69", value); } }
    public byte invisibleFlag_SexVer70 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer70"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer70", value); } }
    public byte invisibleFlag_SexVer71 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer71"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer71", value); } }
    public byte invisibleFlag_SexVer72 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer72"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer72", value); } }
    public byte invisibleFlag_SexVer73 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer73"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer73", value); } }
    public byte invisibleFlag_SexVer74 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer74"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer74", value); } }
    public byte invisibleFlag_SexVer75 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer75"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer75", value); } }
    public byte invisibleFlag_SexVer76 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer76"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer76", value); } }
    public byte invisibleFlag_SexVer77 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer77"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer77", value); } }
    public byte invisibleFlag_SexVer78 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer78"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer78", value); } }
    public byte invisibleFlag_SexVer79 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer79"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer79", value); } }
    public byte invisibleFlag_SexVer80 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer80"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer80", value); } }
    public byte invisibleFlag_SexVer81 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer81"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer81", value); } }
    public byte invisibleFlag_SexVer82 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer82"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer82", value); } }
    public byte invisibleFlag_SexVer83 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer83"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer83", value); } }
    public byte invisibleFlag_SexVer84 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer84"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer84", value); } }
    public byte invisibleFlag_SexVer85 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer85"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer85", value); } }
    public byte invisibleFlag_SexVer86 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer86"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer86", value); } }
    public byte invisibleFlag_SexVer87 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer87"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer87", value); } }
    public byte invisibleFlag_SexVer88 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer88"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer88", value); } }
    public byte invisibleFlag_SexVer89 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer89"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer89", value); } }
    public byte invisibleFlag_SexVer90 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer90"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer90", value); } }
    public byte invisibleFlag_SexVer91 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer91"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer91", value); } }
    public byte invisibleFlag_SexVer92 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer92"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer92", value); } }
    public byte invisibleFlag_SexVer93 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer93"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer93", value); } }
    public byte invisibleFlag_SexVer94 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer94"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer94", value); } }
    public byte invisibleFlag_SexVer95 { get { return this.GenericParam.GetValue<byte>("invisibleFlag_SexVer95"); } set { this.GenericParam.SetValue("invisibleFlag_SexVer95", value); } }
    public byte[] pad404 { get { return this.GenericParam.GetValue<byte[]>("pad404"); } set { this.GenericParam.SetValue("pad404", value); } }
}
