public class EquipParamGem : ParamBase<EquipParamGem>
{
    public string Name { get { return this.GetValue<string>("Name"); } set { this.SetValue("Name", value); } }
    public byte disableParam_NT { get { return this.GetValue<byte>("disableParam_NT"); } set { this.SetValue("disableParam_NT", value); } }
    public byte disableParamReserve1 { get { return this.GetValue<byte>("disableParamReserve1"); } set { this.SetValue("disableParamReserve1", value); } }
    public Byte[] disableParamReserve2 { get { return this.GetValue<Byte[]>("disableParamReserve2"); } set { this.SetValue("disableParamReserve2", value); } }
    public ushort iconId { get { return this.GetValue<ushort>("iconId"); } set { this.SetValue("iconId", value); } }
    public sbyte rank { get { return this.GetValue<sbyte>("rank"); } set { this.SetValue("rank", value); } }
    public byte sortGroupId { get { return this.GetValue<byte>("sortGroupId"); } set { this.SetValue("sortGroupId", value); } }
    public int spEffectId0 { get { return this.GetValue<int>("spEffectId0"); } set { this.SetValue("spEffectId0", value); } }
    public int spEffectId1 { get { return this.GetValue<int>("spEffectId1"); } set { this.SetValue("spEffectId1", value); } }
    public int spEffectId2 { get { return this.GetValue<int>("spEffectId2"); } set { this.SetValue("spEffectId2", value); } }
    public uint itemGetTutorialFlagId { get { return this.GetValue<uint>("itemGetTutorialFlagId"); } set { this.SetValue("itemGetTutorialFlagId", value); } }
    public int swordArtsParamId { get { return this.GetValue<int>("swordArtsParamId"); } set { this.SetValue("swordArtsParamId", value); } }
    public int mountValue { get { return this.GetValue<int>("mountValue"); } set { this.SetValue("mountValue", value); } }
    public int sellValue { get { return this.GetValue<int>("sellValue"); } set { this.SetValue("sellValue", value); } }
    public int saleValue { get { return this.GetValue<int>("saleValue"); } set { this.SetValue("saleValue", value); } }
    public int sortId { get { return this.GetValue<int>("sortId"); } set { this.SetValue("sortId", value); } }
    public short compTrophySedId { get { return this.GetValue<short>("compTrophySedId"); } set { this.SetValue("compTrophySedId", value); } }
    public short trophySeqId { get { return this.GetValue<short>("trophySeqId"); } set { this.SetValue("trophySeqId", value); } }
    public byte configurableWepAttr00 { get { return this.GetValue<byte>("configurableWepAttr00"); } set { this.SetValue("configurableWepAttr00", value); } }
    public byte configurableWepAttr01 { get { return this.GetValue<byte>("configurableWepAttr01"); } set { this.SetValue("configurableWepAttr01", value); } }
    public byte configurableWepAttr02 { get { return this.GetValue<byte>("configurableWepAttr02"); } set { this.SetValue("configurableWepAttr02", value); } }
    public byte configurableWepAttr03 { get { return this.GetValue<byte>("configurableWepAttr03"); } set { this.SetValue("configurableWepAttr03", value); } }
    public byte configurableWepAttr04 { get { return this.GetValue<byte>("configurableWepAttr04"); } set { this.SetValue("configurableWepAttr04", value); } }
    public byte configurableWepAttr05 { get { return this.GetValue<byte>("configurableWepAttr05"); } set { this.SetValue("configurableWepAttr05", value); } }
    public byte configurableWepAttr06 { get { return this.GetValue<byte>("configurableWepAttr06"); } set { this.SetValue("configurableWepAttr06", value); } }
    public byte configurableWepAttr07 { get { return this.GetValue<byte>("configurableWepAttr07"); } set { this.SetValue("configurableWepAttr07", value); } }
    public byte configurableWepAttr08 { get { return this.GetValue<byte>("configurableWepAttr08"); } set { this.SetValue("configurableWepAttr08", value); } }
    public byte configurableWepAttr09 { get { return this.GetValue<byte>("configurableWepAttr09"); } set { this.SetValue("configurableWepAttr09", value); } }
    public byte configurableWepAttr10 { get { return this.GetValue<byte>("configurableWepAttr10"); } set { this.SetValue("configurableWepAttr10", value); } }
    public byte configurableWepAttr11 { get { return this.GetValue<byte>("configurableWepAttr11"); } set { this.SetValue("configurableWepAttr11", value); } }
    public byte configurableWepAttr12 { get { return this.GetValue<byte>("configurableWepAttr12"); } set { this.SetValue("configurableWepAttr12", value); } }
    public byte configurableWepAttr13 { get { return this.GetValue<byte>("configurableWepAttr13"); } set { this.SetValue("configurableWepAttr13", value); } }
    public byte configurableWepAttr14 { get { return this.GetValue<byte>("configurableWepAttr14"); } set { this.SetValue("configurableWepAttr14", value); } }
    public byte configurableWepAttr15 { get { return this.GetValue<byte>("configurableWepAttr15"); } set { this.SetValue("configurableWepAttr15", value); } }
    public byte rarity { get { return this.GetValue<byte>("rarity"); } set { this.SetValue("rarity", value); } }
    public byte configurableWepAttr16 { get { return this.GetValue<byte>("configurableWepAttr16"); } set { this.SetValue("configurableWepAttr16", value); } }
    public byte configurableWepAttr17 { get { return this.GetValue<byte>("configurableWepAttr17"); } set { this.SetValue("configurableWepAttr17", value); } }
    public byte configurableWepAttr18 { get { return this.GetValue<byte>("configurableWepAttr18"); } set { this.SetValue("configurableWepAttr18", value); } }
    public byte configurableWepAttr19 { get { return this.GetValue<byte>("configurableWepAttr19"); } set { this.SetValue("configurableWepAttr19", value); } }
    public byte configurableWepAttr20 { get { return this.GetValue<byte>("configurableWepAttr20"); } set { this.SetValue("configurableWepAttr20", value); } }
    public byte configurableWepAttr21 { get { return this.GetValue<byte>("configurableWepAttr21"); } set { this.SetValue("configurableWepAttr21", value); } }
    public byte configurableWepAttr22 { get { return this.GetValue<byte>("configurableWepAttr22"); } set { this.SetValue("configurableWepAttr22", value); } }
    public byte configurableWepAttr23 { get { return this.GetValue<byte>("configurableWepAttr23"); } set { this.SetValue("configurableWepAttr23", value); } }
    public byte isDiscard { get { return this.GetValue<byte>("isDiscard"); } set { this.SetValue("isDiscard", value); } }
    public byte isDrop { get { return this.GetValue<byte>("isDrop"); } set { this.SetValue("isDrop", value); } }
    public byte isDeposit { get { return this.GetValue<byte>("isDeposit"); } set { this.SetValue("isDeposit", value); } }
    public byte disableMultiDropShare { get { return this.GetValue<byte>("disableMultiDropShare"); } set { this.SetValue("disableMultiDropShare", value); } }
    public byte showDialogCondType { get { return this.GetValue<byte>("showDialogCondType"); } set { this.SetValue("showDialogCondType", value); } }
    public byte showLogCondType { get { return this.GetValue<byte>("showLogCondType"); } set { this.SetValue("showLogCondType", value); } }
    public byte pad { get { return this.GetValue<byte>("pad"); } set { this.SetValue("pad", value); } }
    public byte defaultWepAttr { get { return this.GetValue<byte>("defaultWepAttr"); } set { this.SetValue("defaultWepAttr", value); } }
    public byte isSpecialSwordArt { get { return this.GetValue<byte>("isSpecialSwordArt"); } set { this.SetValue("isSpecialSwordArt", value); } }
    public Byte[] pad2 { get { return this.GetValue<Byte[]>("pad2"); } set { this.SetValue("pad2", value); } }
    public byte canMountWep_Dagger { get { return this.GetValue<byte>("canMountWep_Dagger"); } set { this.SetValue("canMountWep_Dagger", value); } }
    public byte canMountWep_SwordNormal { get { return this.GetValue<byte>("canMountWep_SwordNormal"); } set { this.SetValue("canMountWep_SwordNormal", value); } }
    public byte canMountWep_SwordLarge { get { return this.GetValue<byte>("canMountWep_SwordLarge"); } set { this.SetValue("canMountWep_SwordLarge", value); } }
    public byte canMountWep_SwordGigantic { get { return this.GetValue<byte>("canMountWep_SwordGigantic"); } set { this.SetValue("canMountWep_SwordGigantic", value); } }
    public byte canMountWep_SaberNormal { get { return this.GetValue<byte>("canMountWep_SaberNormal"); } set { this.SetValue("canMountWep_SaberNormal", value); } }
    public byte canMountWep_SaberLarge { get { return this.GetValue<byte>("canMountWep_SaberLarge"); } set { this.SetValue("canMountWep_SaberLarge", value); } }
    public byte canMountWep_katana { get { return this.GetValue<byte>("canMountWep_katana"); } set { this.SetValue("canMountWep_katana", value); } }
    public byte canMountWep_SwordDoubleEdge { get { return this.GetValue<byte>("canMountWep_SwordDoubleEdge"); } set { this.SetValue("canMountWep_SwordDoubleEdge", value); } }
    public byte canMountWep_SwordPierce { get { return this.GetValue<byte>("canMountWep_SwordPierce"); } set { this.SetValue("canMountWep_SwordPierce", value); } }
    public byte canMountWep_RapierHeavy { get { return this.GetValue<byte>("canMountWep_RapierHeavy"); } set { this.SetValue("canMountWep_RapierHeavy", value); } }
    public byte canMountWep_AxeNormal { get { return this.GetValue<byte>("canMountWep_AxeNormal"); } set { this.SetValue("canMountWep_AxeNormal", value); } }
    public byte canMountWep_AxeLarge { get { return this.GetValue<byte>("canMountWep_AxeLarge"); } set { this.SetValue("canMountWep_AxeLarge", value); } }
    public byte canMountWep_HammerNormal { get { return this.GetValue<byte>("canMountWep_HammerNormal"); } set { this.SetValue("canMountWep_HammerNormal", value); } }
    public byte canMountWep_HammerLarge { get { return this.GetValue<byte>("canMountWep_HammerLarge"); } set { this.SetValue("canMountWep_HammerLarge", value); } }
    public byte canMountWep_Flail { get { return this.GetValue<byte>("canMountWep_Flail"); } set { this.SetValue("canMountWep_Flail", value); } }
    public byte canMountWep_SpearNormal { get { return this.GetValue<byte>("canMountWep_SpearNormal"); } set { this.SetValue("canMountWep_SpearNormal", value); } }
    public byte canMountWep_SpearLarge { get { return this.GetValue<byte>("canMountWep_SpearLarge"); } set { this.SetValue("canMountWep_SpearLarge", value); } }
    public byte canMountWep_SpearHeavy { get { return this.GetValue<byte>("canMountWep_SpearHeavy"); } set { this.SetValue("canMountWep_SpearHeavy", value); } }
    public byte canMountWep_SpearAxe { get { return this.GetValue<byte>("canMountWep_SpearAxe"); } set { this.SetValue("canMountWep_SpearAxe", value); } }
    public byte canMountWep_Sickle { get { return this.GetValue<byte>("canMountWep_Sickle"); } set { this.SetValue("canMountWep_Sickle", value); } }
    public byte canMountWep_Knuckle { get { return this.GetValue<byte>("canMountWep_Knuckle"); } set { this.SetValue("canMountWep_Knuckle", value); } }
    public byte canMountWep_Claw { get { return this.GetValue<byte>("canMountWep_Claw"); } set { this.SetValue("canMountWep_Claw", value); } }
    public byte canMountWep_Whip { get { return this.GetValue<byte>("canMountWep_Whip"); } set { this.SetValue("canMountWep_Whip", value); } }
    public byte canMountWep_AxhammerLarge { get { return this.GetValue<byte>("canMountWep_AxhammerLarge"); } set { this.SetValue("canMountWep_AxhammerLarge", value); } }
    public byte canMountWep_BowSmall { get { return this.GetValue<byte>("canMountWep_BowSmall"); } set { this.SetValue("canMountWep_BowSmall", value); } }
    public byte canMountWep_BowNormal { get { return this.GetValue<byte>("canMountWep_BowNormal"); } set { this.SetValue("canMountWep_BowNormal", value); } }
    public byte canMountWep_BowLarge { get { return this.GetValue<byte>("canMountWep_BowLarge"); } set { this.SetValue("canMountWep_BowLarge", value); } }
    public byte canMountWep_ClossBow { get { return this.GetValue<byte>("canMountWep_ClossBow"); } set { this.SetValue("canMountWep_ClossBow", value); } }
    public byte canMountWep_Ballista { get { return this.GetValue<byte>("canMountWep_Ballista"); } set { this.SetValue("canMountWep_Ballista", value); } }
    public byte canMountWep_Staff { get { return this.GetValue<byte>("canMountWep_Staff"); } set { this.SetValue("canMountWep_Staff", value); } }
    public byte canMountWep_Sorcery { get { return this.GetValue<byte>("canMountWep_Sorcery"); } set { this.SetValue("canMountWep_Sorcery", value); } }
    public byte canMountWep_Talisman { get { return this.GetValue<byte>("canMountWep_Talisman"); } set { this.SetValue("canMountWep_Talisman", value); } }
    public byte canMountWep_ShieldSmall { get { return this.GetValue<byte>("canMountWep_ShieldSmall"); } set { this.SetValue("canMountWep_ShieldSmall", value); } }
    public byte canMountWep_ShieldNormal { get { return this.GetValue<byte>("canMountWep_ShieldNormal"); } set { this.SetValue("canMountWep_ShieldNormal", value); } }
    public byte canMountWep_ShieldLarge { get { return this.GetValue<byte>("canMountWep_ShieldLarge"); } set { this.SetValue("canMountWep_ShieldLarge", value); } }
    public byte canMountWep_Torch { get { return this.GetValue<byte>("canMountWep_Torch"); } set { this.SetValue("canMountWep_Torch", value); } }
    public byte canMountWep_HandToHand { get { return this.GetValue<byte>("canMountWep_HandToHand"); } set { this.SetValue("canMountWep_HandToHand", value); } }
    public byte canMountWep_PerfumeBottle { get { return this.GetValue<byte>("canMountWep_PerfumeBottle"); } set { this.SetValue("canMountWep_PerfumeBottle", value); } }
    public byte canMountWep_ThrustingShield { get { return this.GetValue<byte>("canMountWep_ThrustingShield"); } set { this.SetValue("canMountWep_ThrustingShield", value); } }
    public byte canMountWep_ThrowingWeapon { get { return this.GetValue<byte>("canMountWep_ThrowingWeapon"); } set { this.SetValue("canMountWep_ThrowingWeapon", value); } }
    public byte canMountWep_ReverseHandSword { get { return this.GetValue<byte>("canMountWep_ReverseHandSword"); } set { this.SetValue("canMountWep_ReverseHandSword", value); } }
    public byte canMountWep_LightGreatsword { get { return this.GetValue<byte>("canMountWep_LightGreatsword"); } set { this.SetValue("canMountWep_LightGreatsword", value); } }
    public byte canMountWep_GreatKatana { get { return this.GetValue<byte>("canMountWep_GreatKatana"); } set { this.SetValue("canMountWep_GreatKatana", value); } }
    public byte canMountWep_BeastClaw { get { return this.GetValue<byte>("canMountWep_BeastClaw"); } set { this.SetValue("canMountWep_BeastClaw", value); } }
    public byte reserved_canMountWep_0x3d_4 { get { return this.GetValue<byte>("reserved_canMountWep_0x3d_4"); } set { this.SetValue("reserved_canMountWep_0x3d_4", value); } }
    public Byte[] reserved2_canMountWep { get { return this.GetValue<Byte[]>("reserved2_canMountWep"); } set { this.SetValue("reserved2_canMountWep", value); } }
    public int spEffectMsgId0 { get { return this.GetValue<int>("spEffectMsgId0"); } set { this.SetValue("spEffectMsgId0", value); } }
    public int spEffectMsgId1 { get { return this.GetValue<int>("spEffectMsgId1"); } set { this.SetValue("spEffectMsgId1", value); } }
    public int spEffectId_forAtk0 { get { return this.GetValue<int>("spEffectId_forAtk0"); } set { this.SetValue("spEffectId_forAtk0", value); } }
    public int spEffectId_forAtk1 { get { return this.GetValue<int>("spEffectId_forAtk1"); } set { this.SetValue("spEffectId_forAtk1", value); } }
    public int spEffectId_forAtk2 { get { return this.GetValue<int>("spEffectId_forAtk2"); } set { this.SetValue("spEffectId_forAtk2", value); } }
    public int mountWepTextId { get { return this.GetValue<int>("mountWepTextId"); } set { this.SetValue("mountWepTextId", value); } }
    public Byte[] pad6 { get { return this.GetValue<Byte[]>("pad6"); } set { this.SetValue("pad6", value); } }
}
