
namespace DSLRNet.Core.Contracts.Params;

public partial class ItemLotParam_enemy : ParamBase<ItemLotParam_enemy>
{
    public int ID { get { return this.GenericParam.GetValue<int>("ID"); } set { this.GenericParam.SetValue("ID", value); } }
    public string Name { get { return this.GenericParam.GetValue<string>("Name"); } set { this.GenericParam.SetValue("Name", value); } }
    public int lotItemId01 { get { return this.GenericParam.GetValue<int>("lotItemId01"); } set { this.GenericParam.SetValue("lotItemId01", value); } }
    public int lotItemId02 { get { return this.GenericParam.GetValue<int>("lotItemId02"); } set { this.GenericParam.SetValue("lotItemId02", value); } }
    public int lotItemId03 { get { return this.GenericParam.GetValue<int>("lotItemId03"); } set { this.GenericParam.SetValue("lotItemId03", value); } }
    public int lotItemId04 { get { return this.GenericParam.GetValue<int>("lotItemId04"); } set { this.GenericParam.SetValue("lotItemId04", value); } }
    public int lotItemId05 { get { return this.GenericParam.GetValue<int>("lotItemId05"); } set { this.GenericParam.SetValue("lotItemId05", value); } }
    public int lotItemId06 { get { return this.GenericParam.GetValue<int>("lotItemId06"); } set { this.GenericParam.SetValue("lotItemId06", value); } }
    public int lotItemId07 { get { return this.GenericParam.GetValue<int>("lotItemId07"); } set { this.GenericParam.SetValue("lotItemId07", value); } }
    public int lotItemId08 { get { return this.GenericParam.GetValue<int>("lotItemId08"); } set { this.GenericParam.SetValue("lotItemId08", value); } }
    public int lotItemCategory01 { get { return this.GenericParam.GetValue<int>("lotItemCategory01"); } set { this.GenericParam.SetValue("lotItemCategory01", value); } }
    public int lotItemCategory02 { get { return this.GenericParam.GetValue<int>("lotItemCategory02"); } set { this.GenericParam.SetValue("lotItemCategory02", value); } }
    public int lotItemCategory03 { get { return this.GenericParam.GetValue<int>("lotItemCategory03"); } set { this.GenericParam.SetValue("lotItemCategory03", value); } }
    public int lotItemCategory04 { get { return this.GenericParam.GetValue<int>("lotItemCategory04"); } set { this.GenericParam.SetValue("lotItemCategory04", value); } }
    public int lotItemCategory05 { get { return this.GenericParam.GetValue<int>("lotItemCategory05"); } set { this.GenericParam.SetValue("lotItemCategory05", value); } }
    public int lotItemCategory06 { get { return this.GenericParam.GetValue<int>("lotItemCategory06"); } set { this.GenericParam.SetValue("lotItemCategory06", value); } }
    public int lotItemCategory07 { get { return this.GenericParam.GetValue<int>("lotItemCategory07"); } set { this.GenericParam.SetValue("lotItemCategory07", value); } }
    public int lotItemCategory08 { get { return this.GenericParam.GetValue<int>("lotItemCategory08"); } set { this.GenericParam.SetValue("lotItemCategory08", value); } }
    public int lotItemBasePoint01 { get { return this.GenericParam.GetValue<int>("lotItemBasePoint01"); } set { this.GenericParam.SetValue("lotItemBasePoint01", value); } }
    public int lotItemBasePoint02 { get { return this.GenericParam.GetValue<int>("lotItemBasePoint02"); } set { this.GenericParam.SetValue("lotItemBasePoint02", value); } }
    public int lotItemBasePoint03 { get { return this.GenericParam.GetValue<int>("lotItemBasePoint03"); } set { this.GenericParam.SetValue("lotItemBasePoint03", value); } }
    public int lotItemBasePoint04 { get { return this.GenericParam.GetValue<int>("lotItemBasePoint04"); } set { this.GenericParam.SetValue("lotItemBasePoint04", value); } }
    public int lotItemBasePoint05 { get { return this.GenericParam.GetValue<int>("lotItemBasePoint05"); } set { this.GenericParam.SetValue("lotItemBasePoint05", value); } }
    public int lotItemBasePoint06 { get { return this.GenericParam.GetValue<int>("lotItemBasePoint06"); } set { this.GenericParam.SetValue("lotItemBasePoint06", value); } }
    public int lotItemBasePoint07 { get { return this.GenericParam.GetValue<int>("lotItemBasePoint07"); } set { this.GenericParam.SetValue("lotItemBasePoint07", value); } }
    public int lotItemBasePoint08 { get { return this.GenericParam.GetValue<int>("lotItemBasePoint08"); } set { this.GenericParam.SetValue("lotItemBasePoint08", value); } }
    public int cumulateLotPoint01 { get { return this.GenericParam.GetValue<int>("cumulateLotPoint01"); } set { this.GenericParam.SetValue("cumulateLotPoint01", value); } }
    public int cumulateLotPoint02 { get { return this.GenericParam.GetValue<int>("cumulateLotPoint02"); } set { this.GenericParam.SetValue("cumulateLotPoint02", value); } }
    public int cumulateLotPoint03 { get { return this.GenericParam.GetValue<int>("cumulateLotPoint03"); } set { this.GenericParam.SetValue("cumulateLotPoint03", value); } }
    public int cumulateLotPoint04 { get { return this.GenericParam.GetValue<int>("cumulateLotPoint04"); } set { this.GenericParam.SetValue("cumulateLotPoint04", value); } }
    public int cumulateLotPoint05 { get { return this.GenericParam.GetValue<int>("cumulateLotPoint05"); } set { this.GenericParam.SetValue("cumulateLotPoint05", value); } }
    public int cumulateLotPoint06 { get { return this.GenericParam.GetValue<int>("cumulateLotPoint06"); } set { this.GenericParam.SetValue("cumulateLotPoint06", value); } }
    public int cumulateLotPoint07 { get { return this.GenericParam.GetValue<int>("cumulateLotPoint07"); } set { this.GenericParam.SetValue("cumulateLotPoint07", value); } }
    public int cumulateLotPoint08 { get { return this.GenericParam.GetValue<int>("cumulateLotPoint08"); } set { this.GenericParam.SetValue("cumulateLotPoint08", value); } }
    public int getItemFlagId01 { get { return this.GenericParam.GetValue<int>("getItemFlagId01"); } set { this.GenericParam.SetValue("getItemFlagId01", value); } }
    public int getItemFlagId02 { get { return this.GenericParam.GetValue<int>("getItemFlagId02"); } set { this.GenericParam.SetValue("getItemFlagId02", value); } }
    public int getItemFlagId03 { get { return this.GenericParam.GetValue<int>("getItemFlagId03"); } set { this.GenericParam.SetValue("getItemFlagId03", value); } }
    public int getItemFlagId04 { get { return this.GenericParam.GetValue<int>("getItemFlagId04"); } set { this.GenericParam.SetValue("getItemFlagId04", value); } }
    public int getItemFlagId05 { get { return this.GenericParam.GetValue<int>("getItemFlagId05"); } set { this.GenericParam.SetValue("getItemFlagId05", value); } }
    public int getItemFlagId06 { get { return this.GenericParam.GetValue<int>("getItemFlagId06"); } set { this.GenericParam.SetValue("getItemFlagId06", value); } }
    public int getItemFlagId07 { get { return this.GenericParam.GetValue<int>("getItemFlagId07"); } set { this.GenericParam.SetValue("getItemFlagId07", value); } }
    public int getItemFlagId08 { get { return this.GenericParam.GetValue<int>("getItemFlagId08"); } set { this.GenericParam.SetValue("getItemFlagId08", value); } }
    public int getItemFlagId { get { return this.GenericParam.GetValue<int>("getItemFlagId"); } set { this.GenericParam.SetValue("getItemFlagId", value); } }
    public int cumulateNumFlagId { get { return this.GenericParam.GetValue<int>("cumulateNumFlagId"); } set { this.GenericParam.SetValue("cumulateNumFlagId", value); } }
    public int cumulateNumMax { get { return this.GenericParam.GetValue<int>("cumulateNumMax"); } set { this.GenericParam.SetValue("cumulateNumMax", value); } }
    public int lotItem_Rarity { get { return this.GenericParam.GetValue<int>("lotItem_Rarity"); } set { this.GenericParam.SetValue("lotItem_Rarity", value); } }
    public int lotItemNum01 { get { return this.GenericParam.GetValue<int>("lotItemNum01"); } set { this.GenericParam.SetValue("lotItemNum01", value); } }
    public int lotItemNum02 { get { return this.GenericParam.GetValue<int>("lotItemNum02"); } set { this.GenericParam.SetValue("lotItemNum02", value); } }
    public int lotItemNum03 { get { return this.GenericParam.GetValue<int>("lotItemNum03"); } set { this.GenericParam.SetValue("lotItemNum03", value); } }
    public int lotItemNum04 { get { return this.GenericParam.GetValue<int>("lotItemNum04"); } set { this.GenericParam.SetValue("lotItemNum04", value); } }
    public int lotItemNum05 { get { return this.GenericParam.GetValue<int>("lotItemNum05"); } set { this.GenericParam.SetValue("lotItemNum05", value); } }
    public int lotItemNum06 { get { return this.GenericParam.GetValue<int>("lotItemNum06"); } set { this.GenericParam.SetValue("lotItemNum06", value); } }
    public int lotItemNum07 { get { return this.GenericParam.GetValue<int>("lotItemNum07"); } set { this.GenericParam.SetValue("lotItemNum07", value); } }
    public int lotItemNum08 { get { return this.GenericParam.GetValue<int>("lotItemNum08"); } set { this.GenericParam.SetValue("lotItemNum08", value); } }
    public int enableLuck01 { get { return this.GenericParam.GetValue<int>("enableLuck01"); } set { this.GenericParam.SetValue("enableLuck01", value); } }
    public int enableLuck02 { get { return this.GenericParam.GetValue<int>("enableLuck02"); } set { this.GenericParam.SetValue("enableLuck02", value); } }
    public int enableLuck03 { get { return this.GenericParam.GetValue<int>("enableLuck03"); } set { this.GenericParam.SetValue("enableLuck03", value); } }
    public int enableLuck04 { get { return this.GenericParam.GetValue<int>("enableLuck04"); } set { this.GenericParam.SetValue("enableLuck04", value); } }
    public int enableLuck05 { get { return this.GenericParam.GetValue<int>("enableLuck05"); } set { this.GenericParam.SetValue("enableLuck05", value); } }
    public int enableLuck06 { get { return this.GenericParam.GetValue<int>("enableLuck06"); } set { this.GenericParam.SetValue("enableLuck06", value); } }
    public int enableLuck07 { get { return this.GenericParam.GetValue<int>("enableLuck07"); } set { this.GenericParam.SetValue("enableLuck07", value); } }
    public int enableLuck08 { get { return this.GenericParam.GetValue<int>("enableLuck08"); } set { this.GenericParam.SetValue("enableLuck08", value); } }
    public int cumulateReset01 { get { return this.GenericParam.GetValue<int>("cumulateReset01"); } set { this.GenericParam.SetValue("cumulateReset01", value); } }
    public int cumulateReset02 { get { return this.GenericParam.GetValue<int>("cumulateReset02"); } set { this.GenericParam.SetValue("cumulateReset02", value); } }
    public int cumulateReset03 { get { return this.GenericParam.GetValue<int>("cumulateReset03"); } set { this.GenericParam.SetValue("cumulateReset03", value); } }
    public int cumulateReset04 { get { return this.GenericParam.GetValue<int>("cumulateReset04"); } set { this.GenericParam.SetValue("cumulateReset04", value); } }
    public int cumulateReset05 { get { return this.GenericParam.GetValue<int>("cumulateReset05"); } set { this.GenericParam.SetValue("cumulateReset05", value); } }
    public int cumulateReset06 { get { return this.GenericParam.GetValue<int>("cumulateReset06"); } set { this.GenericParam.SetValue("cumulateReset06", value); } }
    public int cumulateReset07 { get { return this.GenericParam.GetValue<int>("cumulateReset07"); } set { this.GenericParam.SetValue("cumulateReset07", value); } }
    public int cumulateReset08 { get { return this.GenericParam.GetValue<int>("cumulateReset08"); } set { this.GenericParam.SetValue("cumulateReset08", value); } }
    public int GameClearOffset { get { return this.GenericParam.GetValue<int>("GameClearOffset"); } set { this.GenericParam.SetValue("GameClearOffset", value); } }
    public int canExecByFriendlyGhost { get { return this.GenericParam.GetValue<int>("canExecByFriendlyGhost"); } set { this.GenericParam.SetValue("canExecByFriendlyGhost", value); } }
    public int canExecByHostileGhost { get { return this.GenericParam.GetValue<int>("canExecByHostileGhost"); } set { this.GenericParam.SetValue("canExecByHostileGhost", value); } }
    public int PAD1 { get { return this.GenericParam.GetValue<int>("PAD1"); } set { this.GenericParam.SetValue("PAD1", value); } }
    public int PAD2 { get { return this.GenericParam.GetValue<int>("PAD2"); } set { this.GenericParam.SetValue("PAD2", value); } }
}