using System;

public class ItemLotParam_map : ParamBase<ItemLotParam_map>
{
    public int ID { get { return this.GenericParam.GetValue<int>("ID"); } set { this.GenericParam.SetValue("ID", value); } }
    public string Name { get { return this.GenericParam.GetValue<string>("Name"); } set { this.GenericParam.SetValue("Name", value); } }
    public int lotItemId01 { get { return this.GenericParam.GetValue<int>("lotItemId01"); } set { this.GenericParam.SetValue("lotItemId01", value); } }
    public int lotItemId02 { get { return this.GenericParam.GetValue<int>("lotItemId02"); } set { this.GenericParam.SetValue("lotItemId02", value); } }
    public int lotItemId03 { get { return this.GenericParam.GetValue<int>("lotItemId03"); } set { this.GenericParam.SetValue("lotItemId03", value); } }
    public int lotItemId04 { get { return this.GenericParam.GetValue<int>("lotItemId04"); } set { this.GenericParam.SetValue("lotItemId04", value); } }
    public int lotItemId05 { get { return this.GenericParam.GetValue<int>("lotItemId05"); } set { this.GenericParam.SetValue("lotItemId05", value); } }
    public int lotItemId06 { get { return this.GenericParam.GetValue<int>("lotItemId06"); } set { this.GenericParam.SetValue("lotItemId06", value); } }
    public int lotItemId07 { get { return this.GenericParam.GetValue<int>("lotItemId07"); } set { this.GenericParam.SetValue("lotItemId07", value); } }
    public int lotItemId08 { get { return this.GenericParam.GetValue<int>("lotItemId08"); } set { this.GenericParam.SetValue("lotItemId08", value); } }
    public int lotItemCategory01 { get { return this.GenericParam.GetValue<int>("lotItemCategory01"); } set { this.GenericParam.SetValue("lotItemCategory01", value); } }
    public int lotItemCategory02 { get { return this.GenericParam.GetValue<int>("lotItemCategory02"); } set { this.GenericParam.SetValue("lotItemCategory02", value); } }
    public int lotItemCategory03 { get { return this.GenericParam.GetValue<int>("lotItemCategory03"); } set { this.GenericParam.SetValue("lotItemCategory03", value); } }
    public int lotItemCategory04 { get { return this.GenericParam.GetValue<int>("lotItemCategory04"); } set { this.GenericParam.SetValue("lotItemCategory04", value); } }
    public int lotItemCategory05 { get { return this.GenericParam.GetValue<int>("lotItemCategory05"); } set { this.GenericParam.SetValue("lotItemCategory05", value); } }
    public int lotItemCategory06 { get { return this.GenericParam.GetValue<int>("lotItemCategory06"); } set { this.GenericParam.SetValue("lotItemCategory06", value); } }
    public int lotItemCategory07 { get { return this.GenericParam.GetValue<int>("lotItemCategory07"); } set { this.GenericParam.SetValue("lotItemCategory07", value); } }
    public int lotItemCategory08 { get { return this.GenericParam.GetValue<int>("lotItemCategory08"); } set { this.GenericParam.SetValue("lotItemCategory08", value); } }
    public ushort lotItemBasePoint01 { get { return this.GenericParam.GetValue<ushort>("lotItemBasePoint01"); } set { this.GenericParam.SetValue("lotItemBasePoint01", value); } }
    public ushort lotItemBasePoint02 { get { return this.GenericParam.GetValue<ushort>("lotItemBasePoint02"); } set { this.GenericParam.SetValue("lotItemBasePoint02", value); } }
    public ushort lotItemBasePoint03 { get { return this.GenericParam.GetValue<ushort>("lotItemBasePoint03"); } set { this.GenericParam.SetValue("lotItemBasePoint03", value); } }
    public ushort lotItemBasePoint04 { get { return this.GenericParam.GetValue<ushort>("lotItemBasePoint04"); } set { this.GenericParam.SetValue("lotItemBasePoint04", value); } }
    public ushort lotItemBasePoint05 { get { return this.GenericParam.GetValue<ushort>("lotItemBasePoint05"); } set { this.GenericParam.SetValue("lotItemBasePoint05", value); } }
    public ushort lotItemBasePoint06 { get { return this.GenericParam.GetValue<ushort>("lotItemBasePoint06"); } set { this.GenericParam.SetValue("lotItemBasePoint06", value); } }
    public ushort lotItemBasePoint07 { get { return this.GenericParam.GetValue<ushort>("lotItemBasePoint07"); } set { this.GenericParam.SetValue("lotItemBasePoint07", value); } }
    public ushort lotItemBasePoint08 { get { return this.GenericParam.GetValue<ushort>("lotItemBasePoint08"); } set { this.GenericParam.SetValue("lotItemBasePoint08", value); } }
    public ushort cumulateLotPoint01 { get { return this.GenericParam.GetValue<ushort>("cumulateLotPoint01"); } set { this.GenericParam.SetValue("cumulateLotPoint01", value); } }
    public ushort cumulateLotPoint02 { get { return this.GenericParam.GetValue<ushort>("cumulateLotPoint02"); } set { this.GenericParam.SetValue("cumulateLotPoint02", value); } }
    public ushort cumulateLotPoint03 { get { return this.GenericParam.GetValue<ushort>("cumulateLotPoint03"); } set { this.GenericParam.SetValue("cumulateLotPoint03", value); } }
    public ushort cumulateLotPoint04 { get { return this.GenericParam.GetValue<ushort>("cumulateLotPoint04"); } set { this.GenericParam.SetValue("cumulateLotPoint04", value); } }
    public ushort cumulateLotPoint05 { get { return this.GenericParam.GetValue<ushort>("cumulateLotPoint05"); } set { this.GenericParam.SetValue("cumulateLotPoint05", value); } }
    public ushort cumulateLotPoint06 { get { return this.GenericParam.GetValue<ushort>("cumulateLotPoint06"); } set { this.GenericParam.SetValue("cumulateLotPoint06", value); } }
    public ushort cumulateLotPoint07 { get { return this.GenericParam.GetValue<ushort>("cumulateLotPoint07"); } set { this.GenericParam.SetValue("cumulateLotPoint07", value); } }
    public ushort cumulateLotPoint08 { get { return this.GenericParam.GetValue<ushort>("cumulateLotPoint08"); } set { this.GenericParam.SetValue("cumulateLotPoint08", value); } }
    public uint getItemFlagId01 { get { return this.GenericParam.GetValue<uint>("getItemFlagId01"); } set { this.GenericParam.SetValue("getItemFlagId01", value); } }
    public uint getItemFlagId02 { get { return this.GenericParam.GetValue<uint>("getItemFlagId02"); } set { this.GenericParam.SetValue("getItemFlagId02", value); } }
    public uint getItemFlagId03 { get { return this.GenericParam.GetValue<uint>("getItemFlagId03"); } set { this.GenericParam.SetValue("getItemFlagId03", value); } }
    public uint getItemFlagId04 { get { return this.GenericParam.GetValue<uint>("getItemFlagId04"); } set { this.GenericParam.SetValue("getItemFlagId04", value); } }
    public uint getItemFlagId05 { get { return this.GenericParam.GetValue<uint>("getItemFlagId05"); } set { this.GenericParam.SetValue("getItemFlagId05", value); } }
    public uint getItemFlagId06 { get { return this.GenericParam.GetValue<uint>("getItemFlagId06"); } set { this.GenericParam.SetValue("getItemFlagId06", value); } }
    public uint getItemFlagId07 { get { return this.GenericParam.GetValue<uint>("getItemFlagId07"); } set { this.GenericParam.SetValue("getItemFlagId07", value); } }
    public uint getItemFlagId08 { get { return this.GenericParam.GetValue<uint>("getItemFlagId08"); } set { this.GenericParam.SetValue("getItemFlagId08", value); } }
    public uint getItemFlagId { get { return this.GenericParam.GetValue<uint>("getItemFlagId"); } set { this.GenericParam.SetValue("getItemFlagId", value); } }
    public uint cumulateNumFlagId { get { return this.GenericParam.GetValue<uint>("cumulateNumFlagId"); } set { this.GenericParam.SetValue("cumulateNumFlagId", value); } }
    public byte cumulateNumMax { get { return this.GenericParam.GetValue<byte>("cumulateNumMax"); } set { this.GenericParam.SetValue("cumulateNumMax", value); } }
    public sbyte lotItem_Rarity { get { return this.GenericParam.GetValue<sbyte>("lotItem_Rarity"); } set { this.GenericParam.SetValue("lotItem_Rarity", value); } }
    public byte lotItemNum01 { get { return this.GenericParam.GetValue<byte>("lotItemNum01"); } set { this.GenericParam.SetValue("lotItemNum01", value); } }
    public byte lotItemNum02 { get { return this.GenericParam.GetValue<byte>("lotItemNum02"); } set { this.GenericParam.SetValue("lotItemNum02", value); } }
    public byte lotItemNum03 { get { return this.GenericParam.GetValue<byte>("lotItemNum03"); } set { this.GenericParam.SetValue("lotItemNum03", value); } }
    public byte lotItemNum04 { get { return this.GenericParam.GetValue<byte>("lotItemNum04"); } set { this.GenericParam.SetValue("lotItemNum04", value); } }
    public byte lotItemNum05 { get { return this.GenericParam.GetValue<byte>("lotItemNum05"); } set { this.GenericParam.SetValue("lotItemNum05", value); } }
    public byte lotItemNum06 { get { return this.GenericParam.GetValue<byte>("lotItemNum06"); } set { this.GenericParam.SetValue("lotItemNum06", value); } }
    public byte lotItemNum07 { get { return this.GenericParam.GetValue<byte>("lotItemNum07"); } set { this.GenericParam.SetValue("lotItemNum07", value); } }
    public byte lotItemNum08 { get { return this.GenericParam.GetValue<byte>("lotItemNum08"); } set { this.GenericParam.SetValue("lotItemNum08", value); } }
    public ushort enableLuck01 { get { return this.GenericParam.GetValue<ushort>("enableLuck01"); } set { this.GenericParam.SetValue("enableLuck01", value); } }
    public ushort enableLuck02 { get { return this.GenericParam.GetValue<ushort>("enableLuck02"); } set { this.GenericParam.SetValue("enableLuck02", value); } }
    public ushort enableLuck03 { get { return this.GenericParam.GetValue<ushort>("enableLuck03"); } set { this.GenericParam.SetValue("enableLuck03", value); } }
    public ushort enableLuck04 { get { return this.GenericParam.GetValue<ushort>("enableLuck04"); } set { this.GenericParam.SetValue("enableLuck04", value); } }
    public ushort enableLuck05 { get { return this.GenericParam.GetValue<ushort>("enableLuck05"); } set { this.GenericParam.SetValue("enableLuck05", value); } }
    public ushort enableLuck06 { get { return this.GenericParam.GetValue<ushort>("enableLuck06"); } set { this.GenericParam.SetValue("enableLuck06", value); } }
    public ushort enableLuck07 { get { return this.GenericParam.GetValue<ushort>("enableLuck07"); } set { this.GenericParam.SetValue("enableLuck07", value); } }
    public ushort enableLuck08 { get { return this.GenericParam.GetValue<ushort>("enableLuck08"); } set { this.GenericParam.SetValue("enableLuck08", value); } }
    public ushort cumulateReset01 { get { return this.GenericParam.GetValue<ushort>("cumulateReset01"); } set { this.GenericParam.SetValue("cumulateReset01", value); } }
    public ushort cumulateReset02 { get { return this.GenericParam.GetValue<ushort>("cumulateReset02"); } set { this.GenericParam.SetValue("cumulateReset02", value); } }
    public ushort cumulateReset03 { get { return this.GenericParam.GetValue<ushort>("cumulateReset03"); } set { this.GenericParam.SetValue("cumulateReset03", value); } }
    public ushort cumulateReset04 { get { return this.GenericParam.GetValue<ushort>("cumulateReset04"); } set { this.GenericParam.SetValue("cumulateReset04", value); } }
    public ushort cumulateReset05 { get { return this.GenericParam.GetValue<ushort>("cumulateReset05"); } set { this.GenericParam.SetValue("cumulateReset05", value); } }
    public ushort cumulateReset06 { get { return this.GenericParam.GetValue<ushort>("cumulateReset06"); } set { this.GenericParam.SetValue("cumulateReset06", value); } }
    public ushort cumulateReset07 { get { return this.GenericParam.GetValue<ushort>("cumulateReset07"); } set { this.GenericParam.SetValue("cumulateReset07", value); } }
    public ushort cumulateReset08 { get { return this.GenericParam.GetValue<ushort>("cumulateReset08"); } set { this.GenericParam.SetValue("cumulateReset08", value); } }
    public sbyte GameClearOffset { get { return this.GenericParam.GetValue<sbyte>("GameClearOffset"); } set { this.GenericParam.SetValue("GameClearOffset", value); } }
    public byte canExecByFriendlyGhost { get { return this.GenericParam.GetValue<byte>("canExecByFriendlyGhost"); } set { this.GenericParam.SetValue("canExecByFriendlyGhost", value); } }
    public byte canExecByHostileGhost { get { return this.GenericParam.GetValue<byte>("canExecByHostileGhost"); } set { this.GenericParam.SetValue("canExecByHostileGhost", value); } }
    public byte PAD1 { get { return this.GenericParam.GetValue<byte>("PAD1"); } set { this.GenericParam.SetValue("PAD1", value); } }
    public ushort PAD2 { get { return this.GenericParam.GetValue<ushort>("PAD2"); } set { this.GenericParam.SetValue("PAD2", value); } }
}
