using System;

public class NpcParam : ParamBase<NpcParam>
{
    public int ID { get { return this.GenericParam.GetValue<int>("ID"); } set { this.GenericParam.SetValue("ID", value); } }
    public string Name { get { return this.GenericParam.GetValue<string>("Name"); } set { this.GenericParam.SetValue("Name", value); } }
    public byte disableParam_NT { get { return this.GenericParam.GetValue<byte>("disableParam_NT"); } set { this.GenericParam.SetValue("disableParam_NT", value); } }
    public byte disableParamReserve1 { get { return this.GenericParam.GetValue<byte>("disableParamReserve1"); } set { this.GenericParam.SetValue("disableParamReserve1", value); } }
    public byte[] disableParamReserve2 { get { return this.GenericParam.GetValue<byte[]>("disableParamReserve2"); } set { this.GenericParam.SetValue("disableParamReserve2", value); } }
    public int behaviorVariationId { get { return this.GenericParam.GetValue<int>("behaviorVariationId"); } set { this.GenericParam.SetValue("behaviorVariationId", value); } }
    public int resistCorrectId_poison { get { return this.GenericParam.GetValue<int>("resistCorrectId_poison"); } set { this.GenericParam.SetValue("resistCorrectId_poison", value); } }
    public int nameId { get { return this.GenericParam.GetValue<int>("nameId"); } set { this.GenericParam.SetValue("nameId", value); } }
    public float turnVellocity { get { return this.GenericParam.GetValue<float>("turnVellocity"); } set { this.GenericParam.SetValue("turnVellocity", value); } }
    public float hitHeight { get { return this.GenericParam.GetValue<float>("hitHeight"); } set { this.GenericParam.SetValue("hitHeight", value); } }
    public float hitRadius { get { return this.GenericParam.GetValue<float>("hitRadius"); } set { this.GenericParam.SetValue("hitRadius", value); } }
    public uint weight { get { return this.GenericParam.GetValue<uint>("weight"); } set { this.GenericParam.SetValue("weight", value); } }
    public float hitYOffset { get { return this.GenericParam.GetValue<float>("hitYOffset"); } set { this.GenericParam.SetValue("hitYOffset", value); } }
    public uint hp { get { return this.GenericParam.GetValue<uint>("hp"); } set { this.GenericParam.SetValue("hp", value); } }
    public uint mp { get { return this.GenericParam.GetValue<uint>("mp"); } set { this.GenericParam.SetValue("mp", value); } }
    public uint getSoul { get { return this.GenericParam.GetValue<uint>("getSoul"); } set { this.GenericParam.SetValue("getSoul", value); } }
    public int itemLotId_enemy { get { return this.GenericParam.GetValue<int>("itemLotId_enemy"); } set { this.GenericParam.SetValue("itemLotId_enemy", value); } }
    public int itemLotId_map { get { return this.GenericParam.GetValue<int>("itemLotId_map"); } set { this.GenericParam.SetValue("itemLotId_map", value); } }
    public float maxAnkleRollAngle { get { return this.GenericParam.GetValue<float>("maxAnkleRollAngle"); } set { this.GenericParam.SetValue("maxAnkleRollAngle", value); } }
    public byte chrHitGroupAndNavimesh { get { return this.GenericParam.GetValue<byte>("chrHitGroupAndNavimesh"); } set { this.GenericParam.SetValue("chrHitGroupAndNavimesh", value); } }
    public byte faceIconId { get { return this.GenericParam.GetValue<byte>("faceIconId"); } set { this.GenericParam.SetValue("faceIconId", value); } }
    public short deactivateDist { get { return this.GenericParam.GetValue<short>("deactivateDist"); } set { this.GenericParam.SetValue("deactivateDist", value); } }
    public uint chrActivateConditionParamId { get { return this.GenericParam.GetValue<uint>("chrActivateConditionParamId"); } set { this.GenericParam.SetValue("chrActivateConditionParamId", value); } }
    public float footIkErrorHeightLimit { get { return this.GenericParam.GetValue<float>("footIkErrorHeightLimit"); } set { this.GenericParam.SetValue("footIkErrorHeightLimit", value); } }
    public int humanityLotId { get { return this.GenericParam.GetValue<int>("humanityLotId"); } set { this.GenericParam.SetValue("humanityLotId", value); } }
    public int spEffectID0 { get { return this.GenericParam.GetValue<int>("spEffectID0"); } set { this.GenericParam.SetValue("spEffectID0", value); } }
    public int spEffectID1 { get { return this.GenericParam.GetValue<int>("spEffectID1"); } set { this.GenericParam.SetValue("spEffectID1", value); } }
    public int spEffectID2 { get { return this.GenericParam.GetValue<int>("spEffectID2"); } set { this.GenericParam.SetValue("spEffectID2", value); } }
    public int spEffectID3 { get { return this.GenericParam.GetValue<int>("spEffectID3"); } set { this.GenericParam.SetValue("spEffectID3", value); } }
    public int spEffectID4 { get { return this.GenericParam.GetValue<int>("spEffectID4"); } set { this.GenericParam.SetValue("spEffectID4", value); } }
    public int spEffectID5 { get { return this.GenericParam.GetValue<int>("spEffectID5"); } set { this.GenericParam.SetValue("spEffectID5", value); } }
    public int spEffectID6 { get { return this.GenericParam.GetValue<int>("spEffectID6"); } set { this.GenericParam.SetValue("spEffectID6", value); } }
    public int spEffectID7 { get { return this.GenericParam.GetValue<int>("spEffectID7"); } set { this.GenericParam.SetValue("spEffectID7", value); } }
    public int GameClearSpEffectID { get { return this.GenericParam.GetValue<int>("GameClearSpEffectID"); } set { this.GenericParam.SetValue("GameClearSpEffectID", value); } }
    public float physGuardCutRate { get { return this.GenericParam.GetValue<float>("physGuardCutRate"); } set { this.GenericParam.SetValue("physGuardCutRate", value); } }
    public float magGuardCutRate { get { return this.GenericParam.GetValue<float>("magGuardCutRate"); } set { this.GenericParam.SetValue("magGuardCutRate", value); } }
    public float fireGuardCutRate { get { return this.GenericParam.GetValue<float>("fireGuardCutRate"); } set { this.GenericParam.SetValue("fireGuardCutRate", value); } }
    public float thunGuardCutRate { get { return this.GenericParam.GetValue<float>("thunGuardCutRate"); } set { this.GenericParam.SetValue("thunGuardCutRate", value); } }
    public int animIdOffset { get { return this.GenericParam.GetValue<int>("animIdOffset"); } set { this.GenericParam.SetValue("animIdOffset", value); } }
    public short lockGazePoint0 { get { return this.GenericParam.GetValue<short>("lockGazePoint0"); } set { this.GenericParam.SetValue("lockGazePoint0", value); } }
    public short lockGazePoint1 { get { return this.GenericParam.GetValue<short>("lockGazePoint1"); } set { this.GenericParam.SetValue("lockGazePoint1", value); } }
    public short lockGazePoint2 { get { return this.GenericParam.GetValue<short>("lockGazePoint2"); } set { this.GenericParam.SetValue("lockGazePoint2", value); } }
    public short lockGazePoint3 { get { return this.GenericParam.GetValue<short>("lockGazePoint3"); } set { this.GenericParam.SetValue("lockGazePoint3", value); } }
    public short lockGazePoint4 { get { return this.GenericParam.GetValue<short>("lockGazePoint4"); } set { this.GenericParam.SetValue("lockGazePoint4", value); } }
    public short lockGazePoint5 { get { return this.GenericParam.GetValue<short>("lockGazePoint5"); } set { this.GenericParam.SetValue("lockGazePoint5", value); } }
    public float networkWarpDist { get { return this.GenericParam.GetValue<float>("networkWarpDist"); } set { this.GenericParam.SetValue("networkWarpDist", value); } }
    public int dbgBehaviorR1 { get { return this.GenericParam.GetValue<int>("dbgBehaviorR1"); } set { this.GenericParam.SetValue("dbgBehaviorR1", value); } }
    public int dbgBehaviorL1 { get { return this.GenericParam.GetValue<int>("dbgBehaviorL1"); } set { this.GenericParam.SetValue("dbgBehaviorL1", value); } }
    public int dbgBehaviorR2 { get { return this.GenericParam.GetValue<int>("dbgBehaviorR2"); } set { this.GenericParam.SetValue("dbgBehaviorR2", value); } }
    public int dbgBehaviorL2 { get { return this.GenericParam.GetValue<int>("dbgBehaviorL2"); } set { this.GenericParam.SetValue("dbgBehaviorL2", value); } }
    public int dbgBehaviorRL { get { return this.GenericParam.GetValue<int>("dbgBehaviorRL"); } set { this.GenericParam.SetValue("dbgBehaviorRL", value); } }
    public int dbgBehaviorRR { get { return this.GenericParam.GetValue<int>("dbgBehaviorRR"); } set { this.GenericParam.SetValue("dbgBehaviorRR", value); } }
    public int dbgBehaviorRD { get { return this.GenericParam.GetValue<int>("dbgBehaviorRD"); } set { this.GenericParam.SetValue("dbgBehaviorRD", value); } }
    public int dbgBehaviorRU { get { return this.GenericParam.GetValue<int>("dbgBehaviorRU"); } set { this.GenericParam.SetValue("dbgBehaviorRU", value); } }
    public int dbgBehaviorLL { get { return this.GenericParam.GetValue<int>("dbgBehaviorLL"); } set { this.GenericParam.SetValue("dbgBehaviorLL", value); } }
    public int dbgBehaviorLR { get { return this.GenericParam.GetValue<int>("dbgBehaviorLR"); } set { this.GenericParam.SetValue("dbgBehaviorLR", value); } }
    public int dbgBehaviorLD { get { return this.GenericParam.GetValue<int>("dbgBehaviorLD"); } set { this.GenericParam.SetValue("dbgBehaviorLD", value); } }
    public int dbgBehaviorLU { get { return this.GenericParam.GetValue<int>("dbgBehaviorLU"); } set { this.GenericParam.SetValue("dbgBehaviorLU", value); } }
    public int animIdOffset2 { get { return this.GenericParam.GetValue<int>("animIdOffset2"); } set { this.GenericParam.SetValue("animIdOffset2", value); } }
    public float partsDamageRate1 { get { return this.GenericParam.GetValue<float>("partsDamageRate1"); } set { this.GenericParam.SetValue("partsDamageRate1", value); } }
    public float partsDamageRate2 { get { return this.GenericParam.GetValue<float>("partsDamageRate2"); } set { this.GenericParam.SetValue("partsDamageRate2", value); } }
    public float partsDamageRate3 { get { return this.GenericParam.GetValue<float>("partsDamageRate3"); } set { this.GenericParam.SetValue("partsDamageRate3", value); } }
    public float partsDamageRate4 { get { return this.GenericParam.GetValue<float>("partsDamageRate4"); } set { this.GenericParam.SetValue("partsDamageRate4", value); } }
    public float partsDamageRate5 { get { return this.GenericParam.GetValue<float>("partsDamageRate5"); } set { this.GenericParam.SetValue("partsDamageRate5", value); } }
    public float partsDamageRate6 { get { return this.GenericParam.GetValue<float>("partsDamageRate6"); } set { this.GenericParam.SetValue("partsDamageRate6", value); } }
    public float partsDamageRate7 { get { return this.GenericParam.GetValue<float>("partsDamageRate7"); } set { this.GenericParam.SetValue("partsDamageRate7", value); } }
    public float partsDamageRate8 { get { return this.GenericParam.GetValue<float>("partsDamageRate8"); } set { this.GenericParam.SetValue("partsDamageRate8", value); } }
    public float weakPartsDamageRate { get { return this.GenericParam.GetValue<float>("weakPartsDamageRate"); } set { this.GenericParam.SetValue("weakPartsDamageRate", value); } }
    public float superArmorRecoverCorrection { get { return this.GenericParam.GetValue<float>("superArmorRecoverCorrection"); } set { this.GenericParam.SetValue("superArmorRecoverCorrection", value); } }
    public float superArmorBrakeKnockbackDist { get { return this.GenericParam.GetValue<float>("superArmorBrakeKnockbackDist"); } set { this.GenericParam.SetValue("superArmorBrakeKnockbackDist", value); } }
    public ushort stamina { get { return this.GenericParam.GetValue<ushort>("stamina"); } set { this.GenericParam.SetValue("stamina", value); } }
    public ushort staminaRecoverBaseVel { get { return this.GenericParam.GetValue<ushort>("staminaRecoverBaseVel"); } set { this.GenericParam.SetValue("staminaRecoverBaseVel", value); } }
    public ushort def_phys { get { return this.GenericParam.GetValue<ushort>("def_phys"); } set { this.GenericParam.SetValue("def_phys", value); } }
    public short def_slash { get { return this.GenericParam.GetValue<short>("def_slash"); } set { this.GenericParam.SetValue("def_slash", value); } }
    public short def_blow { get { return this.GenericParam.GetValue<short>("def_blow"); } set { this.GenericParam.SetValue("def_blow", value); } }
    public short def_thrust { get { return this.GenericParam.GetValue<short>("def_thrust"); } set { this.GenericParam.SetValue("def_thrust", value); } }
    public ushort def_mag { get { return this.GenericParam.GetValue<ushort>("def_mag"); } set { this.GenericParam.SetValue("def_mag", value); } }
    public ushort def_fire { get { return this.GenericParam.GetValue<ushort>("def_fire"); } set { this.GenericParam.SetValue("def_fire", value); } }
    public ushort def_thunder { get { return this.GenericParam.GetValue<ushort>("def_thunder"); } set { this.GenericParam.SetValue("def_thunder", value); } }
    public ushort defFlickPower { get { return this.GenericParam.GetValue<ushort>("defFlickPower"); } set { this.GenericParam.SetValue("defFlickPower", value); } }
    public ushort resist_poison { get { return this.GenericParam.GetValue<ushort>("resist_poison"); } set { this.GenericParam.SetValue("resist_poison", value); } }
    public ushort resist_desease { get { return this.GenericParam.GetValue<ushort>("resist_desease"); } set { this.GenericParam.SetValue("resist_desease", value); } }
    public ushort resist_blood { get { return this.GenericParam.GetValue<ushort>("resist_blood"); } set { this.GenericParam.SetValue("resist_blood", value); } }
    public ushort resist_curse { get { return this.GenericParam.GetValue<ushort>("resist_curse"); } set { this.GenericParam.SetValue("resist_curse", value); } }
    public short ghostModelId { get { return this.GenericParam.GetValue<short>("ghostModelId"); } set { this.GenericParam.SetValue("ghostModelId", value); } }
    public short normalChangeResouceId { get { return this.GenericParam.GetValue<short>("normalChangeResouceId"); } set { this.GenericParam.SetValue("normalChangeResouceId", value); } }
    public short guardAngle { get { return this.GenericParam.GetValue<short>("guardAngle"); } set { this.GenericParam.SetValue("guardAngle", value); } }
    public short slashGuardCutRate { get { return this.GenericParam.GetValue<short>("slashGuardCutRate"); } set { this.GenericParam.SetValue("slashGuardCutRate", value); } }
    public short blowGuardCutRate { get { return this.GenericParam.GetValue<short>("blowGuardCutRate"); } set { this.GenericParam.SetValue("blowGuardCutRate", value); } }
    public short thrustGuardCutRate { get { return this.GenericParam.GetValue<short>("thrustGuardCutRate"); } set { this.GenericParam.SetValue("thrustGuardCutRate", value); } }
    public short lockGazePoint6 { get { return this.GenericParam.GetValue<short>("lockGazePoint6"); } set { this.GenericParam.SetValue("lockGazePoint6", value); } }
    public short normalChangeTexChrId { get { return this.GenericParam.GetValue<short>("normalChangeTexChrId"); } set { this.GenericParam.SetValue("normalChangeTexChrId", value); } }
    public ushort dropType { get { return this.GenericParam.GetValue<ushort>("dropType"); } set { this.GenericParam.SetValue("dropType", value); } }
    public byte knockbackRate { get { return this.GenericParam.GetValue<byte>("knockbackRate"); } set { this.GenericParam.SetValue("knockbackRate", value); } }
    public byte knockbackParamId { get { return this.GenericParam.GetValue<byte>("knockbackParamId"); } set { this.GenericParam.SetValue("knockbackParamId", value); } }
    public byte fallDamageDump { get { return this.GenericParam.GetValue<byte>("fallDamageDump"); } set { this.GenericParam.SetValue("fallDamageDump", value); } }
    public byte staminaGuardDef { get { return this.GenericParam.GetValue<byte>("staminaGuardDef"); } set { this.GenericParam.SetValue("staminaGuardDef", value); } }
    public ushort resist_sleep { get { return this.GenericParam.GetValue<ushort>("resist_sleep"); } set { this.GenericParam.SetValue("resist_sleep", value); } }
    public ushort resist_madness { get { return this.GenericParam.GetValue<ushort>("resist_madness"); } set { this.GenericParam.SetValue("resist_madness", value); } }
    public sbyte sleepGuardResist { get { return this.GenericParam.GetValue<sbyte>("sleepGuardResist"); } set { this.GenericParam.SetValue("sleepGuardResist", value); } }
    public sbyte madnessGuardResist { get { return this.GenericParam.GetValue<sbyte>("madnessGuardResist"); } set { this.GenericParam.SetValue("madnessGuardResist", value); } }
    public short lockGazePoint7 { get { return this.GenericParam.GetValue<short>("lockGazePoint7"); } set { this.GenericParam.SetValue("lockGazePoint7", value); } }
    public byte mpRecoverBaseVel { get { return this.GenericParam.GetValue<byte>("mpRecoverBaseVel"); } set { this.GenericParam.SetValue("mpRecoverBaseVel", value); } }
    public byte flickDamageCutRate { get { return this.GenericParam.GetValue<byte>("flickDamageCutRate"); } set { this.GenericParam.SetValue("flickDamageCutRate", value); } }
    public sbyte defaultLodParamId { get { return this.GenericParam.GetValue<sbyte>("defaultLodParamId"); } set { this.GenericParam.SetValue("defaultLodParamId", value); } }
    public sbyte drawType { get { return this.GenericParam.GetValue<sbyte>("drawType"); } set { this.GenericParam.SetValue("drawType", value); } }
    public byte npcType { get { return this.GenericParam.GetValue<byte>("npcType"); } set { this.GenericParam.SetValue("npcType", value); } }
    public byte teamType { get { return this.GenericParam.GetValue<byte>("teamType"); } set { this.GenericParam.SetValue("teamType", value); } }
    public byte moveType { get { return this.GenericParam.GetValue<byte>("moveType"); } set { this.GenericParam.SetValue("moveType", value); } }
    public byte lockDist { get { return this.GenericParam.GetValue<byte>("lockDist"); } set { this.GenericParam.SetValue("lockDist", value); } }
    public ushort materialSe_Weak1 { get { return this.GenericParam.GetValue<ushort>("materialSe_Weak1"); } set { this.GenericParam.SetValue("materialSe_Weak1", value); } }
    public ushort materialSfx_Weak1 { get { return this.GenericParam.GetValue<ushort>("materialSfx_Weak1"); } set { this.GenericParam.SetValue("materialSfx_Weak1", value); } }
    public byte partsDamageType { get { return this.GenericParam.GetValue<byte>("partsDamageType"); } set { this.GenericParam.SetValue("partsDamageType", value); } }
    public byte vowType { get { return this.GenericParam.GetValue<byte>("vowType"); } set { this.GenericParam.SetValue("vowType", value); } }
    public sbyte guardLevel { get { return this.GenericParam.GetValue<sbyte>("guardLevel"); } set { this.GenericParam.SetValue("guardLevel", value); } }
    public byte burnSfxType { get { return this.GenericParam.GetValue<byte>("burnSfxType"); } set { this.GenericParam.SetValue("burnSfxType", value); } }
    public sbyte poisonGuardResist { get { return this.GenericParam.GetValue<sbyte>("poisonGuardResist"); } set { this.GenericParam.SetValue("poisonGuardResist", value); } }
    public sbyte diseaseGuardResist { get { return this.GenericParam.GetValue<sbyte>("diseaseGuardResist"); } set { this.GenericParam.SetValue("diseaseGuardResist", value); } }
    public sbyte bloodGuardResist { get { return this.GenericParam.GetValue<sbyte>("bloodGuardResist"); } set { this.GenericParam.SetValue("bloodGuardResist", value); } }
    public sbyte curseGuardResist { get { return this.GenericParam.GetValue<sbyte>("curseGuardResist"); } set { this.GenericParam.SetValue("curseGuardResist", value); } }
    public byte parryAttack { get { return this.GenericParam.GetValue<byte>("parryAttack"); } set { this.GenericParam.SetValue("parryAttack", value); } }
    public byte parryDefence { get { return this.GenericParam.GetValue<byte>("parryDefence"); } set { this.GenericParam.SetValue("parryDefence", value); } }
    public byte sfxSize { get { return this.GenericParam.GetValue<byte>("sfxSize"); } set { this.GenericParam.SetValue("sfxSize", value); } }
    public byte pushOutCamRegionRadius { get { return this.GenericParam.GetValue<byte>("pushOutCamRegionRadius"); } set { this.GenericParam.SetValue("pushOutCamRegionRadius", value); } }
    public byte hitStopType { get { return this.GenericParam.GetValue<byte>("hitStopType"); } set { this.GenericParam.SetValue("hitStopType", value); } }
    public byte ladderEndChkOffsetTop { get { return this.GenericParam.GetValue<byte>("ladderEndChkOffsetTop"); } set { this.GenericParam.SetValue("ladderEndChkOffsetTop", value); } }
    public byte ladderEndChkOffsetLow { get { return this.GenericParam.GetValue<byte>("ladderEndChkOffsetLow"); } set { this.GenericParam.SetValue("ladderEndChkOffsetLow", value); } }
    public byte useRagdollCamHit { get { return this.GenericParam.GetValue<byte>("useRagdollCamHit"); } set { this.GenericParam.SetValue("useRagdollCamHit", value); } }
    public byte disableClothRigidHit { get { return this.GenericParam.GetValue<byte>("disableClothRigidHit"); } set { this.GenericParam.SetValue("disableClothRigidHit", value); } }
    public byte useUndulationAddAnimFB { get { return this.GenericParam.GetValue<byte>("useUndulationAddAnimFB"); } set { this.GenericParam.SetValue("useUndulationAddAnimFB", value); } }
    public byte isWeakA { get { return this.GenericParam.GetValue<byte>("isWeakA"); } set { this.GenericParam.SetValue("isWeakA", value); } }
    public byte isGhost { get { return this.GenericParam.GetValue<byte>("isGhost"); } set { this.GenericParam.SetValue("isGhost", value); } }
    public byte isNoDamageMotion { get { return this.GenericParam.GetValue<byte>("isNoDamageMotion"); } set { this.GenericParam.SetValue("isNoDamageMotion", value); } }
    public byte isUnduration { get { return this.GenericParam.GetValue<byte>("isUnduration"); } set { this.GenericParam.SetValue("isUnduration", value); } }
    public byte isChangeWanderGhost { get { return this.GenericParam.GetValue<byte>("isChangeWanderGhost"); } set { this.GenericParam.SetValue("isChangeWanderGhost", value); } }
    public byte modelDispMask0 { get { return this.GenericParam.GetValue<byte>("modelDispMask0"); } set { this.GenericParam.SetValue("modelDispMask0", value); } }
    public byte modelDispMask1 { get { return this.GenericParam.GetValue<byte>("modelDispMask1"); } set { this.GenericParam.SetValue("modelDispMask1", value); } }
    public byte modelDispMask2 { get { return this.GenericParam.GetValue<byte>("modelDispMask2"); } set { this.GenericParam.SetValue("modelDispMask2", value); } }
    public byte modelDispMask3 { get { return this.GenericParam.GetValue<byte>("modelDispMask3"); } set { this.GenericParam.SetValue("modelDispMask3", value); } }
    public byte modelDispMask4 { get { return this.GenericParam.GetValue<byte>("modelDispMask4"); } set { this.GenericParam.SetValue("modelDispMask4", value); } }
    public byte modelDispMask5 { get { return this.GenericParam.GetValue<byte>("modelDispMask5"); } set { this.GenericParam.SetValue("modelDispMask5", value); } }
    public byte modelDispMask6 { get { return this.GenericParam.GetValue<byte>("modelDispMask6"); } set { this.GenericParam.SetValue("modelDispMask6", value); } }
    public byte modelDispMask7 { get { return this.GenericParam.GetValue<byte>("modelDispMask7"); } set { this.GenericParam.SetValue("modelDispMask7", value); } }
    public byte modelDispMask8 { get { return this.GenericParam.GetValue<byte>("modelDispMask8"); } set { this.GenericParam.SetValue("modelDispMask8", value); } }
    public byte modelDispMask9 { get { return this.GenericParam.GetValue<byte>("modelDispMask9"); } set { this.GenericParam.SetValue("modelDispMask9", value); } }
    public byte modelDispMask10 { get { return this.GenericParam.GetValue<byte>("modelDispMask10"); } set { this.GenericParam.SetValue("modelDispMask10", value); } }
    public byte modelDispMask11 { get { return this.GenericParam.GetValue<byte>("modelDispMask11"); } set { this.GenericParam.SetValue("modelDispMask11", value); } }
    public byte modelDispMask12 { get { return this.GenericParam.GetValue<byte>("modelDispMask12"); } set { this.GenericParam.SetValue("modelDispMask12", value); } }
    public byte modelDispMask13 { get { return this.GenericParam.GetValue<byte>("modelDispMask13"); } set { this.GenericParam.SetValue("modelDispMask13", value); } }
    public byte modelDispMask14 { get { return this.GenericParam.GetValue<byte>("modelDispMask14"); } set { this.GenericParam.SetValue("modelDispMask14", value); } }
    public byte modelDispMask15 { get { return this.GenericParam.GetValue<byte>("modelDispMask15"); } set { this.GenericParam.SetValue("modelDispMask15", value); } }
    public byte isEnableNeckTurn { get { return this.GenericParam.GetValue<byte>("isEnableNeckTurn"); } set { this.GenericParam.SetValue("isEnableNeckTurn", value); } }
    public byte disableRespawn { get { return this.GenericParam.GetValue<byte>("disableRespawn"); } set { this.GenericParam.SetValue("disableRespawn", value); } }
    public byte isMoveAnimWait { get { return this.GenericParam.GetValue<byte>("isMoveAnimWait"); } set { this.GenericParam.SetValue("isMoveAnimWait", value); } }
    public byte isCrowd { get { return this.GenericParam.GetValue<byte>("isCrowd"); } set { this.GenericParam.SetValue("isCrowd", value); } }
    public byte isWeakB { get { return this.GenericParam.GetValue<byte>("isWeakB"); } set { this.GenericParam.SetValue("isWeakB", value); } }
    public byte isWeakC { get { return this.GenericParam.GetValue<byte>("isWeakC"); } set { this.GenericParam.SetValue("isWeakC", value); } }
    public byte isWeakD { get { return this.GenericParam.GetValue<byte>("isWeakD"); } set { this.GenericParam.SetValue("isWeakD", value); } }
    public byte doesAlwaysUseSpecialTurn { get { return this.GenericParam.GetValue<byte>("doesAlwaysUseSpecialTurn"); } set { this.GenericParam.SetValue("doesAlwaysUseSpecialTurn", value); } }
    public byte isRideAtkTarget { get { return this.GenericParam.GetValue<byte>("isRideAtkTarget"); } set { this.GenericParam.SetValue("isRideAtkTarget", value); } }
    public byte isEnableStepDispInterpolate { get { return this.GenericParam.GetValue<byte>("isEnableStepDispInterpolate"); } set { this.GenericParam.SetValue("isEnableStepDispInterpolate", value); } }
    public byte isStealthTarget { get { return this.GenericParam.GetValue<byte>("isStealthTarget"); } set { this.GenericParam.SetValue("isStealthTarget", value); } }
    public byte disableInitializeDead { get { return this.GenericParam.GetValue<byte>("disableInitializeDead"); } set { this.GenericParam.SetValue("disableInitializeDead", value); } }
    public byte isHitRumble { get { return this.GenericParam.GetValue<byte>("isHitRumble"); } set { this.GenericParam.SetValue("isHitRumble", value); } }
    public byte isSmoothTurn { get { return this.GenericParam.GetValue<byte>("isSmoothTurn"); } set { this.GenericParam.SetValue("isSmoothTurn", value); } }
    public byte isWeakE { get { return this.GenericParam.GetValue<byte>("isWeakE"); } set { this.GenericParam.SetValue("isWeakE", value); } }
    public byte isWeakF { get { return this.GenericParam.GetValue<byte>("isWeakF"); } set { this.GenericParam.SetValue("isWeakF", value); } }
    public byte modelDispMask16 { get { return this.GenericParam.GetValue<byte>("modelDispMask16"); } set { this.GenericParam.SetValue("modelDispMask16", value); } }
    public byte modelDispMask17 { get { return this.GenericParam.GetValue<byte>("modelDispMask17"); } set { this.GenericParam.SetValue("modelDispMask17", value); } }
    public byte modelDispMask18 { get { return this.GenericParam.GetValue<byte>("modelDispMask18"); } set { this.GenericParam.SetValue("modelDispMask18", value); } }
    public byte modelDispMask19 { get { return this.GenericParam.GetValue<byte>("modelDispMask19"); } set { this.GenericParam.SetValue("modelDispMask19", value); } }
    public byte modelDispMask20 { get { return this.GenericParam.GetValue<byte>("modelDispMask20"); } set { this.GenericParam.SetValue("modelDispMask20", value); } }
    public byte modelDispMask21 { get { return this.GenericParam.GetValue<byte>("modelDispMask21"); } set { this.GenericParam.SetValue("modelDispMask21", value); } }
    public byte modelDispMask22 { get { return this.GenericParam.GetValue<byte>("modelDispMask22"); } set { this.GenericParam.SetValue("modelDispMask22", value); } }
    public byte modelDispMask23 { get { return this.GenericParam.GetValue<byte>("modelDispMask23"); } set { this.GenericParam.SetValue("modelDispMask23", value); } }
    public byte modelDispMask24 { get { return this.GenericParam.GetValue<byte>("modelDispMask24"); } set { this.GenericParam.SetValue("modelDispMask24", value); } }
    public byte modelDispMask25 { get { return this.GenericParam.GetValue<byte>("modelDispMask25"); } set { this.GenericParam.SetValue("modelDispMask25", value); } }
    public byte modelDispMask26 { get { return this.GenericParam.GetValue<byte>("modelDispMask26"); } set { this.GenericParam.SetValue("modelDispMask26", value); } }
    public byte modelDispMask27 { get { return this.GenericParam.GetValue<byte>("modelDispMask27"); } set { this.GenericParam.SetValue("modelDispMask27", value); } }
    public byte modelDispMask28 { get { return this.GenericParam.GetValue<byte>("modelDispMask28"); } set { this.GenericParam.SetValue("modelDispMask28", value); } }
    public byte modelDispMask29 { get { return this.GenericParam.GetValue<byte>("modelDispMask29"); } set { this.GenericParam.SetValue("modelDispMask29", value); } }
    public byte modelDispMask30 { get { return this.GenericParam.GetValue<byte>("modelDispMask30"); } set { this.GenericParam.SetValue("modelDispMask30", value); } }
    public byte modelDispMask31 { get { return this.GenericParam.GetValue<byte>("modelDispMask31"); } set { this.GenericParam.SetValue("modelDispMask31", value); } }
    public float itemSearchRadius { get { return this.GenericParam.GetValue<float>("itemSearchRadius"); } set { this.GenericParam.SetValue("itemSearchRadius", value); } }
    public float chrHitHeight { get { return this.GenericParam.GetValue<float>("chrHitHeight"); } set { this.GenericParam.SetValue("chrHitHeight", value); } }
    public float chrHitRadius { get { return this.GenericParam.GetValue<float>("chrHitRadius"); } set { this.GenericParam.SetValue("chrHitRadius", value); } }
    public byte specialTurnType { get { return this.GenericParam.GetValue<byte>("specialTurnType"); } set { this.GenericParam.SetValue("specialTurnType", value); } }
    public byte isSoulGetByBoss { get { return this.GenericParam.GetValue<byte>("isSoulGetByBoss"); } set { this.GenericParam.SetValue("isSoulGetByBoss", value); } }
    public byte isBulletOwner_byObject { get { return this.GenericParam.GetValue<byte>("isBulletOwner_byObject"); } set { this.GenericParam.SetValue("isBulletOwner_byObject", value); } }
    public byte isUseLowHitFootIk { get { return this.GenericParam.GetValue<byte>("isUseLowHitFootIk"); } set { this.GenericParam.SetValue("isUseLowHitFootIk", value); } }
    public byte isCalculatePvPDamage { get { return this.GenericParam.GetValue<byte>("isCalculatePvPDamage"); } set { this.GenericParam.SetValue("isCalculatePvPDamage", value); } }
    public byte isHostSyncChr { get { return this.GenericParam.GetValue<byte>("isHostSyncChr"); } set { this.GenericParam.SetValue("isHostSyncChr", value); } }
    public byte isSkipWeakDamageAnim { get { return this.GenericParam.GetValue<byte>("isSkipWeakDamageAnim"); } set { this.GenericParam.SetValue("isSkipWeakDamageAnim", value); } }
    public byte isKeepHitOnRide { get { return this.GenericParam.GetValue<byte>("isKeepHitOnRide"); } set { this.GenericParam.SetValue("isKeepHitOnRide", value); } }
    public byte isSpCollide { get { return this.GenericParam.GetValue<byte>("isSpCollide"); } set { this.GenericParam.SetValue("isSpCollide", value); } }
    public ushort def_dark { get { return this.GenericParam.GetValue<ushort>("def_dark"); } set { this.GenericParam.SetValue("def_dark", value); } }
    public uint threatLv { get { return this.GenericParam.GetValue<uint>("threatLv"); } set { this.GenericParam.SetValue("threatLv", value); } }
    public float specialTurnDistanceThreshold { get { return this.GenericParam.GetValue<float>("specialTurnDistanceThreshold"); } set { this.GenericParam.SetValue("specialTurnDistanceThreshold", value); } }
    public int autoFootEffectSfxId { get { return this.GenericParam.GetValue<int>("autoFootEffectSfxId"); } set { this.GenericParam.SetValue("autoFootEffectSfxId", value); } }
    public ushort materialSe1 { get { return this.GenericParam.GetValue<ushort>("materialSe1"); } set { this.GenericParam.SetValue("materialSe1", value); } }
    public ushort materialSfx1 { get { return this.GenericParam.GetValue<ushort>("materialSfx1"); } set { this.GenericParam.SetValue("materialSfx1", value); } }
    public ushort materialSe_Weak2 { get { return this.GenericParam.GetValue<ushort>("materialSe_Weak2"); } set { this.GenericParam.SetValue("materialSe_Weak2", value); } }
    public ushort materialSfx_Weak2 { get { return this.GenericParam.GetValue<ushort>("materialSfx_Weak2"); } set { this.GenericParam.SetValue("materialSfx_Weak2", value); } }
    public ushort materialSe2 { get { return this.GenericParam.GetValue<ushort>("materialSe2"); } set { this.GenericParam.SetValue("materialSe2", value); } }
    public ushort materialSfx2 { get { return this.GenericParam.GetValue<ushort>("materialSfx2"); } set { this.GenericParam.SetValue("materialSfx2", value); } }
    public int spEffectID8 { get { return this.GenericParam.GetValue<int>("spEffectID8"); } set { this.GenericParam.SetValue("spEffectID8", value); } }
    public int spEffectID9 { get { return this.GenericParam.GetValue<int>("spEffectID9"); } set { this.GenericParam.SetValue("spEffectID9", value); } }
    public int spEffectID10 { get { return this.GenericParam.GetValue<int>("spEffectID10"); } set { this.GenericParam.SetValue("spEffectID10", value); } }
    public int spEffectID11 { get { return this.GenericParam.GetValue<int>("spEffectID11"); } set { this.GenericParam.SetValue("spEffectID11", value); } }
    public int spEffectID12 { get { return this.GenericParam.GetValue<int>("spEffectID12"); } set { this.GenericParam.SetValue("spEffectID12", value); } }
    public int spEffectID13 { get { return this.GenericParam.GetValue<int>("spEffectID13"); } set { this.GenericParam.SetValue("spEffectID13", value); } }
    public int spEffectID14 { get { return this.GenericParam.GetValue<int>("spEffectID14"); } set { this.GenericParam.SetValue("spEffectID14", value); } }
    public int spEffectID15 { get { return this.GenericParam.GetValue<int>("spEffectID15"); } set { this.GenericParam.SetValue("spEffectID15", value); } }
    public int autoFootEffectDecalBaseId1 { get { return this.GenericParam.GetValue<int>("autoFootEffectDecalBaseId1"); } set { this.GenericParam.SetValue("autoFootEffectDecalBaseId1", value); } }
    public uint toughness { get { return this.GenericParam.GetValue<uint>("toughness"); } set { this.GenericParam.SetValue("toughness", value); } }
    public float toughnessRecoverCorrection { get { return this.GenericParam.GetValue<float>("toughnessRecoverCorrection"); } set { this.GenericParam.SetValue("toughnessRecoverCorrection", value); } }
    public float neutralDamageCutRate { get { return this.GenericParam.GetValue<float>("neutralDamageCutRate"); } set { this.GenericParam.SetValue("neutralDamageCutRate", value); } }
    public float slashDamageCutRate { get { return this.GenericParam.GetValue<float>("slashDamageCutRate"); } set { this.GenericParam.SetValue("slashDamageCutRate", value); } }
    public float blowDamageCutRate { get { return this.GenericParam.GetValue<float>("blowDamageCutRate"); } set { this.GenericParam.SetValue("blowDamageCutRate", value); } }
    public float thrustDamageCutRate { get { return this.GenericParam.GetValue<float>("thrustDamageCutRate"); } set { this.GenericParam.SetValue("thrustDamageCutRate", value); } }
    public float magicDamageCutRate { get { return this.GenericParam.GetValue<float>("magicDamageCutRate"); } set { this.GenericParam.SetValue("magicDamageCutRate", value); } }
    public float fireDamageCutRate { get { return this.GenericParam.GetValue<float>("fireDamageCutRate"); } set { this.GenericParam.SetValue("fireDamageCutRate", value); } }
    public float thunderDamageCutRate { get { return this.GenericParam.GetValue<float>("thunderDamageCutRate"); } set { this.GenericParam.SetValue("thunderDamageCutRate", value); } }
    public float darkDamageCutRate { get { return this.GenericParam.GetValue<float>("darkDamageCutRate"); } set { this.GenericParam.SetValue("darkDamageCutRate", value); } }
    public float darkGuardCutRate { get { return this.GenericParam.GetValue<float>("darkGuardCutRate"); } set { this.GenericParam.SetValue("darkGuardCutRate", value); } }
    public sbyte clothUpdateOffset { get { return this.GenericParam.GetValue<sbyte>("clothUpdateOffset"); } set { this.GenericParam.SetValue("clothUpdateOffset", value); } }
    public byte npcPlayerWeightType { get { return this.GenericParam.GetValue<byte>("npcPlayerWeightType"); } set { this.GenericParam.SetValue("npcPlayerWeightType", value); } }
    public short normalChangeModelId { get { return this.GenericParam.GetValue<short>("normalChangeModelId"); } set { this.GenericParam.SetValue("normalChangeModelId", value); } }
    public short normalChangeAnimChrId { get { return this.GenericParam.GetValue<short>("normalChangeAnimChrId"); } set { this.GenericParam.SetValue("normalChangeAnimChrId", value); } }
    public ushort paintRenderTargetSize { get { return this.GenericParam.GetValue<ushort>("paintRenderTargetSize"); } set { this.GenericParam.SetValue("paintRenderTargetSize", value); } }
    public int resistCorrectId_disease { get { return this.GenericParam.GetValue<int>("resistCorrectId_disease"); } set { this.GenericParam.SetValue("resistCorrectId_disease", value); } }
    public int phantomShaderId { get { return this.GenericParam.GetValue<int>("phantomShaderId"); } set { this.GenericParam.SetValue("phantomShaderId", value); } }
    public int multiPlayCorrectionParamId { get { return this.GenericParam.GetValue<int>("multiPlayCorrectionParamId"); } set { this.GenericParam.SetValue("multiPlayCorrectionParamId", value); } }
    public float maxAnklePitchAngle { get { return this.GenericParam.GetValue<float>("maxAnklePitchAngle"); } set { this.GenericParam.SetValue("maxAnklePitchAngle", value); } }
    public ushort resist_freeze { get { return this.GenericParam.GetValue<ushort>("resist_freeze"); } set { this.GenericParam.SetValue("resist_freeze", value); } }
    public sbyte freezeGuardResist { get { return this.GenericParam.GetValue<sbyte>("freezeGuardResist"); } set { this.GenericParam.SetValue("freezeGuardResist", value); } }
    public byte hpBurnDamageRate { get { return this.GenericParam.GetValue<byte>("hpBurnDamageRate"); } set { this.GenericParam.SetValue("hpBurnDamageRate", value); } }
    public int lockCameraParamId { get { return this.GenericParam.GetValue<int>("lockCameraParamId"); } set { this.GenericParam.SetValue("lockCameraParamId", value); } }
    public int spEffectID16 { get { return this.GenericParam.GetValue<int>("spEffectID16"); } set { this.GenericParam.SetValue("spEffectID16", value); } }
    public int spEffectID17 { get { return this.GenericParam.GetValue<int>("spEffectID17"); } set { this.GenericParam.SetValue("spEffectID17", value); } }
    public int spEffectID18 { get { return this.GenericParam.GetValue<int>("spEffectID18"); } set { this.GenericParam.SetValue("spEffectID18", value); } }
    public int spEffectID19 { get { return this.GenericParam.GetValue<int>("spEffectID19"); } set { this.GenericParam.SetValue("spEffectID19", value); } }
    public int spEffectID20 { get { return this.GenericParam.GetValue<int>("spEffectID20"); } set { this.GenericParam.SetValue("spEffectID20", value); } }
    public int spEffectID21 { get { return this.GenericParam.GetValue<int>("spEffectID21"); } set { this.GenericParam.SetValue("spEffectID21", value); } }
    public int spEffectID22 { get { return this.GenericParam.GetValue<int>("spEffectID22"); } set { this.GenericParam.SetValue("spEffectID22", value); } }
    public int spEffectID23 { get { return this.GenericParam.GetValue<int>("spEffectID23"); } set { this.GenericParam.SetValue("spEffectID23", value); } }
    public int spEffectID24 { get { return this.GenericParam.GetValue<int>("spEffectID24"); } set { this.GenericParam.SetValue("spEffectID24", value); } }
    public int spEffectID25 { get { return this.GenericParam.GetValue<int>("spEffectID25"); } set { this.GenericParam.SetValue("spEffectID25", value); } }
    public int spEffectID26 { get { return this.GenericParam.GetValue<int>("spEffectID26"); } set { this.GenericParam.SetValue("spEffectID26", value); } }
    public int spEffectID27 { get { return this.GenericParam.GetValue<int>("spEffectID27"); } set { this.GenericParam.SetValue("spEffectID27", value); } }
    public int spEffectID28 { get { return this.GenericParam.GetValue<int>("spEffectID28"); } set { this.GenericParam.SetValue("spEffectID28", value); } }
    public int spEffectID29 { get { return this.GenericParam.GetValue<int>("spEffectID29"); } set { this.GenericParam.SetValue("spEffectID29", value); } }
    public int spEffectID30 { get { return this.GenericParam.GetValue<int>("spEffectID30"); } set { this.GenericParam.SetValue("spEffectID30", value); } }
    public int spEffectID31 { get { return this.GenericParam.GetValue<int>("spEffectID31"); } set { this.GenericParam.SetValue("spEffectID31", value); } }
    public float disableLockOnAng { get { return this.GenericParam.GetValue<float>("disableLockOnAng"); } set { this.GenericParam.SetValue("disableLockOnAng", value); } }
    public sbyte clothOffLodLevel { get { return this.GenericParam.GetValue<sbyte>("clothOffLodLevel"); } set { this.GenericParam.SetValue("clothOffLodLevel", value); } }
    public byte isUseFootIKNormalByUnduration { get { return this.GenericParam.GetValue<byte>("isUseFootIKNormalByUnduration"); } set { this.GenericParam.SetValue("isUseFootIKNormalByUnduration", value); } }
    public byte attachHitInitializeDead { get { return this.GenericParam.GetValue<byte>("attachHitInitializeDead"); } set { this.GenericParam.SetValue("attachHitInitializeDead", value); } }
    public byte excludeGroupRewardCheck { get { return this.GenericParam.GetValue<byte>("excludeGroupRewardCheck"); } set { this.GenericParam.SetValue("excludeGroupRewardCheck", value); } }
    public byte enableAILockDmyPoly_212 { get { return this.GenericParam.GetValue<byte>("enableAILockDmyPoly_212"); } set { this.GenericParam.SetValue("enableAILockDmyPoly_212", value); } }
    public byte enableAILockDmyPoly_213 { get { return this.GenericParam.GetValue<byte>("enableAILockDmyPoly_213"); } set { this.GenericParam.SetValue("enableAILockDmyPoly_213", value); } }
    public byte enableAILockDmyPoly_214 { get { return this.GenericParam.GetValue<byte>("enableAILockDmyPoly_214"); } set { this.GenericParam.SetValue("enableAILockDmyPoly_214", value); } }
    public byte disableActivateOpen_xb1 { get { return this.GenericParam.GetValue<byte>("disableActivateOpen_xb1"); } set { this.GenericParam.SetValue("disableActivateOpen_xb1", value); } }
    public byte disableActivateLegacy_xb1 { get { return this.GenericParam.GetValue<byte>("disableActivateLegacy_xb1"); } set { this.GenericParam.SetValue("disableActivateLegacy_xb1", value); } }
    public short estusFlaskRecoveryParamId { get { return this.GenericParam.GetValue<short>("estusFlaskRecoveryParamId"); } set { this.GenericParam.SetValue("estusFlaskRecoveryParamId", value); } }
    public int roleNameId { get { return this.GenericParam.GetValue<int>("roleNameId"); } set { this.GenericParam.SetValue("roleNameId", value); } }
    public ushort estusFlaskLotPoint { get { return this.GenericParam.GetValue<ushort>("estusFlaskLotPoint"); } set { this.GenericParam.SetValue("estusFlaskLotPoint", value); } }
    public ushort hpEstusFlaskLotPoint { get { return this.GenericParam.GetValue<ushort>("hpEstusFlaskLotPoint"); } set { this.GenericParam.SetValue("hpEstusFlaskLotPoint", value); } }
    public ushort mpEstusFlaskLotPoint { get { return this.GenericParam.GetValue<ushort>("mpEstusFlaskLotPoint"); } set { this.GenericParam.SetValue("mpEstusFlaskLotPoint", value); } }
    public ushort estusFlaskRecovery_failedLotPointAdd { get { return this.GenericParam.GetValue<ushort>("estusFlaskRecovery_failedLotPointAdd"); } set { this.GenericParam.SetValue("estusFlaskRecovery_failedLotPointAdd", value); } }
    public ushort hpEstusFlaskRecovery_failedLotPointAdd { get { return this.GenericParam.GetValue<ushort>("hpEstusFlaskRecovery_failedLotPointAdd"); } set { this.GenericParam.SetValue("hpEstusFlaskRecovery_failedLotPointAdd", value); } }
    public ushort mpEstusFlaskRecovery_failedLotPointAdd { get { return this.GenericParam.GetValue<ushort>("mpEstusFlaskRecovery_failedLotPointAdd"); } set { this.GenericParam.SetValue("mpEstusFlaskRecovery_failedLotPointAdd", value); } }
    public int WanderGhostPhantomId { get { return this.GenericParam.GetValue<int>("WanderGhostPhantomId"); } set { this.GenericParam.SetValue("WanderGhostPhantomId", value); } }
    public float hearingHeadSize { get { return this.GenericParam.GetValue<float>("hearingHeadSize"); } set { this.GenericParam.SetValue("hearingHeadSize", value); } }
    public short SoundBankId { get { return this.GenericParam.GetValue<short>("SoundBankId"); } set { this.GenericParam.SetValue("SoundBankId", value); } }
    public byte forwardUndulationLimit { get { return this.GenericParam.GetValue<byte>("forwardUndulationLimit"); } set { this.GenericParam.SetValue("forwardUndulationLimit", value); } }
    public byte sideUndulationLimit { get { return this.GenericParam.GetValue<byte>("sideUndulationLimit"); } set { this.GenericParam.SetValue("sideUndulationLimit", value); } }
    public float deactiveMoveSpeed { get { return this.GenericParam.GetValue<float>("deactiveMoveSpeed"); } set { this.GenericParam.SetValue("deactiveMoveSpeed", value); } }
    public float deactiveMoveDist { get { return this.GenericParam.GetValue<float>("deactiveMoveDist"); } set { this.GenericParam.SetValue("deactiveMoveDist", value); } }
    public float enableSoundObjDist { get { return this.GenericParam.GetValue<float>("enableSoundObjDist"); } set { this.GenericParam.SetValue("enableSoundObjDist", value); } }
    public float undulationCorrectGain { get { return this.GenericParam.GetValue<float>("undulationCorrectGain"); } set { this.GenericParam.SetValue("undulationCorrectGain", value); } }
    public short autoFootEffectDecalBaseId2 { get { return this.GenericParam.GetValue<short>("autoFootEffectDecalBaseId2"); } set { this.GenericParam.SetValue("autoFootEffectDecalBaseId2", value); } }
    public short autoFootEffectDecalBaseId3 { get { return this.GenericParam.GetValue<short>("autoFootEffectDecalBaseId3"); } set { this.GenericParam.SetValue("autoFootEffectDecalBaseId3", value); } }
    public short RetargetReferenceChrId { get { return this.GenericParam.GetValue<short>("RetargetReferenceChrId"); } set { this.GenericParam.SetValue("RetargetReferenceChrId", value); } }
    public short SfxResBankId { get { return this.GenericParam.GetValue<short>("SfxResBankId"); } set { this.GenericParam.SetValue("SfxResBankId", value); } }
    public float updateActivatePriolity { get { return this.GenericParam.GetValue<float>("updateActivatePriolity"); } set { this.GenericParam.SetValue("updateActivatePriolity", value); } }
    public byte chrNavimeshFlag_Alive { get { return this.GenericParam.GetValue<byte>("chrNavimeshFlag_Alive"); } set { this.GenericParam.SetValue("chrNavimeshFlag_Alive", value); } }
    public byte chrNavimeshFlag_Dead { get { return this.GenericParam.GetValue<byte>("chrNavimeshFlag_Dead"); } set { this.GenericParam.SetValue("chrNavimeshFlag_Dead", value); } }
    public byte isConsideredUndead { get { return this.GenericParam.GetValue<byte>("isConsideredUndead"); } set { this.GenericParam.SetValue("isConsideredUndead", value); } }
    public byte wheelRotType { get { return this.GenericParam.GetValue<byte>("wheelRotType"); } set { this.GenericParam.SetValue("wheelRotType", value); } }
    public float wheelRotRadius { get { return this.GenericParam.GetValue<float>("wheelRotRadius"); } set { this.GenericParam.SetValue("wheelRotRadius", value); } }
    public float retargetMoveRate { get { return this.GenericParam.GetValue<float>("retargetMoveRate"); } set { this.GenericParam.SetValue("retargetMoveRate", value); } }
    public float ladderWarpOffset { get { return this.GenericParam.GetValue<float>("ladderWarpOffset"); } set { this.GenericParam.SetValue("ladderWarpOffset", value); } }
    public int loadAssetId { get { return this.GenericParam.GetValue<int>("loadAssetId"); } set { this.GenericParam.SetValue("loadAssetId", value); } }
    public int overlapCameraDmypolyId { get { return this.GenericParam.GetValue<int>("overlapCameraDmypolyId"); } set { this.GenericParam.SetValue("overlapCameraDmypolyId", value); } }
    public int residentMaterialExParamId00 { get { return this.GenericParam.GetValue<int>("residentMaterialExParamId00"); } set { this.GenericParam.SetValue("residentMaterialExParamId00", value); } }
    public int residentMaterialExParamId01 { get { return this.GenericParam.GetValue<int>("residentMaterialExParamId01"); } set { this.GenericParam.SetValue("residentMaterialExParamId01", value); } }
    public int residentMaterialExParamId02 { get { return this.GenericParam.GetValue<int>("residentMaterialExParamId02"); } set { this.GenericParam.SetValue("residentMaterialExParamId02", value); } }
    public int residentMaterialExParamId03 { get { return this.GenericParam.GetValue<int>("residentMaterialExParamId03"); } set { this.GenericParam.SetValue("residentMaterialExParamId03", value); } }
    public int residentMaterialExParamId04 { get { return this.GenericParam.GetValue<int>("residentMaterialExParamId04"); } set { this.GenericParam.SetValue("residentMaterialExParamId04", value); } }
    public int sleepCollectorItemLotId_enemy { get { return this.GenericParam.GetValue<int>("sleepCollectorItemLotId_enemy"); } set { this.GenericParam.SetValue("sleepCollectorItemLotId_enemy", value); } }
    public int sleepCollectorItemLotId_map { get { return this.GenericParam.GetValue<int>("sleepCollectorItemLotId_map"); } set { this.GenericParam.SetValue("sleepCollectorItemLotId_map", value); } }
    public float footIkErrorOnGain { get { return this.GenericParam.GetValue<float>("footIkErrorOnGain"); } set { this.GenericParam.SetValue("footIkErrorOnGain", value); } }
    public float footIkErrorOffGain { get { return this.GenericParam.GetValue<float>("footIkErrorOffGain"); } set { this.GenericParam.SetValue("footIkErrorOffGain", value); } }
    public short SoundAddBankId { get { return this.GenericParam.GetValue<short>("SoundAddBankId"); } set { this.GenericParam.SetValue("SoundAddBankId", value); } }
    public byte materialVariationValue { get { return this.GenericParam.GetValue<byte>("materialVariationValue"); } set { this.GenericParam.SetValue("materialVariationValue", value); } }
    public byte materialVariationValue_Weak { get { return this.GenericParam.GetValue<byte>("materialVariationValue_Weak"); } set { this.GenericParam.SetValue("materialVariationValue_Weak", value); } }
    public float superArmorDurability { get { return this.GenericParam.GetValue<float>("superArmorDurability"); } set { this.GenericParam.SetValue("superArmorDurability", value); } }
    public float saRecoveryRate { get { return this.GenericParam.GetValue<float>("saRecoveryRate"); } set { this.GenericParam.SetValue("saRecoveryRate", value); } }
    public float saGuardCutRate { get { return this.GenericParam.GetValue<float>("saGuardCutRate"); } set { this.GenericParam.SetValue("saGuardCutRate", value); } }
    public int resistCorrectId_blood { get { return this.GenericParam.GetValue<int>("resistCorrectId_blood"); } set { this.GenericParam.SetValue("resistCorrectId_blood", value); } }
    public int resistCorrectId_curse { get { return this.GenericParam.GetValue<int>("resistCorrectId_curse"); } set { this.GenericParam.SetValue("resistCorrectId_curse", value); } }
    public int resistCorrectId_freeze { get { return this.GenericParam.GetValue<int>("resistCorrectId_freeze"); } set { this.GenericParam.SetValue("resistCorrectId_freeze", value); } }
    public int resistCorrectId_sleep { get { return this.GenericParam.GetValue<int>("resistCorrectId_sleep"); } set { this.GenericParam.SetValue("resistCorrectId_sleep", value); } }
    public int resistCorrectId_madness { get { return this.GenericParam.GetValue<int>("resistCorrectId_madness"); } set { this.GenericParam.SetValue("resistCorrectId_madness", value); } }
    public uint chrDeadTutorialFlagId { get { return this.GenericParam.GetValue<uint>("chrDeadTutorialFlagId"); } set { this.GenericParam.SetValue("chrDeadTutorialFlagId", value); } }
    public float stepDispInterpolateTime { get { return this.GenericParam.GetValue<float>("stepDispInterpolateTime"); } set { this.GenericParam.SetValue("stepDispInterpolateTime", value); } }
    public float stepDispInterpolateTriggerValue { get { return this.GenericParam.GetValue<float>("stepDispInterpolateTriggerValue"); } set { this.GenericParam.SetValue("stepDispInterpolateTriggerValue", value); } }
    public float lockScoreOffset { get { return this.GenericParam.GetValue<float>("lockScoreOffset"); } set { this.GenericParam.SetValue("lockScoreOffset", value); } }
    public int dlcGameClearSpEffectID { get { return this.GenericParam.GetValue<int>("dlcGameClearSpEffectID"); } set { this.GenericParam.SetValue("dlcGameClearSpEffectID", value); } }
    public byte[] pad12 { get { return this.GenericParam.GetValue<byte[]>("pad12"); } set { this.GenericParam.SetValue("pad12", value); } }
}
