namespace DSLRNet.Core.Contracts.Params;

public partial class NpcParam
{
    public int ID { get; set; }
    public string Name { get; set; }
    public int disableParam_NT { get; set; }
    public int disableParamReserve1 { get; set; }
    public string disableParamReserve2 { get; set; }
    public int behaviorVariationId { get; set; }
    public int resistCorrectId_poison { get; set; }
    public int nameId { get; set; }
    public float turnVellocity { get; set; }
    public float hitHeight { get; set; }
    public float hitRadius { get; set; }
    public int weight { get; set; }
    public float hitYOffset { get; set; }
    public int hp { get; set; }
    public int mp { get; set; }
    public int getSoul { get; set; }
    public int itemLotId_enemy { get; set; }
    public int itemLotId_map { get; set; }
    public int maxAnkleRollAngle { get; set; }
    public int chrHitGroupAndNavimesh { get; set; }
    public int faceIconId { get; set; }
    public int deactivateDist { get; set; }
    public int chrActivateConditionParamId { get; set; }
    public float footIkErrorHeightLimit { get; set; }
    public int humanityLotId { get; set; }
    public int spEffectID0 { get; set; }
    public int spEffectID1 { get; set; }
    public int spEffectID2 { get; set; }
    public int spEffectID3 { get; set; }
    public int spEffectID4 { get; set; }
    public int spEffectID5 { get; set; }
    public int spEffectID6 { get; set; }
    public int spEffectID7 { get; set; }
    public int GameClearSpEffectID { get; set; }
    public int physGuardCutRate { get; set; }
    public int magGuardCutRate { get; set; }
    public int fireGuardCutRate { get; set; }
    public int thunGuardCutRate { get; set; }
    public int animIdOffset { get; set; }
    public int lockGazePoint0 { get; set; }
    public int lockGazePoint1 { get; set; }
    public int lockGazePoint2 { get; set; }
    public int lockGazePoint3 { get; set; }
    public int lockGazePoint4 { get; set; }
    public int lockGazePoint5 { get; set; }
    public int networkWarpDist { get; set; }
    public int dbgBehaviorR1 { get; set; }
    public int dbgBehaviorL1 { get; set; }
    public int dbgBehaviorR2 { get; set; }
    public int dbgBehaviorL2 { get; set; }
    public int dbgBehaviorRL { get; set; }
    public int dbgBehaviorRR { get; set; }
    public int dbgBehaviorRD { get; set; }
    public int dbgBehaviorRU { get; set; }
    public int dbgBehaviorLL { get; set; }
    public int dbgBehaviorLR { get; set; }
    public int dbgBehaviorLD { get; set; }
    public int dbgBehaviorLU { get; set; }
    public int animIdOffset2 { get; set; }
    public float partsDamageRate1 { get; set; }
    public float partsDamageRate2 { get; set; }
    public float partsDamageRate3 { get; set; }
    public float partsDamageRate4 { get; set; }
    public float partsDamageRate5 { get; set; }
    public float partsDamageRate6 { get; set; }
    public float partsDamageRate7 { get; set; }
    public float partsDamageRate8 { get; set; }
    public float weakPartsDamageRate { get; set; }
    public float superArmorRecoverCorrection { get; set; }
    public int superArmorBrakeKnockbackDist { get; set; }
    public int stamina { get; set; }
    public int staminaRecoverBaseVel { get; set; }
    public int def_phys { get; set; }
    public int def_slash { get; set; }
    public int def_blow { get; set; }
    public int def_thrust { get; set; }
    public int def_mag { get; set; }
    public int def_fire { get; set; }
    public int def_thunder { get; set; }
    public int defFlickPower { get; set; }
    public int resist_poison { get; set; }
    public int resist_desease { get; set; }
    public int resist_blood { get; set; }
    public int resist_curse { get; set; }
    public int ghostModelId { get; set; }
    public int normalChangeResouceId { get; set; }
    public int guardAngle { get; set; }
    public int slashGuardCutRate { get; set; }
    public int blowGuardCutRate { get; set; }
    public int thrustGuardCutRate { get; set; }
    public int lockGazePoint6 { get; set; }
    public int normalChangeTexChrId { get; set; }
    public int dropType { get; set; }
    public int knockbackRate { get; set; }
    public int knockbackParamId { get; set; }
    public int fallDamageDump { get; set; }
    public int staminaGuardDef { get; set; }
    public int resist_sleep { get; set; }
    public int resist_madness { get; set; }
    public int sleepGuardResist { get; set; }
    public int madnessGuardResist { get; set; }
    public int lockGazePoint7 { get; set; }
    public int mpRecoverBaseVel { get; set; }
    public int flickDamageCutRate { get; set; }
    public int defaultLodParamId { get; set; }
    public int drawType { get; set; }
    public int npcType { get; set; }
    public int teamType { get; set; }
    public int moveType { get; set; }
    public int lockDist { get; set; }
    public int materialSe_Weak1 { get; set; }
    public int materialSfx_Weak1 { get; set; }
    public int partsDamageType { get; set; }
    public int vowType { get; set; }
    public int guardLevel { get; set; }
    public int burnSfxType { get; set; }
    public int poisonGuardResist { get; set; }
    public int diseaseGuardResist { get; set; }
    public int bloodGuardResist { get; set; }
    public int curseGuardResist { get; set; }
    public int parryAttack { get; set; }
    public int parryDefence { get; set; }
    public int sfxSize { get; set; }
    public int pushOutCamRegionRadius { get; set; }
    public int hitStopType { get; set; }
    public int ladderEndChkOffsetTop { get; set; }
    public int ladderEndChkOffsetLow { get; set; }
    public int useRagdollCamHit { get; set; }
    public int disableClothRigidHit { get; set; }
    public int useUndulationAddAnimFB { get; set; }
    public int isWeakA { get; set; }
    public int isGhost { get; set; }
    public int isNoDamageMotion { get; set; }
    public int isUnduration { get; set; }
    public int isChangeWanderGhost { get; set; }
    public int modelDispMask0 { get; set; }
    public int modelDispMask1 { get; set; }
    public int modelDispMask2 { get; set; }
    public int modelDispMask3 { get; set; }
    public int modelDispMask4 { get; set; }
    public int modelDispMask5 { get; set; }
    public int modelDispMask6 { get; set; }
    public int modelDispMask7 { get; set; }
    public int modelDispMask8 { get; set; }
    public int modelDispMask9 { get; set; }
    public int modelDispMask10 { get; set; }
    public int modelDispMask11 { get; set; }
    public int modelDispMask12 { get; set; }
    public int modelDispMask13 { get; set; }
    public int modelDispMask14 { get; set; }
    public int modelDispMask15 { get; set; }
    public int isEnableNeckTurn { get; set; }
    public int disableRespawn { get; set; }
    public int isMoveAnimWait { get; set; }
    public int isCrowd { get; set; }
    public int isWeakB { get; set; }
    public int isWeakC { get; set; }
    public int isWeakD { get; set; }
    public int doesAlwaysUseSpecialTurn { get; set; }
    public int isRideAtkTarget { get; set; }
    public int isEnableStepDispInterpolate { get; set; }
    public int isStealthTarget { get; set; }
    public int disableInitializeDead { get; set; }
    public int isHitRumble { get; set; }
    public int isSmoothTurn { get; set; }
    public int isWeakE { get; set; }
    public int isWeakF { get; set; }
    public int modelDispMask16 { get; set; }
    public int modelDispMask17 { get; set; }
    public int modelDispMask18 { get; set; }
    public int modelDispMask19 { get; set; }
    public int modelDispMask20 { get; set; }
    public int modelDispMask21 { get; set; }
    public int modelDispMask22 { get; set; }
    public int modelDispMask23 { get; set; }
    public int modelDispMask24 { get; set; }
    public int modelDispMask25 { get; set; }
    public int modelDispMask26 { get; set; }
    public int modelDispMask27 { get; set; }
    public int modelDispMask28 { get; set; }
    public int modelDispMask29 { get; set; }
    public int modelDispMask30 { get; set; }
    public int modelDispMask31 { get; set; }
    public int itemSearchRadius { get; set; }
    public float chrHitHeight { get; set; }
    public float chrHitRadius { get; set; }
    public int specialTurnType { get; set; }
    public int isSoulGetByBoss { get; set; }
    public int isBulletOwner_byObject { get; set; }
    public int isUseLowHitFootIk { get; set; }
    public int isCalculatePvPDamage { get; set; }
    public int isHostSyncChr { get; set; }
    public int isSkipWeakDamageAnim { get; set; }
    public int isKeepHitOnRide { get; set; }
    public int isSpCollide { get; set; }
    public int def_dark { get; set; }
    public int threatLv { get; set; }
    public int specialTurnDistanceThreshold { get; set; }
    public int autoFootEffectSfxId { get; set; }
    public int materialSe1 { get; set; }
    public int materialSfx1 { get; set; }
    public int materialSe_Weak2 { get; set; }
    public int materialSfx_Weak2 { get; set; }
    public int materialSe2 { get; set; }
    public int materialSfx2 { get; set; }
    public int spEffectID8 { get; set; }
    public int spEffectID9 { get; set; }
    public int spEffectID10 { get; set; }
    public int spEffectID11 { get; set; }
    public int spEffectID12 { get; set; }
    public int spEffectID13 { get; set; }
    public int spEffectID14 { get; set; }
    public int spEffectID15 { get; set; }
    public int autoFootEffectDecalBaseId1 { get; set; }
    public int toughness { get; set; }
    public float toughnessRecoverCorrection { get; set; }
    public float neutralDamageCutRate { get; set; }
    public float slashDamageCutRate { get; set; }
    public float blowDamageCutRate { get; set; }
    public float thrustDamageCutRate { get; set; }
    public float magicDamageCutRate { get; set; }
    public float fireDamageCutRate { get; set; }
    public float thunderDamageCutRate { get; set; }
    public float darkDamageCutRate { get; set; }
    public int darkGuardCutRate { get; set; }
    public int clothUpdateOffset { get; set; }
    public int npcPlayerWeightType { get; set; }
    public int normalChangeModelId { get; set; }
    public int normalChangeAnimChrId { get; set; }
    public int paintRenderTargetSize { get; set; }
    public int resistCorrectId_disease { get; set; }
    public int phantomShaderId { get; set; }
    public int multiPlayCorrectionParamId { get; set; }
    public int maxAnklePitchAngle { get; set; }
    public int resist_freeze { get; set; }
    public int freezeGuardResist { get; set; }
    public int hpBurnDamageRate { get; set; }
    public int lockCameraParamId { get; set; }
    public int spEffectID16 { get; set; }
    public int spEffectID17 { get; set; }
    public int spEffectID18 { get; set; }
    public int spEffectID19 { get; set; }
    public int spEffectID20 { get; set; }
    public int spEffectID21 { get; set; }
    public int spEffectID22 { get; set; }
    public int spEffectID23 { get; set; }
    public int spEffectID24 { get; set; }
    public int spEffectID25 { get; set; }
    public int spEffectID26 { get; set; }
    public int spEffectID27 { get; set; }
    public int spEffectID28 { get; set; }
    public int spEffectID29 { get; set; }
    public int spEffectID30 { get; set; }
    public int spEffectID31 { get; set; }
    public int disableLockOnAng { get; set; }
    public int clothOffLodLevel { get; set; }
    public int isUseFootIKNormalByUnduration { get; set; }
    public int attachHitInitializeDead { get; set; }
    public int excludeGroupRewardCheck { get; set; }
    public int enableAILockDmyPoly_212 { get; set; }
    public int enableAILockDmyPoly_213 { get; set; }
    public int enableAILockDmyPoly_214 { get; set; }
    public int disableActivateOpen_xb1 { get; set; }
    public int disableActivateLegacy_xb1 { get; set; }
    public int estusFlaskRecoveryParamId { get; set; }
    public int roleNameId { get; set; }
    public int estusFlaskLotPoint { get; set; }
    public int hpEstusFlaskLotPoint { get; set; }
    public int mpEstusFlaskLotPoint { get; set; }
    public int estusFlaskRecovery_failedLotPointAdd { get; set; }
    public int hpEstusFlaskRecovery_failedLotPointAdd { get; set; }
    public int mpEstusFlaskRecovery_failedLotPointAdd { get; set; }
    public int WanderGhostPhantomId { get; set; }
    public int hearingHeadSize { get; set; }
    public int SoundBankId { get; set; }
    public int forwardUndulationLimit { get; set; }
    public int sideUndulationLimit { get; set; }
    public int deactiveMoveSpeed { get; set; }
    public int deactiveMoveDist { get; set; }
    public int enableSoundObjDist { get; set; }
    public float undulationCorrectGain { get; set; }
    public int autoFootEffectDecalBaseId2 { get; set; }
    public int autoFootEffectDecalBaseId3 { get; set; }
    public int RetargetReferenceChrId { get; set; }
    public int SfxResBankId { get; set; }
    public float updateActivatePriolity { get; set; }
    public int chrNavimeshFlag_Alive { get; set; }
    public int chrNavimeshFlag_Dead { get; set; }
    public int isConsideredUndead { get; set; }
    public int wheelRotType { get; set; }
    public float wheelRotRadius { get; set; }
    public float retargetMoveRate { get; set; }
    public float ladderWarpOffset { get; set; }
    public int loadAssetId { get; set; }
    public int overlapCameraDmypolyId { get; set; }
    public int residentMaterialExParamId00 { get; set; }
    public int residentMaterialExParamId01 { get; set; }
    public int residentMaterialExParamId02 { get; set; }
    public int residentMaterialExParamId03 { get; set; }
    public int residentMaterialExParamId04 { get; set; }
    public int sleepCollectorItemLotId_enemy { get; set; }
    public int sleepCollectorItemLotId_map { get; set; }
    public float footIkErrorOnGain { get; set; }
    public float footIkErrorOffGain { get; set; }
    public int SoundAddBankId { get; set; }
    public int materialVariationValue { get; set; }
    public int materialVariationValue_Weak { get; set; }
    public int superArmorDurability { get; set; }
    public float saRecoveryRate { get; set; }
    public int saGuardCutRate { get; set; }
    public int resistCorrectId_blood { get; set; }
    public int resistCorrectId_curse { get; set; }
    public int resistCorrectId_freeze { get; set; }
    public int resistCorrectId_sleep { get; set; }
    public int resistCorrectId_madness { get; set; }
    public int chrDeadTutorialFlagId { get; set; }
    public float stepDispInterpolateTime { get; set; }
    public float stepDispInterpolateTriggerValue { get; set; }
    public int lockScoreOffset { get; set; }
    public int dlcGameClearSpEffectID { get; set; }
    public string pad12 { get; set; }
}