public class SpEffectParamNew : ParamBase<SpEffectParamNew>
{
    public string Name { get { return this.GetValue<string>("Name"); } set { this.SetValue("Name", value); } }
    public int iconId { get { return this.GetValue<int>("iconId"); } set { this.SetValue("iconId", value); } }
    public float conditionHp { get { return this.GetValue<float>("conditionHp"); } set { this.SetValue("conditionHp", value); } }
    public float effectEndurance { get { return this.GetValue<float>("effectEndurance"); } set { this.SetValue("effectEndurance", value); } }
    public float motionInterval { get { return this.GetValue<float>("motionInterval"); } set { this.SetValue("motionInterval", value); } }
    public float maxHpRate { get { return this.GetValue<float>("maxHpRate"); } set { this.SetValue("maxHpRate", value); } }
    public float maxMpRate { get { return this.GetValue<float>("maxMpRate"); } set { this.SetValue("maxMpRate", value); } }
    public float maxStaminaRate { get { return this.GetValue<float>("maxStaminaRate"); } set { this.SetValue("maxStaminaRate", value); } }
    public float slashDamageCutRate { get { return this.GetValue<float>("slashDamageCutRate"); } set { this.SetValue("slashDamageCutRate", value); } }
    public float blowDamageCutRate { get { return this.GetValue<float>("blowDamageCutRate"); } set { this.SetValue("blowDamageCutRate", value); } }
    public float thrustDamageCutRate { get { return this.GetValue<float>("thrustDamageCutRate"); } set { this.SetValue("thrustDamageCutRate", value); } }
    public float neutralDamageCutRate { get { return this.GetValue<float>("neutralDamageCutRate"); } set { this.SetValue("neutralDamageCutRate", value); } }
    public float magicDamageCutRate { get { return this.GetValue<float>("magicDamageCutRate"); } set { this.SetValue("magicDamageCutRate", value); } }
    public float fireDamageCutRate { get { return this.GetValue<float>("fireDamageCutRate"); } set { this.SetValue("fireDamageCutRate", value); } }
    public float thunderDamageCutRate { get { return this.GetValue<float>("thunderDamageCutRate"); } set { this.SetValue("thunderDamageCutRate", value); } }
    public float physicsAttackRate { get { return this.GetValue<float>("physicsAttackRate"); } set { this.SetValue("physicsAttackRate", value); } }
    public float magicAttackRate { get { return this.GetValue<float>("magicAttackRate"); } set { this.SetValue("magicAttackRate", value); } }
    public float fireAttackRate { get { return this.GetValue<float>("fireAttackRate"); } set { this.SetValue("fireAttackRate", value); } }
    public float thunderAttackRate { get { return this.GetValue<float>("thunderAttackRate"); } set { this.SetValue("thunderAttackRate", value); } }
    public float physicsAttackPowerRate { get { return this.GetValue<float>("physicsAttackPowerRate"); } set { this.SetValue("physicsAttackPowerRate", value); } }
    public float magicAttackPowerRate { get { return this.GetValue<float>("magicAttackPowerRate"); } set { this.SetValue("magicAttackPowerRate", value); } }
    public float fireAttackPowerRate { get { return this.GetValue<float>("fireAttackPowerRate"); } set { this.SetValue("fireAttackPowerRate", value); } }
    public float thunderAttackPowerRate { get { return this.GetValue<float>("thunderAttackPowerRate"); } set { this.SetValue("thunderAttackPowerRate", value); } }
    public int physicsAttackPower { get { return this.GetValue<int>("physicsAttackPower"); } set { this.SetValue("physicsAttackPower", value); } }
    public int magicAttackPower { get { return this.GetValue<int>("magicAttackPower"); } set { this.SetValue("magicAttackPower", value); } }
    public int fireAttackPower { get { return this.GetValue<int>("fireAttackPower"); } set { this.SetValue("fireAttackPower", value); } }
    public int thunderAttackPower { get { return this.GetValue<int>("thunderAttackPower"); } set { this.SetValue("thunderAttackPower", value); } }
    public float physicsDiffenceRate { get { return this.GetValue<float>("physicsDiffenceRate"); } set { this.SetValue("physicsDiffenceRate", value); } }
    public float magicDiffenceRate { get { return this.GetValue<float>("magicDiffenceRate"); } set { this.SetValue("magicDiffenceRate", value); } }
    public float fireDiffenceRate { get { return this.GetValue<float>("fireDiffenceRate"); } set { this.SetValue("fireDiffenceRate", value); } }
    public float thunderDiffenceRate { get { return this.GetValue<float>("thunderDiffenceRate"); } set { this.SetValue("thunderDiffenceRate", value); } }
    public int physicsDiffence { get { return this.GetValue<int>("physicsDiffence"); } set { this.SetValue("physicsDiffence", value); } }
    public int magicDiffence { get { return this.GetValue<int>("magicDiffence"); } set { this.SetValue("magicDiffence", value); } }
    public int fireDiffence { get { return this.GetValue<int>("fireDiffence"); } set { this.SetValue("fireDiffence", value); } }
    public int thunderDiffence { get { return this.GetValue<int>("thunderDiffence"); } set { this.SetValue("thunderDiffence", value); } }
    public float NoGuardDamageRate { get { return this.GetValue<float>("NoGuardDamageRate"); } set { this.SetValue("NoGuardDamageRate", value); } }
    public float vitalSpotChangeRate { get { return this.GetValue<float>("vitalSpotChangeRate"); } set { this.SetValue("vitalSpotChangeRate", value); } }
    public float normalSpotChangeRate { get { return this.GetValue<float>("normalSpotChangeRate"); } set { this.SetValue("normalSpotChangeRate", value); } }
    public float lookAtTargetPosOffset { get { return this.GetValue<float>("lookAtTargetPosOffset"); } set { this.SetValue("lookAtTargetPosOffset", value); } }
    public int behaviorId { get { return this.GetValue<int>("behaviorId"); } set { this.SetValue("behaviorId", value); } }
    public float changeHpRate { get { return this.GetValue<float>("changeHpRate"); } set { this.SetValue("changeHpRate", value); } }
    public int changeHpPoint { get { return this.GetValue<int>("changeHpPoint"); } set { this.SetValue("changeHpPoint", value); } }
    public float changeMpRate { get { return this.GetValue<float>("changeMpRate"); } set { this.SetValue("changeMpRate", value); } }
    public int changeMpPoint { get { return this.GetValue<int>("changeMpPoint"); } set { this.SetValue("changeMpPoint", value); } }
    public int mpRecoverChangeSpeed { get { return this.GetValue<int>("mpRecoverChangeSpeed"); } set { this.SetValue("mpRecoverChangeSpeed", value); } }
    public float changeStaminaRate { get { return this.GetValue<float>("changeStaminaRate"); } set { this.SetValue("changeStaminaRate", value); } }
    public int changeStaminaPoint { get { return this.GetValue<int>("changeStaminaPoint"); } set { this.SetValue("changeStaminaPoint", value); } }
    public int staminaRecoverChangeSpeed { get { return this.GetValue<int>("staminaRecoverChangeSpeed"); } set { this.SetValue("staminaRecoverChangeSpeed", value); } }
    public float magicEffectTimeChange { get { return this.GetValue<float>("magicEffectTimeChange"); } set { this.SetValue("magicEffectTimeChange", value); } }
    public int insideDurability { get { return this.GetValue<int>("insideDurability"); } set { this.SetValue("insideDurability", value); } }
    public int maxDurability { get { return this.GetValue<int>("maxDurability"); } set { this.SetValue("maxDurability", value); } }
    public float staminaAttackRate { get { return this.GetValue<float>("staminaAttackRate"); } set { this.SetValue("staminaAttackRate", value); } }
    public int poizonAttackPower { get { return this.GetValue<int>("poizonAttackPower"); } set { this.SetValue("poizonAttackPower", value); } }
    public int diseaseAttackPower { get { return this.GetValue<int>("diseaseAttackPower"); } set { this.SetValue("diseaseAttackPower", value); } }
    public int bloodAttackPower { get { return this.GetValue<int>("bloodAttackPower"); } set { this.SetValue("bloodAttackPower", value); } }
    public int curseAttackPower { get { return this.GetValue<int>("curseAttackPower"); } set { this.SetValue("curseAttackPower", value); } }
    public float fallDamageRate { get { return this.GetValue<float>("fallDamageRate"); } set { this.SetValue("fallDamageRate", value); } }
    public float soulRate { get { return this.GetValue<float>("soulRate"); } set { this.SetValue("soulRate", value); } }
    public float equipWeightChangeRate { get { return this.GetValue<float>("equipWeightChangeRate"); } set { this.SetValue("equipWeightChangeRate", value); } }
    public float allItemWeightChangeRate { get { return this.GetValue<float>("allItemWeightChangeRate"); } set { this.SetValue("allItemWeightChangeRate", value); } }
    public int soul { get { return this.GetValue<int>("soul"); } set { this.SetValue("soul", value); } }
    public int animIdOffset { get { return this.GetValue<int>("animIdOffset"); } set { this.SetValue("animIdOffset", value); } }
    public float haveSoulRate { get { return this.GetValue<float>("haveSoulRate"); } set { this.SetValue("haveSoulRate", value); } }
    public float targetPriority { get { return this.GetValue<float>("targetPriority"); } set { this.SetValue("targetPriority", value); } }
    public float sightSearchEnemyRate { get { return this.GetValue<float>("sightSearchEnemyRate"); } set { this.SetValue("sightSearchEnemyRate", value); } }
    public float hearingSearchEnemyRate { get { return this.GetValue<float>("hearingSearchEnemyRate"); } set { this.SetValue("hearingSearchEnemyRate", value); } }
    public float grabityRate { get { return this.GetValue<float>("grabityRate"); } set { this.SetValue("grabityRate", value); } }
    public float registPoizonChangeRate { get { return this.GetValue<float>("registPoizonChangeRate"); } set { this.SetValue("registPoizonChangeRate", value); } }
    public float registDiseaseChangeRate { get { return this.GetValue<float>("registDiseaseChangeRate"); } set { this.SetValue("registDiseaseChangeRate", value); } }
    public float registBloodChangeRate { get { return this.GetValue<float>("registBloodChangeRate"); } set { this.SetValue("registBloodChangeRate", value); } }
    public float registCurseChangeRate { get { return this.GetValue<float>("registCurseChangeRate"); } set { this.SetValue("registCurseChangeRate", value); } }
    public float soulStealRate { get { return this.GetValue<float>("soulStealRate"); } set { this.SetValue("soulStealRate", value); } }
    public float lifeReductionRate { get { return this.GetValue<float>("lifeReductionRate"); } set { this.SetValue("lifeReductionRate", value); } }
    public float hpRecoverRate { get { return this.GetValue<float>("hpRecoverRate"); } set { this.SetValue("hpRecoverRate", value); } }
    public int replaceSpEffectId { get { return this.GetValue<int>("replaceSpEffectId"); } set { this.SetValue("replaceSpEffectId", value); } }
    public int cycleOccurrenceSpEffectId { get { return this.GetValue<int>("cycleOccurrenceSpEffectId"); } set { this.SetValue("cycleOccurrenceSpEffectId", value); } }
    public int atkOccurrenceSpEffectId { get { return this.GetValue<int>("atkOccurrenceSpEffectId"); } set { this.SetValue("atkOccurrenceSpEffectId", value); } }
    public float guardDefFlickPowerRate { get { return this.GetValue<float>("guardDefFlickPowerRate"); } set { this.SetValue("guardDefFlickPowerRate", value); } }
    public float guardStaminaCutRate { get { return this.GetValue<float>("guardStaminaCutRate"); } set { this.SetValue("guardStaminaCutRate", value); } }
    public short rayCastPassedTime { get { return this.GetValue<short>("rayCastPassedTime"); } set { this.SetValue("rayCastPassedTime", value); } }
    public byte magicSubCategoryChange1 { get { return this.GetValue<byte>("magicSubCategoryChange1"); } set { this.SetValue("magicSubCategoryChange1", value); } }
    public byte magicSubCategoryChange2 { get { return this.GetValue<byte>("magicSubCategoryChange2"); } set { this.SetValue("magicSubCategoryChange2", value); } }
    public short bowDistRate { get { return this.GetValue<short>("bowDistRate"); } set { this.SetValue("bowDistRate", value); } }
    public ushort spCategory { get { return this.GetValue<ushort>("spCategory"); } set { this.SetValue("spCategory", value); } }
    public byte categoryPriority { get { return this.GetValue<byte>("categoryPriority"); } set { this.SetValue("categoryPriority", value); } }
    public sbyte saveCategory { get { return this.GetValue<sbyte>("saveCategory"); } set { this.SetValue("saveCategory", value); } }
    public byte changeMagicSlot { get { return this.GetValue<byte>("changeMagicSlot"); } set { this.SetValue("changeMagicSlot", value); } }
    public byte changeMiracleSlot { get { return this.GetValue<byte>("changeMiracleSlot"); } set { this.SetValue("changeMiracleSlot", value); } }
    public sbyte heroPointDamage { get { return this.GetValue<sbyte>("heroPointDamage"); } set { this.SetValue("heroPointDamage", value); } }
    public byte defFlickPower { get { return this.GetValue<byte>("defFlickPower"); } set { this.SetValue("defFlickPower", value); } }
    public byte flickDamageCutRate { get { return this.GetValue<byte>("flickDamageCutRate"); } set { this.SetValue("flickDamageCutRate", value); } }
    public byte bloodDamageRate { get { return this.GetValue<byte>("bloodDamageRate"); } set { this.SetValue("bloodDamageRate", value); } }
    public sbyte dmgLv_None { get { return this.GetValue<sbyte>("dmgLv_None"); } set { this.SetValue("dmgLv_None", value); } }
    public sbyte dmgLv_S { get { return this.GetValue<sbyte>("dmgLv_S"); } set { this.SetValue("dmgLv_S", value); } }
    public sbyte dmgLv_M { get { return this.GetValue<sbyte>("dmgLv_M"); } set { this.SetValue("dmgLv_M", value); } }
    public sbyte dmgLv_L { get { return this.GetValue<sbyte>("dmgLv_L"); } set { this.SetValue("dmgLv_L", value); } }
    public sbyte dmgLv_BlowM { get { return this.GetValue<sbyte>("dmgLv_BlowM"); } set { this.SetValue("dmgLv_BlowM", value); } }
    public sbyte dmgLv_Push { get { return this.GetValue<sbyte>("dmgLv_Push"); } set { this.SetValue("dmgLv_Push", value); } }
    public sbyte dmgLv_Strike { get { return this.GetValue<sbyte>("dmgLv_Strike"); } set { this.SetValue("dmgLv_Strike", value); } }
    public sbyte dmgLv_BlowS { get { return this.GetValue<sbyte>("dmgLv_BlowS"); } set { this.SetValue("dmgLv_BlowS", value); } }
    public sbyte dmgLv_Min { get { return this.GetValue<sbyte>("dmgLv_Min"); } set { this.SetValue("dmgLv_Min", value); } }
    public sbyte dmgLv_Uppercut { get { return this.GetValue<sbyte>("dmgLv_Uppercut"); } set { this.SetValue("dmgLv_Uppercut", value); } }
    public sbyte dmgLv_BlowLL { get { return this.GetValue<sbyte>("dmgLv_BlowLL"); } set { this.SetValue("dmgLv_BlowLL", value); } }
    public sbyte dmgLv_Breath { get { return this.GetValue<sbyte>("dmgLv_Breath"); } set { this.SetValue("dmgLv_Breath", value); } }
    public byte atkAttribute { get { return this.GetValue<byte>("atkAttribute"); } set { this.SetValue("atkAttribute", value); } }
    public byte spAttribute { get { return this.GetValue<byte>("spAttribute"); } set { this.SetValue("spAttribute", value); } }
    public ushort stateInfo { get { return this.GetValue<ushort>("stateInfo"); } set { this.SetValue("stateInfo", value); } }
    public byte wepParamChange { get { return this.GetValue<byte>("wepParamChange"); } set { this.SetValue("wepParamChange", value); } }
    public byte moveType { get { return this.GetValue<byte>("moveType"); } set { this.SetValue("moveType", value); } }
    public ushort lifeReductionType { get { return this.GetValue<ushort>("lifeReductionType"); } set { this.SetValue("lifeReductionType", value); } }
    public byte throwCondition { get { return this.GetValue<byte>("throwCondition"); } set { this.SetValue("throwCondition", value); } }
    public sbyte addBehaviorJudgeId_condition { get { return this.GetValue<sbyte>("addBehaviorJudgeId_condition"); } set { this.SetValue("addBehaviorJudgeId_condition", value); } }
    public byte freezeDamageRate { get { return this.GetValue<byte>("freezeDamageRate"); } set { this.SetValue("freezeDamageRate", value); } }
    public byte effectTargetSelf { get { return this.GetValue<byte>("effectTargetSelf"); } set { this.SetValue("effectTargetSelf", value); } }
    public byte effectTargetFriend { get { return this.GetValue<byte>("effectTargetFriend"); } set { this.SetValue("effectTargetFriend", value); } }
    public byte effectTargetEnemy { get { return this.GetValue<byte>("effectTargetEnemy"); } set { this.SetValue("effectTargetEnemy", value); } }
    public byte effectTargetPlayer { get { return this.GetValue<byte>("effectTargetPlayer"); } set { this.SetValue("effectTargetPlayer", value); } }
    public byte effectTargetAI { get { return this.GetValue<byte>("effectTargetAI"); } set { this.SetValue("effectTargetAI", value); } }
    public byte effectTargetLive { get { return this.GetValue<byte>("effectTargetLive"); } set { this.SetValue("effectTargetLive", value); } }
    public byte effectTargetGhost { get { return this.GetValue<byte>("effectTargetGhost"); } set { this.SetValue("effectTargetGhost", value); } }
    public byte disableSleep { get { return this.GetValue<byte>("disableSleep"); } set { this.SetValue("disableSleep", value); } }
    public byte disableMadness { get { return this.GetValue<byte>("disableMadness"); } set { this.SetValue("disableMadness", value); } }
    public byte effectTargetAttacker { get { return this.GetValue<byte>("effectTargetAttacker"); } set { this.SetValue("effectTargetAttacker", value); } }
    public byte dispIconNonactive { get { return this.GetValue<byte>("dispIconNonactive"); } set { this.SetValue("dispIconNonactive", value); } }
    public byte regainGaugeDamage { get { return this.GetValue<byte>("regainGaugeDamage"); } set { this.SetValue("regainGaugeDamage", value); } }
    public byte bAdjustMagicAblity { get { return this.GetValue<byte>("bAdjustMagicAblity"); } set { this.SetValue("bAdjustMagicAblity", value); } }
    public byte bAdjustFaithAblity { get { return this.GetValue<byte>("bAdjustFaithAblity"); } set { this.SetValue("bAdjustFaithAblity", value); } }
    public byte bGameClearBonus { get { return this.GetValue<byte>("bGameClearBonus"); } set { this.SetValue("bGameClearBonus", value); } }
    public byte magParamChange { get { return this.GetValue<byte>("magParamChange"); } set { this.SetValue("magParamChange", value); } }
    public byte miracleParamChange { get { return this.GetValue<byte>("miracleParamChange"); } set { this.SetValue("miracleParamChange", value); } }
    public byte clearSoul { get { return this.GetValue<byte>("clearSoul"); } set { this.SetValue("clearSoul", value); } }
    public byte requestSOS { get { return this.GetValue<byte>("requestSOS"); } set { this.SetValue("requestSOS", value); } }
    public byte requestBlackSOS { get { return this.GetValue<byte>("requestBlackSOS"); } set { this.SetValue("requestBlackSOS", value); } }
    public byte requestForceJoinBlackSOS { get { return this.GetValue<byte>("requestForceJoinBlackSOS"); } set { this.SetValue("requestForceJoinBlackSOS", value); } }
    public byte requestKickSession { get { return this.GetValue<byte>("requestKickSession"); } set { this.SetValue("requestKickSession", value); } }
    public byte requestLeaveSession { get { return this.GetValue<byte>("requestLeaveSession"); } set { this.SetValue("requestLeaveSession", value); } }
    public byte requestNpcInveda { get { return this.GetValue<byte>("requestNpcInveda"); } set { this.SetValue("requestNpcInveda", value); } }
    public byte noDead { get { return this.GetValue<byte>("noDead"); } set { this.SetValue("noDead", value); } }
    public byte bCurrHPIndependeMaxHP { get { return this.GetValue<byte>("bCurrHPIndependeMaxHP"); } set { this.SetValue("bCurrHPIndependeMaxHP", value); } }
    public byte corrosionIgnore { get { return this.GetValue<byte>("corrosionIgnore"); } set { this.SetValue("corrosionIgnore", value); } }
    public byte sightSearchCutIgnore { get { return this.GetValue<byte>("sightSearchCutIgnore"); } set { this.SetValue("sightSearchCutIgnore", value); } }
    public byte hearingSearchCutIgnore { get { return this.GetValue<byte>("hearingSearchCutIgnore"); } set { this.SetValue("hearingSearchCutIgnore", value); } }
    public byte antiMagicIgnore { get { return this.GetValue<byte>("antiMagicIgnore"); } set { this.SetValue("antiMagicIgnore", value); } }
    public byte fakeTargetIgnore { get { return this.GetValue<byte>("fakeTargetIgnore"); } set { this.SetValue("fakeTargetIgnore", value); } }
    public byte fakeTargetIgnoreUndead { get { return this.GetValue<byte>("fakeTargetIgnoreUndead"); } set { this.SetValue("fakeTargetIgnoreUndead", value); } }
    public byte fakeTargetIgnoreAnimal { get { return this.GetValue<byte>("fakeTargetIgnoreAnimal"); } set { this.SetValue("fakeTargetIgnoreAnimal", value); } }
    public byte grabityIgnore { get { return this.GetValue<byte>("grabityIgnore"); } set { this.SetValue("grabityIgnore", value); } }
    public byte disablePoison { get { return this.GetValue<byte>("disablePoison"); } set { this.SetValue("disablePoison", value); } }
    public byte disableDisease { get { return this.GetValue<byte>("disableDisease"); } set { this.SetValue("disableDisease", value); } }
    public byte disableBlood { get { return this.GetValue<byte>("disableBlood"); } set { this.SetValue("disableBlood", value); } }
    public byte disableCurse { get { return this.GetValue<byte>("disableCurse"); } set { this.SetValue("disableCurse", value); } }
    public byte enableCharm { get { return this.GetValue<byte>("enableCharm"); } set { this.SetValue("enableCharm", value); } }
    public byte enableLifeTime { get { return this.GetValue<byte>("enableLifeTime"); } set { this.SetValue("enableLifeTime", value); } }
    public byte bAdjustStrengthAblity { get { return this.GetValue<byte>("bAdjustStrengthAblity"); } set { this.SetValue("bAdjustStrengthAblity", value); } }
    public byte bAdjustAgilityAblity { get { return this.GetValue<byte>("bAdjustAgilityAblity"); } set { this.SetValue("bAdjustAgilityAblity", value); } }
    public byte eraseOnBonfireRecover { get { return this.GetValue<byte>("eraseOnBonfireRecover"); } set { this.SetValue("eraseOnBonfireRecover", value); } }
    public byte throwAttackParamChange { get { return this.GetValue<byte>("throwAttackParamChange"); } set { this.SetValue("throwAttackParamChange", value); } }
    public byte requestLeaveColiseumSession { get { return this.GetValue<byte>("requestLeaveColiseumSession"); } set { this.SetValue("requestLeaveColiseumSession", value); } }
    public byte isExtendSpEffectLife { get { return this.GetValue<byte>("isExtendSpEffectLife"); } set { this.SetValue("isExtendSpEffectLife", value); } }
    public byte hasTarget { get { return this.GetValue<byte>("hasTarget"); } set { this.SetValue("hasTarget", value); } }
    public byte replanningOnFire { get { return this.GetValue<byte>("replanningOnFire"); } set { this.SetValue("replanningOnFire", value); } }
    public byte vowType0 { get { return this.GetValue<byte>("vowType0"); } set { this.SetValue("vowType0", value); } }
    public byte vowType1 { get { return this.GetValue<byte>("vowType1"); } set { this.SetValue("vowType1", value); } }
    public byte vowType2 { get { return this.GetValue<byte>("vowType2"); } set { this.SetValue("vowType2", value); } }
    public byte vowType3 { get { return this.GetValue<byte>("vowType3"); } set { this.SetValue("vowType3", value); } }
    public byte vowType4 { get { return this.GetValue<byte>("vowType4"); } set { this.SetValue("vowType4", value); } }
    public byte vowType5 { get { return this.GetValue<byte>("vowType5"); } set { this.SetValue("vowType5", value); } }
    public byte vowType6 { get { return this.GetValue<byte>("vowType6"); } set { this.SetValue("vowType6", value); } }
    public byte vowType7 { get { return this.GetValue<byte>("vowType7"); } set { this.SetValue("vowType7", value); } }
    public byte vowType8 { get { return this.GetValue<byte>("vowType8"); } set { this.SetValue("vowType8", value); } }
    public byte vowType9 { get { return this.GetValue<byte>("vowType9"); } set { this.SetValue("vowType9", value); } }
    public byte vowType10 { get { return this.GetValue<byte>("vowType10"); } set { this.SetValue("vowType10", value); } }
    public byte vowType11 { get { return this.GetValue<byte>("vowType11"); } set { this.SetValue("vowType11", value); } }
    public byte vowType12 { get { return this.GetValue<byte>("vowType12"); } set { this.SetValue("vowType12", value); } }
    public byte vowType13 { get { return this.GetValue<byte>("vowType13"); } set { this.SetValue("vowType13", value); } }
    public byte vowType14 { get { return this.GetValue<byte>("vowType14"); } set { this.SetValue("vowType14", value); } }
    public byte vowType15 { get { return this.GetValue<byte>("vowType15"); } set { this.SetValue("vowType15", value); } }
    public sbyte repAtkDmgLv { get { return this.GetValue<sbyte>("repAtkDmgLv"); } set { this.SetValue("repAtkDmgLv", value); } }
    public float sightSearchRate { get { return this.GetValue<float>("sightSearchRate"); } set { this.SetValue("sightSearchRate", value); } }
    public byte effectTargetOpposeTarget { get { return this.GetValue<byte>("effectTargetOpposeTarget"); } set { this.SetValue("effectTargetOpposeTarget", value); } }
    public byte effectTargetFriendlyTarget { get { return this.GetValue<byte>("effectTargetFriendlyTarget"); } set { this.SetValue("effectTargetFriendlyTarget", value); } }
    public byte effectTargetSelfTarget { get { return this.GetValue<byte>("effectTargetSelfTarget"); } set { this.SetValue("effectTargetSelfTarget", value); } }
    public byte effectTargetPcHorse { get { return this.GetValue<byte>("effectTargetPcHorse"); } set { this.SetValue("effectTargetPcHorse", value); } }
    public byte effectTargetPcDeceased { get { return this.GetValue<byte>("effectTargetPcDeceased"); } set { this.SetValue("effectTargetPcDeceased", value); } }
    public byte isContractSpEffectLife { get { return this.GetValue<byte>("isContractSpEffectLife"); } set { this.SetValue("isContractSpEffectLife", value); } }
    public byte isWaitModeDelete { get { return this.GetValue<byte>("isWaitModeDelete"); } set { this.SetValue("isWaitModeDelete", value); } }
    public byte isIgnoreNoDamage { get { return this.GetValue<byte>("isIgnoreNoDamage"); } set { this.SetValue("isIgnoreNoDamage", value); } }
    public sbyte changeTeamType { get { return this.GetValue<sbyte>("changeTeamType"); } set { this.SetValue("changeTeamType", value); } }
    public short dmypolyId { get { return this.GetValue<short>("dmypolyId"); } set { this.SetValue("dmypolyId", value); } }
    public int vfxId { get { return this.GetValue<int>("vfxId"); } set { this.SetValue("vfxId", value); } }
    public int accumuOverFireId { get { return this.GetValue<int>("accumuOverFireId"); } set { this.SetValue("accumuOverFireId", value); } }
    public int accumuOverVal { get { return this.GetValue<int>("accumuOverVal"); } set { this.SetValue("accumuOverVal", value); } }
    public int accumuUnderFireId { get { return this.GetValue<int>("accumuUnderFireId"); } set { this.SetValue("accumuUnderFireId", value); } }
    public int accumuUnderVal { get { return this.GetValue<int>("accumuUnderVal"); } set { this.SetValue("accumuUnderVal", value); } }
    public int accumuVal { get { return this.GetValue<int>("accumuVal"); } set { this.SetValue("accumuVal", value); } }
    public byte eye_angX { get { return this.GetValue<byte>("eye_angX"); } set { this.SetValue("eye_angX", value); } }
    public byte eye_angY { get { return this.GetValue<byte>("eye_angY"); } set { this.SetValue("eye_angY", value); } }
    public short addDeceasedLv { get { return this.GetValue<short>("addDeceasedLv"); } set { this.SetValue("addDeceasedLv", value); } }
    public int vfxId1 { get { return this.GetValue<int>("vfxId1"); } set { this.SetValue("vfxId1", value); } }
    public int vfxId2 { get { return this.GetValue<int>("vfxId2"); } set { this.SetValue("vfxId2", value); } }
    public int vfxId3 { get { return this.GetValue<int>("vfxId3"); } set { this.SetValue("vfxId3", value); } }
    public int vfxId4 { get { return this.GetValue<int>("vfxId4"); } set { this.SetValue("vfxId4", value); } }
    public int vfxId5 { get { return this.GetValue<int>("vfxId5"); } set { this.SetValue("vfxId5", value); } }
    public int vfxId6 { get { return this.GetValue<int>("vfxId6"); } set { this.SetValue("vfxId6", value); } }
    public int vfxId7 { get { return this.GetValue<int>("vfxId7"); } set { this.SetValue("vfxId7", value); } }
    public int freezeAttackPower { get { return this.GetValue<int>("freezeAttackPower"); } set { this.SetValue("freezeAttackPower", value); } }
    public int AppearAiSoundId { get { return this.GetValue<int>("AppearAiSoundId"); } set { this.SetValue("AppearAiSoundId", value); } }
    public short addFootEffectSfxId { get { return this.GetValue<short>("addFootEffectSfxId"); } set { this.SetValue("addFootEffectSfxId", value); } }
    public sbyte dexterityCancelSystemOnlyAddDexterity { get { return this.GetValue<sbyte>("dexterityCancelSystemOnlyAddDexterity"); } set { this.SetValue("dexterityCancelSystemOnlyAddDexterity", value); } }
    public sbyte teamOffenseEffectivity { get { return this.GetValue<sbyte>("teamOffenseEffectivity"); } set { this.SetValue("teamOffenseEffectivity", value); } }
    public float toughnessDamageCutRate { get { return this.GetValue<float>("toughnessDamageCutRate"); } set { this.SetValue("toughnessDamageCutRate", value); } }
    public float weakDmgRateA { get { return this.GetValue<float>("weakDmgRateA"); } set { this.SetValue("weakDmgRateA", value); } }
    public float weakDmgRateB { get { return this.GetValue<float>("weakDmgRateB"); } set { this.SetValue("weakDmgRateB", value); } }
    public float weakDmgRateC { get { return this.GetValue<float>("weakDmgRateC"); } set { this.SetValue("weakDmgRateC", value); } }
    public float weakDmgRateD { get { return this.GetValue<float>("weakDmgRateD"); } set { this.SetValue("weakDmgRateD", value); } }
    public float weakDmgRateE { get { return this.GetValue<float>("weakDmgRateE"); } set { this.SetValue("weakDmgRateE", value); } }
    public float weakDmgRateF { get { return this.GetValue<float>("weakDmgRateF"); } set { this.SetValue("weakDmgRateF", value); } }
    public float darkDamageCutRate { get { return this.GetValue<float>("darkDamageCutRate"); } set { this.SetValue("darkDamageCutRate", value); } }
    public float darkDiffenceRate { get { return this.GetValue<float>("darkDiffenceRate"); } set { this.SetValue("darkDiffenceRate", value); } }
    public int darkDiffence { get { return this.GetValue<int>("darkDiffence"); } set { this.SetValue("darkDiffence", value); } }
    public float darkAttackRate { get { return this.GetValue<float>("darkAttackRate"); } set { this.SetValue("darkAttackRate", value); } }
    public float darkAttackPowerRate { get { return this.GetValue<float>("darkAttackPowerRate"); } set { this.SetValue("darkAttackPowerRate", value); } }
    public int darkAttackPower { get { return this.GetValue<int>("darkAttackPower"); } set { this.SetValue("darkAttackPower", value); } }
    public float antiDarkSightRadius { get { return this.GetValue<float>("antiDarkSightRadius"); } set { this.SetValue("antiDarkSightRadius", value); } }
    public int antiDarkSightDmypolyId { get { return this.GetValue<int>("antiDarkSightDmypolyId"); } set { this.SetValue("antiDarkSightDmypolyId", value); } }
    public float conditionHpRate { get { return this.GetValue<float>("conditionHpRate"); } set { this.SetValue("conditionHpRate", value); } }
    public float consumeStaminaRate { get { return this.GetValue<float>("consumeStaminaRate"); } set { this.SetValue("consumeStaminaRate", value); } }
    public float itemDropRate { get { return this.GetValue<float>("itemDropRate"); } set { this.SetValue("itemDropRate", value); } }
    public int changePoisonResistPoint { get { return this.GetValue<int>("changePoisonResistPoint"); } set { this.SetValue("changePoisonResistPoint", value); } }
    public int changeDiseaseResistPoint { get { return this.GetValue<int>("changeDiseaseResistPoint"); } set { this.SetValue("changeDiseaseResistPoint", value); } }
    public int changeBloodResistPoint { get { return this.GetValue<int>("changeBloodResistPoint"); } set { this.SetValue("changeBloodResistPoint", value); } }
    public int changeCurseResistPoint { get { return this.GetValue<int>("changeCurseResistPoint"); } set { this.SetValue("changeCurseResistPoint", value); } }
    public int changeFreezeResistPoint { get { return this.GetValue<int>("changeFreezeResistPoint"); } set { this.SetValue("changeFreezeResistPoint", value); } }
    public float slashAttackRate { get { return this.GetValue<float>("slashAttackRate"); } set { this.SetValue("slashAttackRate", value); } }
    public float blowAttackRate { get { return this.GetValue<float>("blowAttackRate"); } set { this.SetValue("blowAttackRate", value); } }
    public float thrustAttackRate { get { return this.GetValue<float>("thrustAttackRate"); } set { this.SetValue("thrustAttackRate", value); } }
    public float neutralAttackRate { get { return this.GetValue<float>("neutralAttackRate"); } set { this.SetValue("neutralAttackRate", value); } }
    public float slashAttackPowerRate { get { return this.GetValue<float>("slashAttackPowerRate"); } set { this.SetValue("slashAttackPowerRate", value); } }
    public float blowAttackPowerRate { get { return this.GetValue<float>("blowAttackPowerRate"); } set { this.SetValue("blowAttackPowerRate", value); } }
    public float thrustAttackPowerRate { get { return this.GetValue<float>("thrustAttackPowerRate"); } set { this.SetValue("thrustAttackPowerRate", value); } }
    public float neutralAttackPowerRate { get { return this.GetValue<float>("neutralAttackPowerRate"); } set { this.SetValue("neutralAttackPowerRate", value); } }
    public int slashAttackPower { get { return this.GetValue<int>("slashAttackPower"); } set { this.SetValue("slashAttackPower", value); } }
    public int blowAttackPower { get { return this.GetValue<int>("blowAttackPower"); } set { this.SetValue("blowAttackPower", value); } }
    public int thrustAttackPower { get { return this.GetValue<int>("thrustAttackPower"); } set { this.SetValue("thrustAttackPower", value); } }
    public int neutralAttackPower { get { return this.GetValue<int>("neutralAttackPower"); } set { this.SetValue("neutralAttackPower", value); } }
    public int changeStrengthPoint { get { return this.GetValue<int>("changeStrengthPoint"); } set { this.SetValue("changeStrengthPoint", value); } }
    public int changeAgilityPoint { get { return this.GetValue<int>("changeAgilityPoint"); } set { this.SetValue("changeAgilityPoint", value); } }
    public int changeMagicPoint { get { return this.GetValue<int>("changeMagicPoint"); } set { this.SetValue("changeMagicPoint", value); } }
    public int changeFaithPoint { get { return this.GetValue<int>("changeFaithPoint"); } set { this.SetValue("changeFaithPoint", value); } }
    public int changeLuckPoint { get { return this.GetValue<int>("changeLuckPoint"); } set { this.SetValue("changeLuckPoint", value); } }
    public sbyte recoverArtsPoint_Str { get { return this.GetValue<sbyte>("recoverArtsPoint_Str"); } set { this.SetValue("recoverArtsPoint_Str", value); } }
    public sbyte recoverArtsPoint_Dex { get { return this.GetValue<sbyte>("recoverArtsPoint_Dex"); } set { this.SetValue("recoverArtsPoint_Dex", value); } }
    public sbyte recoverArtsPoint_Magic { get { return this.GetValue<sbyte>("recoverArtsPoint_Magic"); } set { this.SetValue("recoverArtsPoint_Magic", value); } }
    public sbyte recoverArtsPoint_Miracle { get { return this.GetValue<sbyte>("recoverArtsPoint_Miracle"); } set { this.SetValue("recoverArtsPoint_Miracle", value); } }
    public byte madnessDamageRate { get { return this.GetValue<byte>("madnessDamageRate"); } set { this.SetValue("madnessDamageRate", value); } }
    public byte isUseStatusAilmentAtkPowerCorrect { get { return this.GetValue<byte>("isUseStatusAilmentAtkPowerCorrect"); } set { this.SetValue("isUseStatusAilmentAtkPowerCorrect", value); } }
    public byte isUseAtkParamAtkPowerCorrect { get { return this.GetValue<byte>("isUseAtkParamAtkPowerCorrect"); } set { this.SetValue("isUseAtkParamAtkPowerCorrect", value); } }
    public byte dontDeleteOnDead { get { return this.GetValue<byte>("dontDeleteOnDead"); } set { this.SetValue("dontDeleteOnDead", value); } }
    public byte disableFreeze { get { return this.GetValue<byte>("disableFreeze"); } set { this.SetValue("disableFreeze", value); } }
    public byte isDisableNetSync { get { return this.GetValue<byte>("isDisableNetSync"); } set { this.SetValue("isDisableNetSync", value); } }
    public byte shamanParamChange { get { return this.GetValue<byte>("shamanParamChange"); } set { this.SetValue("shamanParamChange", value); } }
    public byte isStopSearchedNotify { get { return this.GetValue<byte>("isStopSearchedNotify"); } set { this.SetValue("isStopSearchedNotify", value); } }
    public byte isCheckAboveShadowTest { get { return this.GetValue<byte>("isCheckAboveShadowTest"); } set { this.SetValue("isCheckAboveShadowTest", value); } }
    public ushort addBehaviorJudgeId_add { get { return this.GetValue<ushort>("addBehaviorJudgeId_add"); } set { this.SetValue("addBehaviorJudgeId_add", value); } }
    public float saReceiveDamageRate { get { return this.GetValue<float>("saReceiveDamageRate"); } set { this.SetValue("saReceiveDamageRate", value); } }
    public float defPlayerDmgCorrectRate_Physics { get { return this.GetValue<float>("defPlayerDmgCorrectRate_Physics"); } set { this.SetValue("defPlayerDmgCorrectRate_Physics", value); } }
    public float defPlayerDmgCorrectRate_Magic { get { return this.GetValue<float>("defPlayerDmgCorrectRate_Magic"); } set { this.SetValue("defPlayerDmgCorrectRate_Magic", value); } }
    public float defPlayerDmgCorrectRate_Fire { get { return this.GetValue<float>("defPlayerDmgCorrectRate_Fire"); } set { this.SetValue("defPlayerDmgCorrectRate_Fire", value); } }
    public float defPlayerDmgCorrectRate_Thunder { get { return this.GetValue<float>("defPlayerDmgCorrectRate_Thunder"); } set { this.SetValue("defPlayerDmgCorrectRate_Thunder", value); } }
    public float defPlayerDmgCorrectRate_Dark { get { return this.GetValue<float>("defPlayerDmgCorrectRate_Dark"); } set { this.SetValue("defPlayerDmgCorrectRate_Dark", value); } }
    public float defEnemyDmgCorrectRate_Physics { get { return this.GetValue<float>("defEnemyDmgCorrectRate_Physics"); } set { this.SetValue("defEnemyDmgCorrectRate_Physics", value); } }
    public float defEnemyDmgCorrectRate_Magic { get { return this.GetValue<float>("defEnemyDmgCorrectRate_Magic"); } set { this.SetValue("defEnemyDmgCorrectRate_Magic", value); } }
    public float defEnemyDmgCorrectRate_Fire { get { return this.GetValue<float>("defEnemyDmgCorrectRate_Fire"); } set { this.SetValue("defEnemyDmgCorrectRate_Fire", value); } }
    public float defEnemyDmgCorrectRate_Thunder { get { return this.GetValue<float>("defEnemyDmgCorrectRate_Thunder"); } set { this.SetValue("defEnemyDmgCorrectRate_Thunder", value); } }
    public float defEnemyDmgCorrectRate_Dark { get { return this.GetValue<float>("defEnemyDmgCorrectRate_Dark"); } set { this.SetValue("defEnemyDmgCorrectRate_Dark", value); } }
    public float defObjDmgCorrectRate { get { return this.GetValue<float>("defObjDmgCorrectRate"); } set { this.SetValue("defObjDmgCorrectRate", value); } }
    public float atkPlayerDmgCorrectRate_Physics { get { return this.GetValue<float>("atkPlayerDmgCorrectRate_Physics"); } set { this.SetValue("atkPlayerDmgCorrectRate_Physics", value); } }
    public float atkPlayerDmgCorrectRate_Magic { get { return this.GetValue<float>("atkPlayerDmgCorrectRate_Magic"); } set { this.SetValue("atkPlayerDmgCorrectRate_Magic", value); } }
    public float atkPlayerDmgCorrectRate_Fire { get { return this.GetValue<float>("atkPlayerDmgCorrectRate_Fire"); } set { this.SetValue("atkPlayerDmgCorrectRate_Fire", value); } }
    public float atkPlayerDmgCorrectRate_Thunder { get { return this.GetValue<float>("atkPlayerDmgCorrectRate_Thunder"); } set { this.SetValue("atkPlayerDmgCorrectRate_Thunder", value); } }
    public float atkPlayerDmgCorrectRate_Dark { get { return this.GetValue<float>("atkPlayerDmgCorrectRate_Dark"); } set { this.SetValue("atkPlayerDmgCorrectRate_Dark", value); } }
    public float atkEnemyDmgCorrectRate_Physics { get { return this.GetValue<float>("atkEnemyDmgCorrectRate_Physics"); } set { this.SetValue("atkEnemyDmgCorrectRate_Physics", value); } }
    public float atkEnemyDmgCorrectRate_Magic { get { return this.GetValue<float>("atkEnemyDmgCorrectRate_Magic"); } set { this.SetValue("atkEnemyDmgCorrectRate_Magic", value); } }
    public float atkEnemyDmgCorrectRate_Fire { get { return this.GetValue<float>("atkEnemyDmgCorrectRate_Fire"); } set { this.SetValue("atkEnemyDmgCorrectRate_Fire", value); } }
    public float atkEnemyDmgCorrectRate_Thunder { get { return this.GetValue<float>("atkEnemyDmgCorrectRate_Thunder"); } set { this.SetValue("atkEnemyDmgCorrectRate_Thunder", value); } }
    public float atkEnemyDmgCorrectRate_Dark { get { return this.GetValue<float>("atkEnemyDmgCorrectRate_Dark"); } set { this.SetValue("atkEnemyDmgCorrectRate_Dark", value); } }
    public float registFreezeChangeRate { get { return this.GetValue<float>("registFreezeChangeRate"); } set { this.SetValue("registFreezeChangeRate", value); } }
    public ushort invocationConditionsStateChange1 { get { return this.GetValue<ushort>("invocationConditionsStateChange1"); } set { this.SetValue("invocationConditionsStateChange1", value); } }
    public ushort invocationConditionsStateChange2 { get { return this.GetValue<ushort>("invocationConditionsStateChange2"); } set { this.SetValue("invocationConditionsStateChange2", value); } }
    public ushort invocationConditionsStateChange3 { get { return this.GetValue<ushort>("invocationConditionsStateChange3"); } set { this.SetValue("invocationConditionsStateChange3", value); } }
    public short hearingAiSoundLevel { get { return this.GetValue<short>("hearingAiSoundLevel"); } set { this.SetValue("hearingAiSoundLevel", value); } }
    public float chrProxyHeightRate { get { return this.GetValue<float>("chrProxyHeightRate"); } set { this.SetValue("chrProxyHeightRate", value); } }
    public float addAwarePointCorrectValue_forMe { get { return this.GetValue<float>("addAwarePointCorrectValue_forMe"); } set { this.SetValue("addAwarePointCorrectValue_forMe", value); } }
    public float addAwarePointCorrectValue_forTarget { get { return this.GetValue<float>("addAwarePointCorrectValue_forTarget"); } set { this.SetValue("addAwarePointCorrectValue_forTarget", value); } }
    public float sightSearchEnemyAdd { get { return this.GetValue<float>("sightSearchEnemyAdd"); } set { this.SetValue("sightSearchEnemyAdd", value); } }
    public float sightSearchAdd { get { return this.GetValue<float>("sightSearchAdd"); } set { this.SetValue("sightSearchAdd", value); } }
    public float hearingSearchAdd { get { return this.GetValue<float>("hearingSearchAdd"); } set { this.SetValue("hearingSearchAdd", value); } }
    public float hearingSearchRate { get { return this.GetValue<float>("hearingSearchRate"); } set { this.SetValue("hearingSearchRate", value); } }
    public float hearingSearchEnemyAdd { get { return this.GetValue<float>("hearingSearchEnemyAdd"); } set { this.SetValue("hearingSearchEnemyAdd", value); } }
    public float value_Magnification { get { return this.GetValue<float>("value_Magnification"); } set { this.SetValue("value_Magnification", value); } }
    public float artsConsumptionRate { get { return this.GetValue<float>("artsConsumptionRate"); } set { this.SetValue("artsConsumptionRate", value); } }
    public float magicConsumptionRate { get { return this.GetValue<float>("magicConsumptionRate"); } set { this.SetValue("magicConsumptionRate", value); } }
    public float shamanConsumptionRate { get { return this.GetValue<float>("shamanConsumptionRate"); } set { this.SetValue("shamanConsumptionRate", value); } }
    public float miracleConsumptionRate { get { return this.GetValue<float>("miracleConsumptionRate"); } set { this.SetValue("miracleConsumptionRate", value); } }
    public int changeHpEstusFlaskRate { get { return this.GetValue<int>("changeHpEstusFlaskRate"); } set { this.SetValue("changeHpEstusFlaskRate", value); } }
    public int changeHpEstusFlaskPoint { get { return this.GetValue<int>("changeHpEstusFlaskPoint"); } set { this.SetValue("changeHpEstusFlaskPoint", value); } }
    public int changeMpEstusFlaskRate { get { return this.GetValue<int>("changeMpEstusFlaskRate"); } set { this.SetValue("changeMpEstusFlaskRate", value); } }
    public int changeMpEstusFlaskPoint { get { return this.GetValue<int>("changeMpEstusFlaskPoint"); } set { this.SetValue("changeMpEstusFlaskPoint", value); } }
    public float changeHpEstusFlaskCorrectRate { get { return this.GetValue<float>("changeHpEstusFlaskCorrectRate"); } set { this.SetValue("changeHpEstusFlaskCorrectRate", value); } }
    public float changeMpEstusFlaskCorrectRate { get { return this.GetValue<float>("changeMpEstusFlaskCorrectRate"); } set { this.SetValue("changeMpEstusFlaskCorrectRate", value); } }
    public int applyIdOnGetSoul { get { return this.GetValue<int>("applyIdOnGetSoul"); } set { this.SetValue("applyIdOnGetSoul", value); } }
    public float extendLifeRate { get { return this.GetValue<float>("extendLifeRate"); } set { this.SetValue("extendLifeRate", value); } }
    public float contractLifeRate { get { return this.GetValue<float>("contractLifeRate"); } set { this.SetValue("contractLifeRate", value); } }
    public float defObjectAttackPowerRate { get { return this.GetValue<float>("defObjectAttackPowerRate"); } set { this.SetValue("defObjectAttackPowerRate", value); } }
    public short effectEndDeleteDecalGroupId { get { return this.GetValue<short>("effectEndDeleteDecalGroupId"); } set { this.SetValue("effectEndDeleteDecalGroupId", value); } }
    public sbyte addLifeForceStatus { get { return this.GetValue<sbyte>("addLifeForceStatus"); } set { this.SetValue("addLifeForceStatus", value); } }
    public sbyte addWillpowerStatus { get { return this.GetValue<sbyte>("addWillpowerStatus"); } set { this.SetValue("addWillpowerStatus", value); } }
    public sbyte addEndureStatus { get { return this.GetValue<sbyte>("addEndureStatus"); } set { this.SetValue("addEndureStatus", value); } }
    public sbyte addVitalityStatus { get { return this.GetValue<sbyte>("addVitalityStatus"); } set { this.SetValue("addVitalityStatus", value); } }
    public sbyte addStrengthStatus { get { return this.GetValue<sbyte>("addStrengthStatus"); } set { this.SetValue("addStrengthStatus", value); } }
    public sbyte addDexterityStatus { get { return this.GetValue<sbyte>("addDexterityStatus"); } set { this.SetValue("addDexterityStatus", value); } }
    public sbyte addMagicStatus { get { return this.GetValue<sbyte>("addMagicStatus"); } set { this.SetValue("addMagicStatus", value); } }
    public sbyte addFaithStatus { get { return this.GetValue<sbyte>("addFaithStatus"); } set { this.SetValue("addFaithStatus", value); } }
    public sbyte addLuckStatus { get { return this.GetValue<sbyte>("addLuckStatus"); } set { this.SetValue("addLuckStatus", value); } }
    public byte deleteCriteriaDamage { get { return this.GetValue<byte>("deleteCriteriaDamage"); } set { this.SetValue("deleteCriteriaDamage", value); } }
    public byte magicSubCategoryChange3 { get { return this.GetValue<byte>("magicSubCategoryChange3"); } set { this.SetValue("magicSubCategoryChange3", value); } }
    public byte spAttributeVariationValue { get { return this.GetValue<byte>("spAttributeVariationValue"); } set { this.SetValue("spAttributeVariationValue", value); } }
    public byte atkFlickPower { get { return this.GetValue<byte>("atkFlickPower"); } set { this.SetValue("atkFlickPower", value); } }
    public byte wetConditionDepth { get { return this.GetValue<byte>("wetConditionDepth"); } set { this.SetValue("wetConditionDepth", value); } }
    public float changeSaRecoveryVelocity { get { return this.GetValue<float>("changeSaRecoveryVelocity"); } set { this.SetValue("changeSaRecoveryVelocity", value); } }
    public float regainRate { get { return this.GetValue<float>("regainRate"); } set { this.SetValue("regainRate", value); } }
    public float saAttackPowerRate { get { return this.GetValue<float>("saAttackPowerRate"); } set { this.SetValue("saAttackPowerRate", value); } }
    public int sleepAttackPower { get { return this.GetValue<int>("sleepAttackPower"); } set { this.SetValue("sleepAttackPower", value); } }
    public int madnessAttackPower { get { return this.GetValue<int>("madnessAttackPower"); } set { this.SetValue("madnessAttackPower", value); } }
    public float registSleepChangeRate { get { return this.GetValue<float>("registSleepChangeRate"); } set { this.SetValue("registSleepChangeRate", value); } }
    public float registMadnessChangeRate { get { return this.GetValue<float>("registMadnessChangeRate"); } set { this.SetValue("registMadnessChangeRate", value); } }
    public int changeSleepResistPoint { get { return this.GetValue<int>("changeSleepResistPoint"); } set { this.SetValue("changeSleepResistPoint", value); } }
    public int changeMadnessResistPoint { get { return this.GetValue<int>("changeMadnessResistPoint"); } set { this.SetValue("changeMadnessResistPoint", value); } }
    public byte sleepDamageRate { get { return this.GetValue<byte>("sleepDamageRate"); } set { this.SetValue("sleepDamageRate", value); } }
    public byte applyPartsGroup { get { return this.GetValue<byte>("applyPartsGroup"); } set { this.SetValue("applyPartsGroup", value); } }
    public byte clearTarget { get { return this.GetValue<byte>("clearTarget"); } set { this.SetValue("clearTarget", value); } }
    public byte fakeTargetIgnoreAjin { get { return this.GetValue<byte>("fakeTargetIgnoreAjin"); } set { this.SetValue("fakeTargetIgnoreAjin", value); } }
    public byte fakeTargetIgnoreMirageArts { get { return this.GetValue<byte>("fakeTargetIgnoreMirageArts"); } set { this.SetValue("fakeTargetIgnoreMirageArts", value); } }
    public byte requestForceJoinBlackSOS_B { get { return this.GetValue<byte>("requestForceJoinBlackSOS_B"); } set { this.SetValue("requestForceJoinBlackSOS_B", value); } }
    public byte isDestinedDeathHpMult { get { return this.GetValue<byte>("isDestinedDeathHpMult"); } set { this.SetValue("isDestinedDeathHpMult", value); } }
    public byte isHpBurnEffect { get { return this.GetValue<byte>("isHpBurnEffect"); } set { this.SetValue("isHpBurnEffect", value); } }
    public byte unknown_0x352_6 { get { return this.GetValue<byte>("unknown_0x352_6"); } set { this.SetValue("unknown_0x352_6", value); } }
    public byte unknown_0x352_7 { get { return this.GetValue<byte>("unknown_0x352_7"); } set { this.SetValue("unknown_0x352_7", value); } }
    public byte unknown_0x353_0 { get { return this.GetValue<byte>("unknown_0x353_0"); } set { this.SetValue("unknown_0x353_0", value); } }
    public byte unknown_0x353_1 { get { return this.GetValue<byte>("unknown_0x353_1"); } set { this.SetValue("unknown_0x353_1", value); } }
    public byte unknown_0x353_2 { get { return this.GetValue<byte>("unknown_0x353_2"); } set { this.SetValue("unknown_0x353_2", value); } }
    public byte unknown_0x353_3 { get { return this.GetValue<byte>("unknown_0x353_3"); } set { this.SetValue("unknown_0x353_3", value); } }
    public byte unknown_0x353_4 { get { return this.GetValue<byte>("unknown_0x353_4"); } set { this.SetValue("unknown_0x353_4", value); } }
    public byte unknown_0x353_5 { get { return this.GetValue<byte>("unknown_0x353_5"); } set { this.SetValue("unknown_0x353_5", value); } }
    public float changeSuperArmorPoint { get { return this.GetValue<float>("changeSuperArmorPoint"); } set { this.SetValue("changeSuperArmorPoint", value); } }
    public float changeSaPoint { get { return this.GetValue<float>("changeSaPoint"); } set { this.SetValue("changeSaPoint", value); } }
    public float hugeEnemyPickupHeightOverwrite { get { return this.GetValue<float>("hugeEnemyPickupHeightOverwrite"); } set { this.SetValue("hugeEnemyPickupHeightOverwrite", value); } }
    public float poisonDefDamageRate { get { return this.GetValue<float>("poisonDefDamageRate"); } set { this.SetValue("poisonDefDamageRate", value); } }
    public float diseaseDefDamageRate { get { return this.GetValue<float>("diseaseDefDamageRate"); } set { this.SetValue("diseaseDefDamageRate", value); } }
    public float bloodDefDamageRate { get { return this.GetValue<float>("bloodDefDamageRate"); } set { this.SetValue("bloodDefDamageRate", value); } }
    public float curseDefDamageRate { get { return this.GetValue<float>("curseDefDamageRate"); } set { this.SetValue("curseDefDamageRate", value); } }
    public float freezeDefDamageRate { get { return this.GetValue<float>("freezeDefDamageRate"); } set { this.SetValue("freezeDefDamageRate", value); } }
    public float sleepDefDamageRate { get { return this.GetValue<float>("sleepDefDamageRate"); } set { this.SetValue("sleepDefDamageRate", value); } }
    public float madnessDefDamageRate { get { return this.GetValue<float>("madnessDefDamageRate"); } set { this.SetValue("madnessDefDamageRate", value); } }
    public ushort overwrite_maxBackhomeDist { get { return this.GetValue<ushort>("overwrite_maxBackhomeDist"); } set { this.SetValue("overwrite_maxBackhomeDist", value); } }
    public ushort overwrite_backhomeDist { get { return this.GetValue<ushort>("overwrite_backhomeDist"); } set { this.SetValue("overwrite_backhomeDist", value); } }
    public ushort overwrite_backhomeBattleDist { get { return this.GetValue<ushort>("overwrite_backhomeBattleDist"); } set { this.SetValue("overwrite_backhomeBattleDist", value); } }
    public ushort overwrite_BackHome_LookTargetDist { get { return this.GetValue<ushort>("overwrite_BackHome_LookTargetDist"); } set { this.SetValue("overwrite_BackHome_LookTargetDist", value); } }
    public float goodsConsumptionRate { get { return this.GetValue<float>("goodsConsumptionRate"); } set { this.SetValue("goodsConsumptionRate", value); } }
    public float guardStaminaMult { get { return this.GetValue<float>("guardStaminaMult"); } set { this.SetValue("guardStaminaMult", value); } }
    public int spiritDeathSpEffectId { get { return this.GetValue<int>("spiritDeathSpEffectId"); } set { this.SetValue("spiritDeathSpEffectId", value); } }
}
